CreateGroup_HDF5 – SELF
CreateGroup_HDF5 Subroutine
3-Clause BSD with attribution
23 statements
Source File
public subroutine CreateGroup_HDF5(fileId, groupName)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: groupName
Calls
Called by
Contents
Source Code
CreateGroup_HDF5
Source Code
  subroutine CreateGroup_HDF5(fileId,groupName)
#undef __FUNC__
#define __FUNC__ "CreateGroup_HDF5"
    implicit none
    integer(HID_T),intent(in) :: fileId
    character(*),intent(in) :: groupName
    ! Local
    integer(HID_T) :: groupId
    logical :: groupExists
    integer :: error
    call h5lexists_f(fileId,trim(groupName),groupExists,error)
    if(error /= 0) then
      print*,__FILE__," : Link check failure for "//trim(groupName)
    else
      if(.not. groupExists) then
        ! Create groups
        call h5gcreate_f(fileId,trim(groupName),groupId,error)
        if(error /= 0) then
          print*,__FILE__," :Failed to create group "//trim(groupName)
        endif
        call h5gclose_f(groupId,error)
        if(error /= 0) then
          print*,__FILE__," :Failed to close group "//trim(groupName)
        endif
      endif
    endif
  endsubroutine CreateGroup_HDF5
Call graph
creategroup_hdf5 calls h5lexists_f, h5gcreate_f, h5gclose_f
write_dgmodel3d_t calls creategroup_hdf5
writehdf5_vector2d_t calls creategroup_hdf5
writehdf5_mpi_scalar2d_t calls creategroup_hdf5
writehdf5_mpi_vector3d_t calls creategroup_hdf5
writehdf5_lagrange_t calls creategroup_hdf5
write_geometry1d calls creategroup_hdf5
writehdf5_metadata calls creategroup_hdf5
writehdf5_scalar1d_t calls creategroup_hdf5
writehdf5_scalar3d_t calls creategroup_hdf5
write_dgmodel1d_t calls creategroup_hdf5
write_dgmodel2d_t calls creategroup_hdf5
writehdf5_scalar2d_t calls creategroup_hdf5
writehdf5_mpi_vector2d_t calls creategroup_hdf5
writehdf5_vector3d_t calls creategroup_hdf5
writehdf5_mpi_scalar3d_t calls creategroup_hdf5