Divergence_Vector3D – SELF
Divergence_Vector3D Subroutine
3-Clause BSD with attribution
15 statements
Source File
public subroutine Divergence_Vector3D(this, df)
Arguments
Type Intent Optional Attributes Name
class(Vector3D), intent(in) :: this
type(c_ptr), intent(inout) :: df
Calls
Contents
Source Code
Divergence_Vector3D
Source Code
  subroutine Divergence_Vector3D(this,df)
    implicit none
    class(Vector3D),intent(in) :: this
    type(c_ptr),intent(inout) :: df
    !Local
    real(prec),pointer :: f_p(:,:,:,:,:,:)
    type(c_ptr) :: fc
    call c_f_pointer(this%interior_gpu,f_p, &
                     [this%interp%N+1,this%interp%N+1,this%interp%N+1,this%nelem,this%nvar,3])
    fc = c_loc(f_p(1,1,1,1,1,1))
    call self_blas_matrixop_dim1_3d(this%interp%dMatrix_gpu,fc,df, &
                                    this%interp%N,this%interp%N,this%nvar,this%nelem,this%blas_handle)
    fc = c_loc(f_p(1,1,1,1,1,2))
    call self_blas_matrixop_dim2_3d(this%interp%dMatrix_gpu,fc,df, &
                                    1.0_c_prec,this%interp%N,this%interp%N,this%nvar,this%nelem,this%blas_handle)
    fc = c_loc(f_p(1,1,1,1,1,3))
    call self_blas_matrixop_dim3_3d(this%interp%dMatrix_gpu,fc,df, &
                                    1.0_c_prec,this%interp%N,this%interp%N,this%nvar,this%nelem,this%blas_handle)
    f_p => null()
  endsubroutine Divergence_Vector3D
Call graph
divergence_vector3d calls self_blas_matrixop_dim1_3d, self_blas_matrixop_dim3_3d, self_blas_matrixop_dim2_3d
self_blas_matrixop_dim1_3d calls hipblasgemm, hipblascheck
self_blas_matrixop_dim3_3d calls hipblasgemvstridedbatched, hipblascheck
self_blas_matrixop_dim2_3d calls hipblasgemvstridedbatched, hipblascheck