Free_DomainDecomposition – SELF
Free_DomainDecomposition Subroutine
3-Clause BSD with attribution
16 statements
Source File
public subroutine Free_DomainDecomposition(this)
Arguments
Type Intent Optional Attributes Name
class(DomainDecomposition), intent(inout) :: this
Calls
Contents
Source Code
Free_DomainDecomposition
Source Code
  subroutine Free_DomainDecomposition(this)
    implicit none
    class(DomainDecomposition),intent(inout) :: this
    ! Local
    integer :: ierror
    if(associated(this%offSetElem)) then
      deallocate(this%offSetElem)
    endif
    if(associated(this%elemToRank)) then
      deallocate(this%elemToRank)
      call gpuCheck(hipFree(this%elemToRank_gpu))
    endif
    if(allocated(this%requests)) deallocate(this%requests)
    if(allocated(this%stats)) deallocate(this%stats)
    print*,__FILE__," : Rank ",this%rankId+1,"/",this%nRanks," checking out."
    call MPI_FINALIZE(ierror)
  endsubroutine Free_DomainDecomposition
Call graph
free_domaindecomposition calls hipfree, gpucheck, mpi_finalize