gpuCheck – SELF
gpuCheck Subroutine
3-Clause BSD with attribution
9 statements
Source File
public subroutine gpuCheck(gpuError_t)
Uses
iso_c_binding
Arguments
Type Intent Optional Attributes Name
integer(kind=c_int) :: gpuError_t
Called by
Contents
Source Code
gpuCheck
Source Code
                      subroutine gpuCheck(gpuError_t)
                        use iso_c_binding
                        implicit none
                        integer(c_int) :: gpuError_t
                        if(gpuError_t /= hipSuccess) then
                          write(*,*) "GPU ERROR: Error code = ",gpuError_t
                          call exit(gpuError_t)
                        endif
                      endsubroutine gpuCheck
Call graph
boundaryflux_dgmodel3d calls gpucheck
sourcemethod_ecadvection3d calls gpucheck
free_tensor2d calls gpucheck
init_scalar1d calls gpucheck
free_vector3d calls gpucheck
free_dgmodel2d calls gpucheck
sourcemethod_dgmodel3d calls gpucheck
buildhaloexchange_domaindecomposition calls gpucheck
init_esatmo3d calls gpucheck
setgradientboundarycondition_dgmodel1d calls gpucheck
setinteriorfromequation_mappedscalar2d calls gpucheck
updatehost_twopointvector2d calls gpucheck
calculateentropy_dgmodel3d calls gpucheck
init_tensor2d calls gpucheck
updatedevice_scalar1d calls gpucheck
init_dgmodel2d calls gpucheck
updatehost_scalar3d calls gpucheck
setinteriorfromequation_mappedscalar3d calls gpucheck
setinteriorfromequation_mappedvector3d calls gpucheck
sourcemethod_dgmodel1d calls gpucheck
free_mesh3d calls gpucheck
free_points calls gpucheck
updatedevice_tensor2d calls gpucheck
updatehost_scalar1d calls gpucheck
free_scalar2d calls gpucheck
free_mappedscalar2d calls gpucheck
free_domaindecomposition calls gpucheck
free_mesh2d calls gpucheck
sideexchangestart_mappedscalar2d calls gpucheck
init_mesh3d calls gpucheck
updatehost_tensor2d calls gpucheck
free_dgmodel1d calls gpucheck
init_mappedscalar2d calls gpucheck
sideexchangestart_mappedscalar3d calls gpucheck
free_twopointvector3d calls gpucheck
free_scalar1d calls gpucheck
init_mesh2d calls gpucheck
updatedevice_mesh3d calls gpucheck
free_mappedscalar3d calls gpucheck
init_points calls gpucheck
init_vector3d calls gpucheck
init_vector2d calls gpucheck
free_dgmodel3d calls gpucheck
free_ecadvection2d calls gpucheck
init_dgmodel1d calls gpucheck
free_mappedvector2d calls gpucheck, free_vector2d
updatedevice_mesh2d calls gpucheck
updatedevice_vector2d calls gpucheck
init_dgmodel3d calls gpucheck
init_twopointvector3d calls gpucheck
setinteriorfromequation_mappedscalar1d calls gpucheck
free_scalar3d calls gpucheck
init_mappedscalar3d calls gpucheck
setinteriorfromequation_mappedvector2d calls gpucheck
updatehost_vector2d calls gpucheck
updatedevice_vector3d calls gpucheck
free_esatmo2d calls gpucheck
init_ecadvection2d calls gpucheck
setelemtorank_domaindecomposition calls gpucheck
free_tensor3d calls gpucheck
updatedevice_twopointvector3d calls gpucheck
sideexchange_mappedscalar1d calls gpucheck
updatedevice_points calls gpucheck
boundaryflux_dgmodel2d calls gpucheck
updatehost_vector3d calls gpucheck
init_scalar2d calls gpucheck
fluxmethod_dgmodel2d calls gpucheck
sourcemethod_ecadvection2d calls gpucheck
mpiexchangeasync_mappedvector2d calls gpucheck
updatehost_twopointvector3d calls gpucheck
boundaryflux_dgmodel1d calls gpucheck
free_ecadvection3d calls gpucheck
init_tensor3d calls gpucheck
calculateentropy_dgmodel2d calls gpucheck
init_esatmo2d calls gpucheck
free_twopointvector2d calls gpucheck
free_vector2d calls gpucheck
calculateentropy_dgmodel1d calls gpucheck
init_scalar3d calls gpucheck
updatedevice_tensor3d calls gpucheck
free_mappedvector3d calls gpucheck, free_vector3d
free_lagrange calls gpucheck
updatedevice_scalar2d calls gpucheck
free_esatmo3d calls gpucheck
sourcemethod_dgmodel2d calls gpucheck
fluxmethod_dgmodel1d calls gpucheck
init_twopointvector2d calls gpucheck
init_ecadvection3d calls gpucheck
updatedevice_scalar3d calls gpucheck
updatehost_tensor3d calls gpucheck
mpiexchangeasync_mappedvector3d calls gpucheck
fluxmethod_dgmodel3d calls gpucheck
init_lagrange calls gpucheck
updatedevice_twopointvector2d calls gpucheck
updatehost_scalar2d calls gpucheck
setboundarycondition_dgmodel1d calls gpucheck