GridInterp_Scalar2D – SELF
GridInterp_Scalar2D Subroutine
3-Clause BSD with attribution
7 statements
Source File
public subroutine GridInterp_Scalar2D(this, f)
Arguments
Type Intent Optional Attributes Name
class(Scalar2D), intent(inout) :: this
type(c_ptr), intent(inout) :: f
Calls
Contents
Source Code
GridInterp_Scalar2D
Source Code
  subroutine GridInterp_Scalar2D(this,f)
    implicit none
    class(Scalar2D),intent(inout) :: this
    type(c_ptr),intent(inout) :: f
    call self_blas_matrixop_dim1_2d(this%interp%iMatrix_gpu,this%interior_gpu, &
                                    this%interpWork,this%N,this%M,this%nvar,this%nelem, &
                                    this%blas_handle)
    call self_blas_matrixop_dim2_2d(this%interp%iMatrix_gpu,this%interpWork,f, &
                                    0.0_c_prec,this%N,this%M,this%nvar,this%nelem, &
                                    this%blas_handle)
  endsubroutine GridInterp_Scalar2D
Call graph
gridinterp_scalar2d calls self_blas_matrixop_dim1_2d, self_blas_matrixop_dim2_2d
self_blas_matrixop_dim1_2d calls hipblasgemm, hipblascheck
self_blas_matrixop_dim2_2d calls hipblasgemvstridedbatched, hipblascheck