GridInterp_Vector3D – SELF
GridInterp_Vector3D Subroutine
3-Clause BSD with attribution
8 statements
Source File
public subroutine GridInterp_Vector3D(this, f)
Arguments
Type Intent Optional Attributes Name
class(Vector3D), intent(inout) :: this
type(c_ptr), intent(inout) :: f
Calls
Contents
Source Code
GridInterp_Vector3D
Source Code
  subroutine GridInterp_Vector3D(this,f)
    implicit none
    class(Vector3D),intent(inout) :: this
    type(c_ptr),intent(inout) :: f
    call self_blas_matrixop_dim1_3d(this%interp%iMatrix_gpu,this%interior_gpu, &
                                    this%interpWork1,this%N,this%M,3*this%nvar,this%nelem, &
                                    this%blas_handle)
    call self_blas_matrixop_dim2_3d(this%interp%iMatrix_gpu,this%interpWork1,this%interpWork2, &
                                    0.0_c_prec,this%N,this%M,3*this%nvar,this%nelem, &
                                    this%blas_handle)
    call self_blas_matrixop_dim3_3d(this%interp%iMatrix_gpu,this%interpWork2,f, &
                                    0.0_c_prec,this%N,this%M,3*this%nvar,this%nelem, &
                                    this%blas_handle)
  endsubroutine GridInterp_Vector3D
Call graph
gridinterp_vector3d calls self_blas_matrixop_dim1_3d, self_blas_matrixop_dim3_3d, self_blas_matrixop_dim2_3d
self_blas_matrixop_dim1_3d calls hipblasgemm, hipblascheck
self_blas_matrixop_dim3_3d calls hipblasgemvstridedbatched, hipblascheck
self_blas_matrixop_dim2_3d calls hipblasgemvstridedbatched, hipblascheck