hipblasCheck – SELF
hipblasCheck Subroutine
3-Clause BSD with attribution
10 statements
Source File
public subroutine hipblasCheck(hipblasError_t)
Uses
iso_c_binding
SELF_GPU_enums
Arguments
Type Intent Optional Attributes Name
integer(kind=c_int) :: hipblasError_t
Called by
Contents
Source Code
hipblasCheck
Source Code
                          subroutine hipblasCheck(hipblasError_t)
                            use SELF_GPU_enums
                            use iso_c_binding
                            implicit none
                            integer(c_int) :: hipblasError_t
                            if(hipblasError_t /= HIPBLAS_STATUS_SUCCESS) then
                              write(*,*) "GPUBLAS ERROR: Error code = ",hipblasError_t
                              call exit(hipblasError_t)
                            endif
                          endsubroutine hipblasCheck
Call graph
self_blas_matrixop_dim1_3d calls hipblascheck
init_scalar2d calls hipblascheck
init_mappedscalar2d calls hipblascheck
init_tensor2d calls hipblascheck
free_scalar1d calls hipblascheck
self_blas_matrixop_dim1_2d calls hipblascheck
self_blas_matrixop_dim2_2d calls hipblascheck
free_mappedscalar3d calls hipblascheck
free_tensor2d calls hipblascheck
self_blas_matrixop_dim3_3d calls hipblascheck
free_tensor3d calls hipblascheck
free_scalar2d calls hipblascheck
free_scalar3d calls hipblascheck
free_vector2d calls hipblascheck
free_vector3d calls hipblascheck
init_tensor3d calls hipblascheck
init_scalar3d calls hipblascheck
init_vector2d calls hipblascheck
init_vector3d calls hipblascheck
self_blas_matrixop_dim2_3d calls hipblascheck
init_mappedscalar3d calls hipblascheck
free_mappedscalar2d calls hipblascheck
self_blas_matrixop_1d calls hipblascheck
init_scalar1d calls hipblascheck
mappeddggradient_mappedscalar3d calls self_blas_matrixop_dim1_3d, self_blas_matrixop_dim3_3d, self_blas_matrixop_dim2_3d
gridinterp_scalar3d calls self_blas_matrixop_dim1_3d, self_blas_matrixop_dim3_3d, self_blas_matrixop_dim2_3d
gridinterp_vector3d calls self_blas_matrixop_dim1_3d, self_blas_matrixop_dim3_3d, self_blas_matrixop_dim2_3d
gradient_scalar2d calls self_blas_matrixop_dim1_2d, self_blas_matrixop_dim2_2d
mappedgradient_mappedscalar2d calls self_blas_matrixop_dim1_2d, self_blas_matrixop_dim2_2d
gridinterp_vector2d calls self_blas_matrixop_dim1_2d, self_blas_matrixop_dim2_2d
mappeddgderivative_mappedscalar1d calls self_blas_matrixop_1d
derivative_scalar1d calls self_blas_matrixop_1d
gridinterp_scalar1d calls self_blas_matrixop_1d
divergence_vector3d calls self_blas_matrixop_dim1_3d, self_blas_matrixop_dim3_3d, self_blas_matrixop_dim2_3d
gradient_scalar3d calls self_blas_matrixop_dim1_3d, self_blas_matrixop_dim3_3d, self_blas_matrixop_dim2_3d
mappedgradient_mappedscalar3d calls self_blas_matrixop_dim1_3d, self_blas_matrixop_dim3_3d, self_blas_matrixop_dim2_3d
gradient_vector3d calls self_blas_matrixop_dim1_3d, self_blas_matrixop_dim3_3d, self_blas_matrixop_dim2_3d
gradient_vector2d calls self_blas_matrixop_dim1_2d, self_blas_matrixop_dim2_2d
gridinterp_scalar2d calls self_blas_matrixop_dim1_2d, self_blas_matrixop_dim2_2d
mappeddggradient_mappedscalar2d calls self_blas_matrixop_dim1_2d, self_blas_matrixop_dim2_2d
boundaryinterp_scalar1d calls self_blas_matrixop_1d