hipblasCheck – SELF
hipblasCheck Subroutine
3-Clause BSD with attribution
9 statements
Source File
public subroutine hipblasCheck(hipblasError_t)
Uses
SELF_GPU_enums
Arguments
Type Intent Optional Attributes Name
integer(kind=kind(HIPBLAS_STATUS_SUCCESS)) :: hipblasError_t
Called by
Contents
Source Code
hipblasCheck
Source Code
                          subroutine hipblasCheck(hipblasError_t)
                            use SELF_GPU_enums
                            implicit none
                            integer(kind(HIPBLAS_STATUS_SUCCESS)) :: hipblasError_t
                            if(hipblasError_t /= HIPBLAS_STATUS_SUCCESS) then
                              write(*,*) "GPUBLAS ERROR: Error code = ",hipblasError_t
                              call exit(hipblasError_t)
                            endif
                          endsubroutine hipblasCheck
Call graph
self_blas_matrixop_1d calls hipblascheck
self_blas_matrixop_dim2_3d calls hipblascheck
self_blas_matrixop_dim1_3d calls hipblascheck
self_blas_matrixop_dim2_2d calls hipblascheck
self_blas_matrixop_dim1_2d calls hipblascheck
self_blas_matrixop_dim3_3d calls hipblascheck