Init_DGModel3D_t – SELF
Init_DGModel3D_t Subroutine
3-Clause BSD with attribution
25 statements
Source File
public subroutine Init_DGModel3D_t(this, mesh, geometry)
Arguments
Type Intent Optional Attributes Name
class(DGModel3D_t), intent(out) :: this
type(Mesh3D), intent(in), target :: mesh
type(SEMHex), intent(in), target :: geometry
Called by
Contents
Source Code
Init_DGModel3D_t
Source Code
  subroutine Init_DGModel3D_t(this,mesh,geometry)
    implicit none
    class(DGModel3D_t),intent(out) :: this
    type(Mesh3D),intent(in),target :: mesh
    type(SEMHex),intent(in),target :: geometry
    ! Local
    this%mesh => mesh
    this%geometry => geometry
    call this%SetNumberOfVariables()
    call this%solution%Init(geometry%x%interp,this%nvar,this%mesh%nElem)
    call this%workSol%Init(geometry%x%interp,this%nvar,this%mesh%nElem)
    call this%dSdt%Init(geometry%x%interp,this%nvar,this%mesh%nElem)
    call this%solutionGradient%Init(geometry%x%interp,this%nvar,this%mesh%nElem)
    call this%flux%Init(geometry%x%interp,this%nvar,this%mesh%nElem)
    call this%source%Init(geometry%x%interp,this%nvar,this%mesh%nElem)
    call this%fluxDivergence%Init(geometry%x%interp,this%nvar,this%mesh%nElem)
    call this%solution%AssociateGeometry(geometry)
    call this%solutionGradient%AssociateGeometry(geometry)
    call this%flux%AssociateGeometry(geometry)
    call this%fluxDivergence%AssociateGeometry(geometry)
    call this%hyperbolicBCs%Init()
    call this%parabolicBCs%Init()
    call this%AdditionalInit()
    call this%MapBoundaryConditions()
    call this%SetMetadata()
  endsubroutine Init_DGModel3D_t
Call graph
init_ecdgmodel3d_t calls init_dgmodel3d_t
init_dgmodel3d calls init_dgmodel3d_t
init_ecadvection3d calls init_ecdgmodel3d_t