Init_ECAdvection2D – SELF
Init_ECAdvection2D Subroutine
3-Clause BSD with attribution
18 statements
Source File
public subroutine Init_ECAdvection2D(this, mesh, geometry)
Initialize EC Advection 2D, then upload BC element/side arrays to GPU.
Arguments
Type Intent Optional Attributes Name
class(ECAdvection2D), intent(out) :: this
type(Mesh2D), intent(in), target :: mesh
type(SEMQuad), intent(in), target :: geometry
Calls
Contents
Source Code
Init_ECAdvection2D
Source Code
  subroutine Init_ECAdvection2D(this,mesh,geometry)
    !! Initialize EC Advection 2D, then upload BC element/side arrays to GPU.
    implicit none
    class(ECAdvection2D),intent(out) :: this
    type(Mesh2D),intent(in),target :: mesh
    type(SEMQuad),intent(in),target :: geometry
    ! Local
    type(BoundaryCondition),pointer :: bc
    call Init_ECDGModel2D_t(this,mesh,geometry)
    ! Upload hyperbolic BC element/side arrays to device
    bc => this%hyperbolicBCs%head
    do while(associated(bc))
      if(bc%nBoundaries > 0) then
        call gpuCheck(hipMalloc(bc%elements_gpu,sizeof(bc%elements)))
        call gpuCheck(hipMemcpy(bc%elements_gpu,c_loc(bc%elements), &
                                sizeof(bc%elements),hipMemcpyHostToDevice))
        call gpuCheck(hipMalloc(bc%sides_gpu,sizeof(bc%sides)))
        call gpuCheck(hipMemcpy(bc%sides_gpu,c_loc(bc%sides), &
                                sizeof(bc%sides),hipMemcpyHostToDevice))
      endif
      bc => bc%next
    enddo
  endsubroutine Init_ECAdvection2D
Call graph
init_ecadvection2d calls init_ecdgmodel2d_t, gpucheck, hipmemcpy, hipmalloc
init_ecdgmodel2d_t calls init_dgmodel2d_t