MappedDivergence_MappedVector3D – SELF
MappedDivergence_MappedVector3D Subroutine
3-Clause BSD with attribution
8 statements
Source File
public subroutine MappedDivergence_MappedVector3D(this, df)
Arguments
Type Intent Optional Attributes Name
class(MappedVector3D), intent(in) :: this
type(c_ptr), intent(inout) :: df
Calls
Contents
Source Code
MappedDivergence_MappedVector3D
Source Code
  subroutine MappedDivergence_MappedVector3D(this,df)
    ! Strong Form Operator
    !    !
    implicit none
    class(MappedVector3D),intent(in) :: this
    type(c_ptr),intent(inout) :: df
    ! Contravariant projection
    call ContravariantProjection_3D_gpu(this%interior_gpu, &
                                        this%geometry%dsdx%interior_gpu,this%interp%N,this%nvar,this%nelem)
    call Divergence_3D_gpu(this%interior_gpu,df,this%interp%dMatrix_gpu, &
                           this%interp%N,this%nvar,this%nelem)
    call JacobianWeight_3D_gpu(df,this%geometry%J%interior_gpu,this%interp%N,this%nVar,this%nelem)
  endsubroutine MappedDivergence_MappedVector3D
Call graph
mappeddivergence_mappedvector3d calls contravariantprojection_3d_gpu, divergence_3d_gpu, jacobianweight_3d_gpu