MappedDGDerivative_MappedScalar1D – SELF
MappedDGDerivative_MappedScalar1D Subroutine
3-Clause BSD with attribution
10 statements
Source File
public subroutine MappedDGDerivative_MappedScalar1D(this, df)
Arguments
Type Intent Optional Attributes Name
class(MappedScalar1D), intent(in) :: this
type(c_ptr), intent(inout) :: df
Calls
Contents
Source Code
MappedDGDerivative_MappedScalar1D
Source Code
  subroutine MappedDGDerivative_MappedScalar1D(this,dF)
    implicit none
    class(MappedScalar1D),intent(in) :: this
    type(c_ptr),intent(inout) :: df
    ! Local
    integer :: iEl,iVar,i,ii
    real(prec) :: dfloc
    call self_blas_matrixop_1d(this%interp%dgMatrix_gpu, &
                               this%interior_gpu, &
                               df,this%N+1,this%N+1, &
                               this%nvar*this%nelem,this%blas_handle)
    call DGDerivative_BoundaryContribution_1D_gpu(this%interp%bMatrix_gpu, &
                                                  this%interp%qWeights_gpu, &
                                                  this%boundarynormal_gpu,df, &
                                                  this%N,this%nVar,this%nelem)
    call JacobianWeight_1D_gpu(df,this%geometry%dxds%interior_gpu,this%N,this%nVar,this%nelem)
  endsubroutine MappedDGDerivative_MappedScalar1D
Call graph
mappeddgderivative_mappedscalar1d calls self_blas_matrixop_1d, dgderivative_boundarycontribution_1d_gpu, jacobianweight_1d_gpu
self_blas_matrixop_1d calls hipblasgemm, hipblascheck