newunit – SELF
newunit Function
3-Clause BSD with attribution
15 statements
Source File
public function newunit(unit)
Arguments
Type Intent Optional Attributes Name
integer, intent(out), optional :: unit
Return Value integer
Called by
Contents
Source Code
newunit
Source Code
  integer function newunit(unit)
    !  https://fortranwiki.org/fortran/show/newunit
    integer,intent(out),optional :: unit
! local
    integer,parameter :: LUN_MIN = 10,LUN_MAX = 1000
    logical :: opened
    integer :: lun
! begin
    newunit = -1
    do lun = LUN_MIN,LUN_MAX
      inquire(unit=lun,opened=opened)
      if(.not. opened) then
        newunit = lun
        exit
      endif
    enddo
    if(present(unit)) unit = newunit
  endfunction newunit
Call graph
writetecplot_dgmodel2d_t calls newunit
writetecplot_semquad calls newunit
writetecplot_dgmodel1d_t calls newunit
writetecplot_semhex calls newunit
writetecplot_dgmodel3d_t calls newunit