Open_HDF5_serial – SELF
Open_HDF5_serial Subroutine
3-Clause BSD with attribution
17 statements
Source File
private subroutine Open_HDF5_serial(fileName, accessFlag, fileId)
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: fileName
integer, intent(in) :: accessFlag
integer(kind=HID_T), intent(inout) :: fileId
Calls
Called by
Contents
Source Code
Open_HDF5_serial
Source Code
  subroutine Open_HDF5_serial(fileName,accessFlag,fileId)
    implicit none
    character(*),intent(in) :: fileName
    integer,intent(in) :: accessFlag
    integer(HID_T),intent(inout) :: fileId
    ! Local
    integer :: error
    call h5open_f(error)
    if(accessFlag == H5F_ACC_TRUNC_F) then
      call h5fcreate_f(trim(fileName),accessFlag,fileId,error)
    else
      call h5fopen_f(trim(fileName),accessFlag,fileId,error)
    endif
    if(error == -1) then
      print*,'Failed to open '//trim(fileName)//'.'
      stop 1
    endif
  endsubroutine Open_HDF5_serial
Call graph
open_hdf5_serial calls h5open_f, h5fopen_f, h5fcreate_f
open_hdf5 calls open_hdf5_serial
read_dgmodel2d_t calls open_hdf5
write_dgmodel3d_t calls open_hdf5
read_dgmodel3d_t calls open_hdf5
read_hopr_mesh2d_t calls open_hdf5
write_geometry1d calls open_hdf5
write_mesh3d_t calls open_hdf5
write_dgmodel1d_t calls open_hdf5
write_dgmodel2d_t calls open_hdf5
write_mesh2d_t calls open_hdf5
write_mesh1d calls open_hdf5
read_hopr_mesh3d_t calls open_hdf5
read_dgmodel1d_t calls open_hdf5