ReadAttribute_HDF5_character – SELF
ReadAttribute_HDF5_character Subroutine
3-Clause BSD with attribution
16 statements
Source File
private subroutine ReadAttribute_HDF5_character(fileId, attributeName, attribute)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: attributeName
character, intent(out) :: attribute
Calls
Called by
Contents
Source Code
ReadAttribute_HDF5_character
Source Code
  subroutine ReadAttribute_HDF5_character(fileId,attributeName,attribute)
    implicit none
    integer(HID_T),intent(in) :: fileId
    character(*),intent(in) :: attributeName
    character(*),intent(out) :: attribute
    ! Local
    integer(HID_T) :: attrId
    integer(HID_T) :: typeId
    integer(HSIZE_T) :: dims(1:1)
    integer :: error
    dims(1) = 1
    call h5aopen_f(fileId,trim(attributeName),attrId,error)
    call h5aget_type_f(attrId,typeId,error)
    call h5aread_f(attrId,typeId,attribute,dims,error)
    call h5tclose_f(typeId,error)
    call h5aclose_f(attrId,error)
  endsubroutine ReadAttribute_HDF5_character
Call graph
readattribute_hdf5_character calls h5aopen_f, h5aread_f, h5tclose_f, h5aclose_f, h5aget_type_f
readattribute_hdf5 calls readattribute_hdf5_character
read_hopr_mesh2d_t calls readattribute_hdf5
read_hopr_mesh3d_t calls readattribute_hdf5