Read_HOPr_Mesh1D_parallel – SELF
Read_HOPr_Mesh1D_parallel Subroutine
Anti-Capitalist Software License
45 statements
Source File
public subroutine Read_HOPr_Mesh1D_parallel(myMesh, meshFile, decomp)
Arguments
Type Intent Optional Attributes Name
class(Mesh1D), intent(out) :: myMesh
character, intent(in) :: meshFile
type(MPILayer), intent(inout) :: decomp
Calls
Contents
Source Code
Read_HOPr_Mesh1D_parallel
Source Code
  SUBROUTINE Read_HOPr_Mesh1D_parallel(myMesh,meshFile,decomp)
    ! From https://www.hopr-project.org/externals/Meshformat.pdf, Algorithm 6
    ! Adapted for 1D Mesh : Note that HOPR does not have 1D mesh output.
    IMPLICIT NONE
    CLASS(Mesh1D),INTENT(out) :: myMesh
    CHARACTER(*),INTENT(in) :: meshFile
    TYPE(MPILayer),INTENT(inout) :: decomp
    ! Local
    INTEGER(HID_T) :: fileId
    INTEGER(HID_T) :: offset(1:2),gOffset(1)
    INTEGER :: nGlobalElem
    INTEGER :: firstElem,nLocalElems
    INTEGER :: firstNode,nLocalNodes
    INTEGER :: nGeo,nBCs
    TYPE(hfInt32_r2) :: hopr_elemInfo
    TYPE(hfReal_r1) :: hopr_nodeCoords
    TYPE(hfInt32_r1) :: hopr_globalNodeIDs
    TYPE(hfInt32_r2) :: bcType
    CALL Open_HDF5(meshFile,H5F_ACC_RDWR_F,fileId,decomp % mpiComm)
    CALL ReadAttribute_HDF5(fileId,'nElems',nGlobalElem)
    CALL ReadAttribute_HDF5(fileId,'Ngeo',nGeo)
    CALL ReadAttribute_HDF5(fileId,'nBCs',nBCs)
    CALL decomp % SetElemToRank(nGlobalElem)
    ! Read BCType
    CALL bcType % Alloc(loBound=(/1,1/), &
                        upBound=(/4,nBCs/))
    offset(:) = 0
    CALL ReadArray_HDF5(fileId,'BCType',bcType,offset)
    ! Read local subarray of ElemInfo
    firstElem = decomp % offsetElem % hostData(decomp % rankId) + 1
    nLocalElems = decomp % offsetElem % hostData(decomp % rankId + 1) - &
                  decomp % offsetElem % hostData(decomp % rankId)
    ! Allocate Space for hopr_elemInfo!
    CALL hopr_elemInfo % Alloc(loBound=(/1,1/), &
                               upBound=(/6,nLocalElems/))
    offset = (/0,firstElem - 1/)
    CALL ReadArray_HDF5(fileId,'ElemInfo',hopr_elemInfo,offset)
    ! Read local subarray of NodeCoords and GlobalNodeIDs
    firstNode = hopr_elemInfo % hostData(5,1) + 1
    nLocalNodes = hopr_elemInfo % hostData(6,nLocalElems) - hopr_elemInfo % hostData(5,1)
    ! Allocate Space for hopr_nodeCoords and hopr_globalNodeIDs !
    CALL hopr_nodeCoords % Alloc(loBound=1, &
                                 upBound=nLocalNodes)
    CALL hopr_globalNodeIDs % Alloc(loBound=1, &
                                    upBound=nLocalNodes)
    gOffset = (/firstNode - 1/)
    CALL ReadArray_HDF5(fileId,'NodeCoords',hopr_nodeCoords,gOffset)
    CALL ReadArray_HDF5(fileId,'GlobalNodeIDs',hopr_globalNodeIDs,gOffset)
    CALL Close_HDF5(fileID)
    CALL myMesh % Init(nGeo,nLocalElems,nLocalNodes,nBCs)
    ! Copy data from local arrays into myMesh
    myMesh % hopr_elemInfo = hopr_elemInfo
    myMesh % hopr_nodeCoords = hopr_nodeCoords
    myMesh % hopr_globalNodeIDs = hopr_globalNodeIDs
    CALL myMesh % UpdateDevice()
    CALL hopr_elemInfo % Free()
    CALL hopr_nodeCoords % Free()
    CALL hopr_globalNodeIDs % Free()
  END SUBROUTINE Read_HOPr_Mesh1D_parallel
Call graph
read_hopr_mesh1d_parallel calls readattribute_hdf5, readarray_hdf5, open_hdf5, close_hdf5