ReadArray_HDF5_real_r3_serial – SELF
ReadArray_HDF5_real_r3_serial Subroutine
3-Clause BSD with attribution
13 statements
Source File
private subroutine ReadArray_HDF5_real_r3_serial(fileId, arrayName, hfArray)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
real(kind=prec), intent(inout), dimension(:,:,:) :: hfArray
Calls
Called by
Contents
Source Code
ReadArray_HDF5_real_r3_serial
Source Code
  subroutine ReadArray_HDF5_real_r3_serial(fileId,arrayName,hfArray)
    implicit none
    integer(HID_T),intent(in) :: fileId
    character(*),intent(in) :: arrayName
    real(prec),dimension(:,:,:),intent(inout) :: hfArray
    ! Local
    integer(HID_T) :: dsetId
    integer(HID_T) :: dims(1:3)
    integer :: error
    dims = shape(hfArray)
    call h5dopen_f(fileId,arrayName,dsetId,error)
    call h5dread_f(dsetId,h5kind_to_type(prec,H5_REAL_KIND),hfArray,dims,error)
    call h5dclose_f(dsetId,error)
  endsubroutine ReadArray_HDF5_real_r3_serial
Call graph
readarray_hdf5_real_r3_serial calls h5dopen_f, h5dread_f, h5dclose_f, h5kind_to_type
readarray_hdf5 calls readarray_hdf5_real_r3_serial
read_dgmodel2d_t calls readarray_hdf5
read_dgmodel3d_t calls readarray_hdf5
read_hopr_mesh2d_t calls readarray_hdf5
read_hopr_mesh3d_t calls readarray_hdf5
read_dgmodel1d_t calls readarray_hdf5