Read_DGModel1D_t – SELF
Read_DGModel1D_t Subroutine
3-Clause BSD with attribution
13 statements
Source File
public subroutine Read_DGModel1D_t(this, fileName)
Arguments
Type Intent Optional Attributes Name
class(DGModel1D_t), intent(inout) :: this
character, intent(in) :: fileName
Calls
Contents
Source Code
Read_DGModel1D_t
Source Code
  subroutine Read_DGModel1D_t(this,fileName)
    implicit none
    class(DGModel1D_t),intent(inout) :: this
    character(*),intent(in) :: fileName
    ! Local
    integer(HID_T) :: fileId
    integer(HID_T) :: solOffset(1:3)
    integer :: firstElem
    integer :: N
    call Open_HDF5(fileName,H5F_ACC_RDWR_F,fileId)
    call ReadArray_HDF5(fileId,'/controlgrid/solution/interior',this%solution%interior)
    call Close_HDF5(fileId)
    call this%solution%UpdateDevice()
  endsubroutine Read_DGModel1D_t
Call graph
read_dgmodel1d_t calls open_hdf5, close_hdf5, readarray_hdf5
open_hdf5 calls open_hdf5_serial, open_hdf5_parallel
close_hdf5 calls h5fclose_f, h5close_f
readarray_hdf5 calls readarray_hdf5_real_r2_serial, readarray_hdf5_real_r4_serial, readarray_hdf5_int32_r1_serial, readarray_hdf5_real_r1_parallel, readarray_hdf5_int32_r1_parallel, readarray_hdf5_real_r1_serial, readarray_hdf5_real_r5_serial, readarray_hdf5_real_r3_serial, readarray_hdf5_int32_r2_serial, readarray_hdf5_real_r2_parallel, readarray_hdf5_real_r3_parallel, readarray_hdf5_real_r4_parallel, readarray_hdf5_int32_r2_parallel
open_hdf5_serial calls h5open_f, h5fopen_f, h5fcreate_f
readarray_hdf5_real_r2_serial calls h5dread_f, h5kind_to_type, h5dopen_f, h5dclose_f
readarray_hdf5_real_r4_serial calls h5dread_f, h5kind_to_type, h5dopen_f, h5dclose_f
readarray_hdf5_int32_r1_serial calls h5dread_f, h5kind_to_type, h5dopen_f, h5dclose_f
readarray_hdf5_real_r1_parallel calls h5dread_f, h5screate_simple_f, h5pcreate_f, h5dget_space_f, h5sselect_hyperslab_f, h5dget_type_f, h5pclose_f, h5dopen_f, h5dclose_f, h5sclose_f, h5pset_dxpl_mpio_f, h5tclose_f
readarray_hdf5_int32_r1_parallel calls h5dread_f, h5screate_simple_f, h5pcreate_f, h5dget_space_f, h5sselect_hyperslab_f, h5dget_type_f, h5pclose_f, h5dopen_f, h5dclose_f, h5sclose_f, h5pset_dxpl_mpio_f, h5tclose_f
open_hdf5_parallel calls h5open_f, h5fopen_f, h5pcreate_f, h5pclose_f, h5fcreate_f, h5pset_fapl_mpio_f
readarray_hdf5_real_r1_serial calls h5dread_f, h5kind_to_type, h5dopen_f, h5dclose_f
readarray_hdf5_real_r5_serial calls h5dread_f, h5kind_to_type, h5dopen_f, h5dclose_f
readarray_hdf5_real_r3_serial calls h5dread_f, h5kind_to_type, h5dopen_f, h5dclose_f
readarray_hdf5_int32_r2_serial calls h5dread_f, h5kind_to_type, h5dopen_f, h5dclose_f
readarray_hdf5_real_r2_parallel calls h5dread_f, h5screate_simple_f, h5pcreate_f, h5dget_space_f, h5sselect_hyperslab_f, h5dget_type_f, h5pclose_f, h5dopen_f, h5dclose_f, h5sclose_f, h5pset_dxpl_mpio_f, h5tclose_f
readarray_hdf5_real_r3_parallel calls h5dread_f, h5screate_simple_f, h5pcreate_f, h5dget_space_f, h5sselect_hyperslab_f, h5dget_type_f, h5pclose_f, h5dopen_f, h5dclose_f, h5sclose_f, h5pset_dxpl_mpio_f, h5tclose_f
readarray_hdf5_real_r4_parallel calls h5dread_f, h5screate_simple_f, h5pcreate_f, h5dget_space_f, h5sselect_hyperslab_f, h5dget_type_f, h5pclose_f, h5dopen_f, h5dclose_f, h5sclose_f, h5pset_dxpl_mpio_f, h5tclose_f
readarray_hdf5_int32_r2_parallel calls h5dread_f, h5screate_simple_f, h5pcreate_f, h5dget_space_f, h5sselect_hyperslab_f, h5dget_type_f, h5pclose_f, h5dopen_f, h5dclose_f, h5sclose_f, h5pset_dxpl_mpio_f, h5tclose_f