RecalculateFlip_Mesh3D – SELF
RecalculateFlip_Mesh3D Subroutine
Anti-Capitalist Software License
116 statements
Source File
public subroutine RecalculateFlip_Mesh3D(myMesh, decomp)
Arguments
Type Intent Optional Attributes Name
class(Mesh3D), intent(inout) :: myMesh
type(MPILayer), intent(inout), optional :: decomp
Calls
Contents
Source Code
RecalculateFlip_Mesh3D
Source Code
  SUBROUTINE RecalculateFlip_Mesh3D(myMesh,decomp)
    IMPLICIT NONE
    CLASS(Mesh3D),INTENT(inout) :: myMesh
    TYPE(MPILayer),INTENT(inout),OPTIONAL :: decomp
    ! Local
    INTEGER :: e1
    INTEGER :: s1
    INTEGER :: e2
    INTEGER :: e2Global
    INTEGER :: s2
    INTEGER :: flip
    INTEGER :: bcid
    INTEGER :: lnid1(1:4)
    INTEGER :: lnid2(1:4)
    INTEGER :: nid1(1:4,1:6,1:myMesh % nElem)
    INTEGER :: nid2(1:4,1:6,1:myMesh % nElem)
    INTEGER :: nloc1(1:4)
    INTEGER :: nloc2(1:4)
    INTEGER :: n1
    INTEGER :: n1Global
    INTEGER :: n2
    INTEGER :: n2Global
    INTEGER :: c1
    INTEGER :: c2
    INTEGER :: i
    INTEGER :: l
    INTEGER :: nShifts
    INTEGER :: neighborRank
    INTEGER :: rankId
    INTEGER :: offset
    INTEGER :: msgCount
    INTEGER :: globalSideId
    INTEGER, ALLOCATABLE :: requests(:)
    INTEGER, ALLOCATABLE :: stats(:,:)
    INTEGER :: iError
    LOGICAL :: theyMatch
    ALLOCATE(requests(1:myMesh % nSides*2))
    ALLOCATE(stats(MPI_STATUS_SIZE,1:myMesh % nSides*2))
    IF (PRESENT(decomp)) THEN
      rankId = decomp % rankId
      offset = decomp % offsetElem % hostData(rankId)
    ELSE
      rankId = 0
      offset = 0
    ENDIF
    msgCount = 0
    DO e1 = 1,myMesh % nElem
      DO s1 = 1,6
        e2Global = myMesh % self_sideInfo % hostData(3,s1,e1)
        e2 = e2Global - offset
        s2 = myMesh % self_sideInfo % hostData(4,s1,e1)/10
        flip = myMesh % self_sideInfo % hostData(4,s1,e1) - s2*10
        bcid = myMesh % self_sideInfo % hostData(5,s1,e1)
        IF (bcid == 0) THEN
          IF (PRESENT(decomp)) THEN
            neighborRank = decomp % elemToRank % hostData(e2Global)
          ELSE
            neighborRank = 0
          ENDIF
          IF (neighborRank == rankId) THEN
            ! With 8 nodes per element, and the nodes provided in order, we can also shift the node indices
            n1Global = myMesh % hopr_elemInfo % hostData(5,e1) ! Starting node index for element 1
            n1 = n1Global - 8*offset
            n2Global = myMesh % hopr_elemInfo % hostData(5,e2) ! Starting node index for element 2
            n2 = n2Global - 8*offset
            lnid1 = myMesh % self_sideMap % hostData(1:4,s1) ! local CGNS corner node ids for element 1 side
            lnid2 = myMesh % self_sideMap % hostData(1:4,s2) ! local CGNS corner node ids for element 2 side
            DO l = 1, 4
              c1 = myMesh % hopr_CGNSCornerMap % hostData(lnid1(l)) ! Get the local HOPR node id for element 1
              c2 = myMesh % hopr_CGNSCornerMap % hostData(lnid2(l)) ! Get the local HOPR node id for element 2
              nid1(l,s1,e1) = myMesh % hopr_globalNodeIDs % hostData(n1+c1) ! Global node IDs for element 1 side
              nid2(l,s1,e1) = myMesh % hopr_globalNodeIDs % hostData(n2+c2) ! Global node IDs for element 2 side
            ENDDO
          ELSE ! In this case, we need to exchange
            globalSideId = ABS(myMesh % self_sideInfo % hostdata(2,s1,e1))
            n1Global = myMesh % hopr_elemInfo % hostData(5,e1) ! Starting node index for element 1
            n1 = n1Global - 8*offset
            lnid1 = myMesh % self_sideMap % hostData(1:4,s1) ! local CGNS corner node ids for element 1 side
            DO l = 1, 4
              c1 = myMesh % hopr_CGNSCornerMap % hostData(lnid1(l)) ! Get the local HOPR node id for element 1
              nid1(l,s1,e1) = myMesh % hopr_globalNodeIDs % hostData(n1+c1) ! Global node IDs for element 1 side
              ! Receive nid2(l) on this rank from  nid1(l) on the other rank
              msgCount = msgCount + 1
              CALL MPI_IRECV(nid2(l,s1,e1), &
                             1, &
                             MPI_INTEGER, &
                             neighborRank,globalSideId, &
                             decomp % mpiComm, &
                             requests(msgCount),iError)
              ! Send nid1(l) from this rank to nid2(l) on the other rank
              msgCount = msgCount + 1
              CALL MPI_ISEND(nid1(l,s1,e1), &
                             1, &
                             MPI_INTEGER, &
                             neighborRank,globalSideId, &
                             decomp % mpiComm, &
                             requests(msgCount),iError)
            ENDDO
          ENDIF ! MPI or not
        ENDIF ! If not physical boundary
      ENDDO
    ENDDO
    IF (PRESENT(decomp) .AND. msgCount > 0) THEN
      CALL MPI_WaitAll(msgCount, &
                       requests(1:msgCount), &
                       stats(1:MPI_STATUS_SIZE,1:msgCount), &
                       iError)
    ENDIF
    DO e1 = 1,myMesh % nElem
      DO s1 = 1,6
        s2 = myMesh % self_sideInfo % hostData(4,s1,e1)/10
        bcid = myMesh % self_sideInfo % hostData(5,s1,e1)
        nloc1(1:4) = nid1(1:4,s1,e1)
        nloc2(1:4) = nid2(1:4,s1,e1)
        IF (bcid == 0) THEN
          nShifts = 0
          theyMatch = .FALSE.
          DO i = 1, 4
            theyMatch = CompareArray( nloc1, nloc2, 4 )
            IF( theyMatch )THEN
              EXIT
            ELSE
              nShifts = nShifts + 1
              CALL ForwardShift( nloc1, 4 )
            ENDIF
          ENDDO
          myMesh % self_sideInfo % hostData(4,s1,e1) = 10*s2+nShifts
        ENDIF
      ENDDO
    ENDDO
    DEALLOCATE(requests)
    DEALLOCATE(stats)
  END SUBROUTINE RecalculateFlip_Mesh3D
Call graph
recalculateflip_mesh3d calls mpi_irecv, mpi_waitall, forwardshift, comparearray, mpi_isend