SetElemToRank_DomainDecomposition – SELF
SetElemToRank_DomainDecomposition Subroutine
3-Clause BSD with attribution
14 statements
Source File
public subroutine SetElemToRank_DomainDecomposition(this, nElem)
Arguments
Type Intent Optional Attributes Name
class(DomainDecomposition), intent(inout) :: this
integer, intent(in) :: nElem
Calls
Contents
Source Code
SetElemToRank_DomainDecomposition
Source Code
  subroutine SetElemToRank_DomainDecomposition(this,nElem)
    implicit none
    class(DomainDecomposition),intent(inout) :: this
    integer,intent(in) :: nElem
    ! Local
    integer :: iel
    this%nElem = nElem
    allocate(this%elemToRank(1:nelem))
    call gpuCheck(hipMalloc(this%elemToRank_gpu,sizeof(this%elemToRank)))
    call DomainDecomp(nElem, &
                      this%nRanks, &
                      this%offSetElem)
    do iel = 1,nElem
      call ElemToRank(this%nRanks, &
                      this%offSetElem, &
                      iel, &
                      this%elemToRank(iel))
    enddo
    call gpuCheck(hipMemcpy(this%elemToRank_gpu,c_loc(this%elemToRank),sizeof(this%elemToRank),hipMemcpyHostToDevice))
  endsubroutine SetElemToRank_DomainDecomposition
Call graph
setelemtorank_domaindecomposition calls gpucheck, hipmemcpy, domaindecomp, hipmalloc, elemtorank