WriteArray_HDF5_int32_r6_parallel – SELF
WriteArray_HDF5_int32_r6_parallel Subroutine
Anti-Capitalist Software License
36 statements
Source File
private subroutine WriteArray_HDF5_int32_r6_parallel(fileId, arrayName, hfArray, offset, globalDims)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfint32_r6), intent(in) :: hfArray
integer(kind=HID_T), intent(in) :: offset(1:6)
integer(kind=HID_T), intent(in) :: globalDims(1:6)
Calls
Called by
Contents
Source Code
WriteArray_HDF5_int32_r6_parallel
Source Code
  SUBROUTINE WriteArray_HDF5_int32_r6_parallel(fileId,arrayName,hfArray,offset,globalDims)
    IMPLICIT NONE
    INTEGER(HID_T),INTENT(in) :: fileId
    CHARACTER(*),INTENT(in) :: arrayName
    INTEGER(HID_T),INTENT(in) :: offset(1:6)
    TYPE(hfint32_r6),INTENT(in) :: hfArray
    INTEGER(HID_T),INTENT(in) :: globalDims(1:6)
    ! Local
    INTEGER(HID_T) :: plistId
    INTEGER(HID_T) :: dsetId
    INTEGER(HID_T) :: filespace
    INTEGER(HID_T) :: memspace
    INTEGER(HSIZE_T) :: dims(1:6)
    INTEGER(HSIZE_T) :: strides(1:6)
    INTEGER(HSIZE_T) :: counts(1:6)
    INTEGER :: error
    INTEGER :: aRank
    aRank = RANK(hfArray % hostData)
    dims = SHAPE(hfArray % hostData)
    CALL h5screate_simple_f(aRank,globalDims,filespace,error)
    CALL h5screate_simple_f(aRank,dims,memspace,error)
    ! Set the data creation mode to CHUNK
    CALL h5pcreate_f(H5P_DATASET_CREATE_F,plistId,error)
    CALL h5pset_chunk_f(plistId,aRank,dims,error)
    CALL h5dcreate_f(fileId,TRIM(arrayName),H5T_STD_I32LE,filespace, &
                     dsetId,error,plistId)
    strides = (/1,1,1,1,1,1/)
    counts = (/1,1,1,1,1,1/)
    CALL h5sselect_hyperslab_f(filespace,&
                               H5S_SELECT_SET_F,&
                               offset,&
                               counts,&
                               error,&
                               strides,&
                               dims)
    CALL h5dwrite_f(dsetId,H5T_STD_I32LE, &
                    hfArray % hostData,dims,error,memspace,filespace)
    IF( error /= 0 )THEN
      PRINT*, 'Failure to write dataset'
      STOP
    ENDIF
    CALL h5pclose_f(plistId,error)
    CALL h5sclose_f(filespace,error)
    CALL h5dclose_f(dSetId,error)
    CALL h5sclose_f(memspace,error)
  END SUBROUTINE WriteArray_HDF5_int32_r6_parallel
Call graph
writearray_hdf5_int32_r6_parallel calls h5pcreate_f, h5screate_simple_f, h5dcreate_f, h5sclose_f, h5sselect_hyperslab_f, h5dwrite_f, h5dclose_f, h5pset_chunk_f, h5pclose_f
writearray_hdf5 calls writearray_hdf5_int32_r6_parallel