WriteHDF5_Vector3D_t – SELF
WriteHDF5_Vector3D_t Subroutine
3-Clause BSD with attribution
19 statements
Source File
public subroutine WriteHDF5_Vector3D_t(this, fileId, group)
Arguments
Type Intent Optional Attributes Name
class(Vector3D_t), intent(in) :: this
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: group
Calls
Contents
Source Code
WriteHDF5_Vector3D_t
Source Code
  subroutine WriteHDF5_Vector3D_t(this,fileId,group)
    implicit none
    class(Vector3D_t),intent(in) :: this
    integer(HID_T),intent(in) :: fileId
    character(*),intent(in) :: group
    ! Local
    integer :: ivar,idir
    character(4) :: dimvar
    call CreateGroup_HDF5(fileId,trim(group))
    do ivar = 1,this%nVar
      call this%meta(ivar)%WriteHDF5(group,ivar,fileId)
    enddo
    do idir = 1,3
      write(dimvar,'(I1)') idir
      dimvar = "dim"//trim(dimvar)
      do ivar = 1,this%nVar
        call WriteArray_HDF5(fileId, &
                             trim(group)//"/"//trim(this%meta(ivar)%name)//"_"//dimvar, &
                             this%interior(:,:,:,:,ivar,idir))
      enddo
    enddo
  endsubroutine WriteHDF5_Vector3D_t
Call graph
writehdf5_vector3d_t calls creategroup_hdf5, writearray_hdf5
creategroup_hdf5 calls h5lexists_f, h5gcreate_f, h5gclose_f
writearray_hdf5 calls writearray_hdf5_real_r1_serial, writearray_hdf5_real_r3_serial, writearray_hdf5_real_r5_serial, writearray_hdf5_real_r2_serial, writearray_hdf5_int32_r2_serial, writearray_hdf5_int32_r3_serial, writearray_hdf5_real_r3_parallel, writearray_hdf5_real_r4_parallel, writearray_hdf5_real_r4_serial, writearray_hdf5_int32_r1_serial, writearray_hdf5_int32_r4_serial
writearray_hdf5_real_r1_serial calls h5dclose_f, h5dwrite_f, h5dcreate_f, h5screate_simple_f, h5sclose_f
writearray_hdf5_real_r3_serial calls h5dclose_f, h5dwrite_f, h5dcreate_f, h5screate_simple_f, h5sclose_f
writearray_hdf5_real_r5_serial calls h5dclose_f, h5dwrite_f, h5dcreate_f, h5screate_simple_f, h5sclose_f
writearray_hdf5_real_r2_serial calls h5dclose_f, h5dwrite_f, h5dcreate_f, h5screate_simple_f, h5sclose_f
writearray_hdf5_int32_r2_serial calls h5dclose_f, h5dwrite_f, h5dcreate_f, h5screate_simple_f, h5sclose_f
writearray_hdf5_int32_r3_serial calls h5dclose_f, h5dwrite_f, h5dcreate_f, h5screate_simple_f, h5sclose_f
writearray_hdf5_real_r3_parallel calls h5dclose_f, h5dwrite_f, h5dcreate_f, h5sselect_hyperslab_f, h5screate_simple_f, h5sclose_f, h5pset_dxpl_mpio_f, h5pcreate_f, h5pclose_f
writearray_hdf5_real_r4_parallel calls h5dclose_f, h5dwrite_f, h5dcreate_f, h5sselect_hyperslab_f, h5screate_simple_f, h5sclose_f, h5pset_dxpl_mpio_f, h5pcreate_f, h5pclose_f
writearray_hdf5_real_r4_serial calls h5dclose_f, h5dwrite_f, h5dcreate_f, h5screate_simple_f, h5sclose_f
writearray_hdf5_int32_r1_serial calls h5dclose_f, h5dwrite_f, h5dcreate_f, h5screate_simple_f, h5sclose_f
writearray_hdf5_int32_r4_serial calls h5dclose_f, h5dwrite_f, h5dcreate_f, h5screate_simple_f, h5sclose_f