WriteArray_HDF5_real_r4_parallel – SELF
WriteArray_HDF5_real_r4_parallel Subroutine
3-Clause BSD with attribution
30 statements
Source File
private subroutine WriteArray_HDF5_real_r4_parallel(fileId, arrayName, hfArray, offset, globalDims)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
real(kind=prec), intent(in), dimension(:,:,:,:) :: hfArray
integer(kind=HID_T), intent(in) :: offset(1:4)
integer(kind=HID_T), intent(in) :: globalDims(1:4)
Calls
Called by
Contents
Source Code
WriteArray_HDF5_real_r4_parallel
Source Code
  subroutine WriteArray_HDF5_real_r4_parallel(fileId,arrayName,hfArray,offset,globalDims)
    implicit none
    integer(HID_T),intent(in) :: fileId
    character(*),intent(in) :: arrayName
    integer(HID_T),intent(in) :: offset(1:4)
    real(prec),dimension(:,:,:,:),intent(in) :: hfArray
    integer(HID_T),intent(in) :: globalDims(1:4)
    ! Local
    integer(HID_T) :: plistId
    integer(HID_T) :: dsetId
    integer(HID_T) :: filespace
    integer(HID_T) :: memspace
    integer(HSIZE_T) :: dims(1:4)
    integer :: error
    dims = shape(hfArray)
    call h5screate_simple_f(4,globalDims,filespace,error)
    call h5screate_simple_f(4,dims,memspace,error)
    call h5dcreate_f(fileId,trim(arrayName),HDF5_IO_PREC,filespace,dsetId,error)
    call h5sselect_hyperslab_f(filespace, &
                               H5S_SELECT_SET_F, &
                               offset, &
                               dims, &
                               error)
    call h5pcreate_f(H5P_DATASET_XFER_F,plistId,error)
    call h5pset_dxpl_mpio_f(plistId,H5FD_MPIO_COLLECTIVE_F,error)
    call h5dwrite_f(dsetId,HDF5_IO_PREC,hfArray,dims,error, &
                    mem_space_id=memspace,file_space_id=filespace,xfer_prp=plistId)
    if(error /= 0) then
      print*,'Failure to write dataset'
      stop 1
    endif
    call h5pclose_f(plistId,error)
    call h5sclose_f(filespace,error)
    call h5dclose_f(dSetId,error)
    call h5sclose_f(memspace,error)
  endsubroutine WriteArray_HDF5_real_r4_parallel
Call graph
writearray_hdf5_real_r4_parallel calls h5screate_simple_f, h5dwrite_f, h5pcreate_f, h5sselect_hyperslab_f, h5pclose_f, h5sclose_f, h5pset_dxpl_mpio_f, h5dcreate_f, h5dclose_f
writearray_hdf5 calls writearray_hdf5_real_r4_parallel
writehdf5_lagrange_t calls writearray_hdf5
writehdf5_vector2d_t calls writearray_hdf5
writehdf5_mpi_scalar2d_t calls writearray_hdf5
writehdf5_mpi_vector3d_t calls writearray_hdf5
write_geometry1d calls writearray_hdf5
writehdf5_scalar1d_t calls writearray_hdf5
write_mesh3d_t calls writearray_hdf5
writehdf5_scalar3d_t calls writearray_hdf5
writehdf5_mpi_vector2d_t calls writearray_hdf5
writehdf5_scalar2d_t calls writearray_hdf5
writehdf5_vector3d_t calls writearray_hdf5
write_mesh2d_t calls writearray_hdf5
write_mesh1d calls writearray_hdf5
writehdf5_mpi_scalar3d_t calls writearray_hdf5