WriteHDF5_MPI_Vector3D_t – SELF
WriteHDF5_MPI_Vector3D_t Subroutine
3-Clause BSD with attribution
22 statements
Source File
public subroutine WriteHDF5_MPI_Vector3D_t(this, fileId, group, elemoffset, nglobalelem)
Arguments
Type Intent Optional Attributes Name
class(Vector3D_t), intent(in) :: this
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: group
integer, intent(in) :: elemoffset
integer, intent(in) :: nglobalelem
Calls
Contents
Source Code
WriteHDF5_MPI_Vector3D_t
Source Code
  subroutine WriteHDF5_MPI_Vector3D_t(this,fileId,group,elemoffset,nglobalelem)
    implicit none
    class(Vector3D_t),intent(in) :: this
    character(*),intent(in) :: group
    integer(HID_T),intent(in) :: fileId
    integer,intent(in) :: elemoffset
    integer,intent(in) :: nglobalelem
    ! Local
    integer(HID_T) :: offset(1:4)
    integer(HID_T) :: globalDims(1:4)
    integer :: ivar,idir
    character(4) :: dimvar
    offset(1:4) = (/0,0,0,elemoffset/)
    globalDims(1:4) = (/this%interp%N+1, &
                        this%interp%N+1, &
                        this%interp%N+1, &
                        nglobalelem/)
    call CreateGroup_HDF5(fileId,trim(group))
    do idir = 1,3
      write(dimvar,'(I1)') idir
      dimvar = "dim"//trim(dimvar)
      do ivar = 1,this%nVar
        call WriteArray_HDF5(fileId, &
                             trim(group)//"/"//trim(this%meta(ivar)%name)//"_"//dimvar, &
                             this%interior(:,:,:,:,ivar,idir),offset,globalDims)
      enddo
    enddo
  endsubroutine WriteHDF5_MPI_Vector3D_t
Call graph
writehdf5_mpi_vector3d_t calls creategroup_hdf5, writearray_hdf5
creategroup_hdf5 calls h5gcreate_f, h5lexists_f, h5gclose_f
writearray_hdf5 calls writearray_hdf5_real_r5_serial, writearray_hdf5_real_r2_serial, writearray_hdf5_real_r3_serial, writearray_hdf5_int32_r2_serial, writearray_hdf5_int32_r4_serial, writearray_hdf5_real_r4_parallel, writearray_hdf5_real_r1_serial, writearray_hdf5_real_r4_serial, writearray_hdf5_int32_r1_serial, writearray_hdf5_int32_r3_serial, writearray_hdf5_real_r3_parallel
writearray_hdf5_real_r5_serial calls h5dclose_f, h5dcreate_f, h5screate_simple_f, h5sclose_f, h5dwrite_f
writearray_hdf5_real_r2_serial calls h5dclose_f, h5dcreate_f, h5screate_simple_f, h5sclose_f, h5dwrite_f
writearray_hdf5_real_r3_serial calls h5dclose_f, h5dcreate_f, h5screate_simple_f, h5sclose_f, h5dwrite_f
writearray_hdf5_int32_r2_serial calls h5dclose_f, h5dcreate_f, h5screate_simple_f, h5sclose_f, h5dwrite_f
writearray_hdf5_int32_r4_serial calls h5dclose_f, h5dcreate_f, h5screate_simple_f, h5sclose_f, h5dwrite_f
writearray_hdf5_real_r4_parallel calls h5dclose_f, h5dcreate_f, h5pcreate_f, h5pclose_f, h5screate_simple_f, h5sclose_f, h5dwrite_f, h5sselect_hyperslab_f, h5pset_dxpl_mpio_f
writearray_hdf5_real_r1_serial calls h5dclose_f, h5dcreate_f, h5screate_simple_f, h5sclose_f, h5dwrite_f
writearray_hdf5_real_r4_serial calls h5dclose_f, h5dcreate_f, h5screate_simple_f, h5sclose_f, h5dwrite_f
writearray_hdf5_int32_r1_serial calls h5dclose_f, h5dcreate_f, h5screate_simple_f, h5sclose_f, h5dwrite_f
writearray_hdf5_int32_r3_serial calls h5dclose_f, h5dcreate_f, h5screate_simple_f, h5sclose_f, h5dwrite_f
writearray_hdf5_real_r3_parallel calls h5dclose_f, h5dcreate_f, h5pcreate_f, h5pclose_f, h5screate_simple_f, h5sclose_f, h5dwrite_f, h5sselect_hyperslab_f, h5pset_dxpl_mpio_f