Write_Mesh2D_t – SELF
Write_Mesh2D_t Subroutine
3-Clause BSD with attribution
16 statements
Source File
public subroutine Write_Mesh2D_t(this, meshFile)
Arguments
Type Intent Optional Attributes Name
class(Mesh2D_t), intent(inout) :: this
character, intent(in) :: meshFile
Calls
Contents
Source Code
Write_Mesh2D_t
Source Code
  subroutine Write_Mesh2D_t(this,meshFile)
    ! Writes mesh output in HOPR format (serial only)
    implicit none
    class(Mesh2D_t),intent(inout) :: this
    character(*),intent(in) :: meshFile
    ! Local
    integer(HID_T) :: fileId
    call Open_HDF5(meshFile,H5F_ACC_RDWR_F,fileId)
    call WriteAttribute_HDF5(fileId,'nElems',this%nElem)
    call WriteAttribute_HDF5(fileId,'Ngeo',this%nGeo)
    call WriteAttribute_HDF5(fileId,'nBCs',this%nBCs)
    call WriteArray_HDF5(fileId,'BCType',this%bcType)
    ! Write local subarray of ElemInfo
    call WriteArray_HDF5(fileId,'ElemInfo',this%elemInfo)
    ! Write local subarray of NodeCoords and GlobalNodeIDs
    call WriteArray_HDF5(fileId,'NodeCoords',this%nodeCoords)
    call WriteArray_HDF5(fileId,'GlobalNodeIDs',this%globalNodeIDs)
    ! Write local subarray of SideInfo
    call WriteArray_HDF5(fileId,'SideInfo',this%sideInfo)
    call Close_HDF5(fileID)
  endsubroutine Write_Mesh2D_t
Call graph
write_mesh2d_t calls open_hdf5, writeattribute_hdf5, close_hdf5, writearray_hdf5
open_hdf5 calls open_hdf5_serial, open_hdf5_parallel
writeattribute_hdf5 calls writeattribute_hdf5_int32
close_hdf5 calls h5fclose_f, h5close_f
writearray_hdf5 calls writearray_hdf5_real_r4_serial, writearray_hdf5_real_r2_serial, writearray_hdf5_int32_r1_serial, writearray_hdf5_int32_r3_serial, writearray_hdf5_real_r3_parallel, writearray_hdf5_real_r1_serial, writearray_hdf5_real_r3_serial, writearray_hdf5_real_r5_serial, writearray_hdf5_int32_r2_serial, writearray_hdf5_int32_r4_serial, writearray_hdf5_real_r4_parallel
open_hdf5_serial calls h5open_f, h5fopen_f, h5fcreate_f
writearray_hdf5_real_r4_serial calls h5screate_simple_f, h5dwrite_f, h5sclose_f, h5dclose_f, h5dcreate_f
writearray_hdf5_real_r2_serial calls h5screate_simple_f, h5dwrite_f, h5sclose_f, h5dclose_f, h5dcreate_f
writearray_hdf5_int32_r1_serial calls h5screate_simple_f, h5dwrite_f, h5sclose_f, h5dclose_f, h5dcreate_f
writearray_hdf5_int32_r3_serial calls h5screate_simple_f, h5dwrite_f, h5sclose_f, h5dclose_f, h5dcreate_f
writearray_hdf5_real_r3_parallel calls h5screate_simple_f, h5dwrite_f, h5sclose_f, h5pcreate_f, h5sselect_hyperslab_f, h5pclose_f, h5dclose_f, h5dcreate_f, h5pset_dxpl_mpio_f
open_hdf5_parallel calls h5open_f, h5fopen_f, h5pcreate_f, h5pclose_f, h5fcreate_f, h5pset_fapl_mpio_f
writeattribute_hdf5_int32 calls h5sclose_f, h5acreate_f, h5screate_f, h5awrite_f, h5aclose_f
writearray_hdf5_real_r1_serial calls h5screate_simple_f, h5dwrite_f, h5sclose_f, h5dclose_f, h5dcreate_f
writearray_hdf5_real_r3_serial calls h5screate_simple_f, h5dwrite_f, h5sclose_f, h5dclose_f, h5dcreate_f
writearray_hdf5_real_r5_serial calls h5screate_simple_f, h5dwrite_f, h5sclose_f, h5dclose_f, h5dcreate_f
writearray_hdf5_int32_r2_serial calls h5screate_simple_f, h5dwrite_f, h5sclose_f, h5dclose_f, h5dcreate_f
writearray_hdf5_int32_r4_serial calls h5screate_simple_f, h5dwrite_f, h5sclose_f, h5dclose_f, h5dcreate_f
writearray_hdf5_real_r4_parallel calls h5screate_simple_f, h5dwrite_f, h5sclose_f, h5pcreate_f, h5sselect_hyperslab_f, h5pclose_f, h5dclose_f, h5dcreate_f, h5pset_dxpl_mpio_f