WriteArray_HDF5_real_r1_serial – SELF
WriteArray_HDF5_real_r1_serial Subroutine
3-Clause BSD with attribution
16 statements
Source File
private subroutine WriteArray_HDF5_real_r1_serial(fileId, arrayName, hfArray)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
real(kind=prec), intent(in), dimension(:) :: hfArray
Calls
Called by
Contents
Source Code
WriteArray_HDF5_real_r1_serial
Source Code
  subroutine WriteArray_HDF5_real_r1_serial(fileId,arrayName,hfArray)
    implicit none
    integer(HID_T),intent(in) :: fileId
    character(*),intent(in) :: arrayName
    real(prec),dimension(:),intent(in) :: hfArray
    ! Local
    integer(HID_T) :: dsetId
    integer(HID_T) :: memspace
    integer(HSIZE_T) :: dims(1)
    integer :: error
    dims = shape(hfArray)
    call h5screate_simple_f(1,dims,memspace,error)
    call h5dcreate_f(fileId,trim(arrayName),HDF5_IO_PREC,memspace, &
                     dsetId,error)
    call h5dwrite_f(dsetId,HDF5_IO_PREC, &
                    hfArray,dims,error)
    call h5dclose_f(dSetId,error)
    call h5sclose_f(memspace,error)
  endsubroutine WriteArray_HDF5_real_r1_serial
Call graph
writearray_hdf5_real_r1_serial calls h5screate_simple_f, h5dwrite_f, h5sclose_f, h5dclose_f, h5dcreate_f
writearray_hdf5 calls writearray_hdf5_real_r1_serial
writehdf5_lagrange_t calls writearray_hdf5
writehdf5_vector2d_t calls writearray_hdf5
writehdf5_mpi_scalar2d_t calls writearray_hdf5
writehdf5_mpi_vector3d_t calls writearray_hdf5
write_geometry1d calls writearray_hdf5
writehdf5_scalar1d_t calls writearray_hdf5
write_mesh3d_t calls writearray_hdf5
writehdf5_scalar3d_t calls writearray_hdf5
writehdf5_mpi_vector2d_t calls writearray_hdf5
writehdf5_scalar2d_t calls writearray_hdf5
writehdf5_vector3d_t calls writearray_hdf5
write_mesh2d_t calls writearray_hdf5
write_mesh1d calls writearray_hdf5
writehdf5_mpi_scalar3d_t calls writearray_hdf5