WriteHDF5_Lagrange_t – SELF
WriteHDF5_Lagrange_t Subroutine
3-Clause BSD with attribution
12 statements
Source File
public subroutine WriteHDF5_Lagrange_t(this, fileId)
Arguments
Type Intent Optional Attributes Name
class(Lagrange_t), intent(in) :: this
integer(kind=HID_T), intent(in) :: fileId
Calls
Contents
Source Code
WriteHDF5_Lagrange_t
Source Code
  subroutine WriteHDF5_Lagrange_t(this,fileId)
    implicit none
    class(Lagrange_t),intent(in) :: this
    integer(HID_T),intent(in) :: fileId
    call CreateGroup_HDF5(fileId,'/interp')
    call WriteArray_HDF5(fileId,'/interp/controlpoints', &
                         this%controlPoints)
    call WriteArray_HDF5(fileId,'/interp/qweights', &
                         this%qWeights)
    call WriteArray_HDF5(fileId,'/interp/dgmatrix', &
                         this%dgMatrix)
    call WriteArray_HDF5(fileId,'/interp/dmatrix', &
                         this%dMatrix)
    call WriteArray_HDF5(fileId,'/interp/bmatrix', &
                         this%bMatrix)
    call WriteArray_HDF5(fileId,'/interp/imatrix', &
                         this%iMatrix)
  endsubroutine WriteHDF5_Lagrange_t
Call graph
writehdf5_lagrange_t calls creategroup_hdf5, writearray_hdf5
creategroup_hdf5 calls h5lexists_f, h5gclose_f, h5gcreate_f
writearray_hdf5 calls writearray_hdf5_real_r4_serial, writearray_hdf5_real_r2_serial, writearray_hdf5_int32_r1_serial, writearray_hdf5_int32_r3_serial, writearray_hdf5_real_r3_parallel, writearray_hdf5_real_r1_serial, writearray_hdf5_real_r3_serial, writearray_hdf5_real_r5_serial, writearray_hdf5_int32_r2_serial, writearray_hdf5_int32_r4_serial, writearray_hdf5_real_r4_parallel
writearray_hdf5_real_r4_serial calls h5screate_simple_f, h5dwrite_f, h5sclose_f, h5dclose_f, h5dcreate_f
writearray_hdf5_real_r2_serial calls h5screate_simple_f, h5dwrite_f, h5sclose_f, h5dclose_f, h5dcreate_f
writearray_hdf5_int32_r1_serial calls h5screate_simple_f, h5dwrite_f, h5sclose_f, h5dclose_f, h5dcreate_f
writearray_hdf5_int32_r3_serial calls h5screate_simple_f, h5dwrite_f, h5sclose_f, h5dclose_f, h5dcreate_f
writearray_hdf5_real_r3_parallel calls h5screate_simple_f, h5dwrite_f, h5sclose_f, h5pcreate_f, h5sselect_hyperslab_f, h5pclose_f, h5dclose_f, h5dcreate_f, h5pset_dxpl_mpio_f
writearray_hdf5_real_r1_serial calls h5screate_simple_f, h5dwrite_f, h5sclose_f, h5dclose_f, h5dcreate_f
writearray_hdf5_real_r3_serial calls h5screate_simple_f, h5dwrite_f, h5sclose_f, h5dclose_f, h5dcreate_f
writearray_hdf5_real_r5_serial calls h5screate_simple_f, h5dwrite_f, h5sclose_f, h5dclose_f, h5dcreate_f
writearray_hdf5_int32_r2_serial calls h5screate_simple_f, h5dwrite_f, h5sclose_f, h5dclose_f, h5dcreate_f
writearray_hdf5_int32_r4_serial calls h5screate_simple_f, h5dwrite_f, h5sclose_f, h5dclose_f, h5dcreate_f
writearray_hdf5_real_r4_parallel calls h5screate_simple_f, h5dwrite_f, h5sclose_f, h5pcreate_f, h5sselect_hyperslab_f, h5pclose_f, h5dclose_f, h5dcreate_f, h5pset_dxpl_mpio_f