Write_Geometry1D – SELF
Write_Geometry1D Subroutine
3-Clause BSD with attribution
26 statements
Source File
public subroutine Write_Geometry1D(myGeom, fileName)
Arguments
Type Intent Optional Attributes Name
class(Geometry1D), intent(in) :: myGeom
character, intent(in), optional :: fileName
Calls
Contents
Source Code
Write_Geometry1D
Source Code
  subroutine Write_Geometry1D(myGeom,fileName)
    implicit none
    class(Geometry1D),intent(in) :: myGeom
    character(*),optional,intent(in) :: fileName
    ! Local
    integer(HID_T) :: fileId
    ! Local
    character(LEN=self_FileNameLength) :: pickupFile
    if(present(filename)) then
      pickupFile = filename
    else
      pickupFile = 'mesh.h5'
    endif
    call Open_HDF5(pickupFile,H5F_ACC_TRUNC_F,fileId)
    call CreateGroup_HDF5(fileId,'/quadrature')
    call WriteArray_HDF5(fileId,'/quadrature/xi', &
                         myGeom%x%interp%controlPoints)
    call WriteArray_HDF5(fileId,'/quadrature/weights', &
                         myGeom%x%interp%qWeights)
    call WriteArray_HDF5(fileId,'/quadrature/dgmatrix', &
                         myGeom%x%interp%dgMatrix)
    call WriteArray_HDF5(fileId,'/quadrature/dmatrix', &
                         myGeom%x%interp%dMatrix)
    call CreateGroup_HDF5(fileId,'/mesh')
    call CreateGroup_HDF5(fileId,'/mesh/interior')
    call CreateGroup_HDF5(fileId,'/mesh/boundary')
    call WriteArray_HDF5(fileId,'/mesh/interior/x',myGeom%x%interior)
    call WriteArray_HDF5(fileId,'/mesh/interior/dxds',myGeom%dxds%interior)
    call WriteArray_HDF5(fileId,'/mesh/boundary/x',myGeom%x%boundary)
    call WriteArray_HDF5(fileId,'/mesh/boundary/dxds',myGeom%dxds%boundary)
    call Close_HDF5(fileId)
  endsubroutine Write_Geometry1D
Call graph
write_geometry1d calls open_hdf5, close_hdf5, creategroup_hdf5, writearray_hdf5
open_hdf5 calls open_hdf5_serial, open_hdf5_parallel
close_hdf5 calls h5fclose_f, h5close_f
creategroup_hdf5 calls h5lexists_f, h5gclose_f, h5gcreate_f
writearray_hdf5 calls writearray_hdf5_real_r4_serial, writearray_hdf5_real_r2_serial, writearray_hdf5_int32_r1_serial, writearray_hdf5_int32_r3_serial, writearray_hdf5_real_r3_parallel, writearray_hdf5_real_r1_serial, writearray_hdf5_real_r3_serial, writearray_hdf5_real_r5_serial, writearray_hdf5_int32_r2_serial, writearray_hdf5_int32_r4_serial, writearray_hdf5_real_r4_parallel
open_hdf5_serial calls h5open_f, h5fopen_f, h5fcreate_f
writearray_hdf5_real_r4_serial calls h5screate_simple_f, h5dwrite_f, h5sclose_f, h5dclose_f, h5dcreate_f
writearray_hdf5_real_r2_serial calls h5screate_simple_f, h5dwrite_f, h5sclose_f, h5dclose_f, h5dcreate_f
writearray_hdf5_int32_r1_serial calls h5screate_simple_f, h5dwrite_f, h5sclose_f, h5dclose_f, h5dcreate_f
writearray_hdf5_int32_r3_serial calls h5screate_simple_f, h5dwrite_f, h5sclose_f, h5dclose_f, h5dcreate_f
writearray_hdf5_real_r3_parallel calls h5screate_simple_f, h5dwrite_f, h5sclose_f, h5pcreate_f, h5sselect_hyperslab_f, h5pclose_f, h5dclose_f, h5dcreate_f, h5pset_dxpl_mpio_f
open_hdf5_parallel calls h5open_f, h5fopen_f, h5pcreate_f, h5pclose_f, h5fcreate_f, h5pset_fapl_mpio_f
writearray_hdf5_real_r1_serial calls h5screate_simple_f, h5dwrite_f, h5sclose_f, h5dclose_f, h5dcreate_f
writearray_hdf5_real_r3_serial calls h5screate_simple_f, h5dwrite_f, h5sclose_f, h5dclose_f, h5dcreate_f
writearray_hdf5_real_r5_serial calls h5screate_simple_f, h5dwrite_f, h5sclose_f, h5dclose_f, h5dcreate_f
writearray_hdf5_int32_r2_serial calls h5screate_simple_f, h5dwrite_f, h5sclose_f, h5dclose_f, h5dcreate_f
writearray_hdf5_int32_r4_serial calls h5screate_simple_f, h5dwrite_f, h5sclose_f, h5dclose_f, h5dcreate_f
writearray_hdf5_real_r4_parallel calls h5screate_simple_f, h5dwrite_f, h5sclose_f, h5pcreate_f, h5sselect_hyperslab_f, h5pclose_f, h5dclose_f, h5dcreate_f, h5pset_dxpl_mpio_f