repos:
  - repo: local
    hooks:
      - id: fprettify
        name: fprettify
        entry: fprettify
        language: system
        types: [fortran]
        args: ["--config-file", "./fprettify.config", "--case", "1", "1", "1", "1"]
