# 
# To use this build,
# gcloud builds submit . --substitutions=_BUILD_BASE=pgi
#
# Options : 
#   _BUILD_BASE=[ pgi | pgi-openmpi | pgi-mvapich | gnu | gnu-openmpi | gnu-mvapich ]
#
timeout: 1800s

steps:

- id: SELF Build
  name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '.',
         '-t',
         'gcr.io/${PROJECT_ID}/self:${_TAG}',
         ]


substitutions:
  _TAG: 'dev'

images: ['gcr.io/${PROJECT_ID}/self:${_TAG}']

  #artifacts:
  #  objects:
  #    location: 'gs://${PROJECT_ID}-singularity/builds/${BRANCH_NAME}'
  #    paths: ['self-fluids_${_BUILD_BASE}.sif']
  #
    
