# 
# To use this build,
# gcloud builds submit . --substitutions=_BUILD_BASE=pgi
#
timeout: 30m

steps:
- name: 'gcr.io/$PROJECT_ID/singularity'
  args: ['build','--notest','self-fluids_${_BUILD_BASE}.sif','./cloudbuild/${_BUILD_BASE}/self-fluids.def']

substitutions:
  _BUILD_BASE: pgi

artifacts:
  objects:
    location: 'gs://${PROJECT_ID}-singularity/builds/${BRANCH_NAME}'
    paths: ['self-fluids_${_BUILD_BASE}.sif']
