
steps:
        # Add a step for formatting requirements

        - id: Build Docker Image
          name: 'gcr.io/cloud-builders/docker'
          args: ['build',
                 '--build-arg','BUILD_TYPE=${_BUILD_TYPE}',
                 '-f','docker/Dockerfile.${_PLATFORM}',
                 '.',
                 '-t',
                 'gcr.io/self-fluids/self_${_PLATFORM}:${_IMAGE_TAG}'
          ]

#        - id: Serial CPU Test
#          name: 'gcr.io/cloud-builders/docker'
#          args: ['run',
#                 '--entrypoint','/usr/bin/python3',
#                 '--env','WORKSPACE=/workspace',
#                 '--mount', 'type=bind,src=/workspace,dst=/workspace',
#                 'gcr.io/self-fluids/self_${_PLATFORM}:${_IMAGE_TAG}',
#                 '/opt/self/test/ciCheck.py'
#          ]

        - id: Build Singularity Image
          name: 'quay.io/singularity/singularity:v3.7.1'
          args: ['build',
                 'self_${_PLATFORM}.sif',
                 'docker-daemon://gcr.io/self-fluids/self_${_PLATFORM}:${_IMAGE_TAG}']
          waitFor: ["Build Docker Image"]


# Create CI Infrastructure

# Launch CI job on head node

# Copy Artifacts back from CI infrastructure

# Delete CI Infrastructure

# Check for zero exit codes

# Check for correctness
  


images: ['gcr.io/self-fluids/self_${_PLATFORM}:${_IMAGE_TAG}']

artifacts:
  objects:
    location: 'gs://self-fluids-singularity/${_IMAGE_TAG}'
    paths: ['self_${_PLATFORM}.sif']

timeout: 7200s

substitutions:
        _IMAGE_TAG: 'dev'
        _BUILD_TYPE: 'dev'
        _PLATFORM: 'serial-x86'
