
steps:
        - id: 'Build Singularity Image'
          name: 'gcr.io/self-fluids/singularity'
          args: ['build',
                 'self.sif',
                 './build/singularity/self.srf']

        - id: 'Test Singularity Image (GPU)'
          name: 'gcr.io/cloud-builders/gcloud'
          entrypoint: '/bin/sh'
          args: 
            - '-c'
            - |
                    ssh-keygen -b 2048 -t rsa -f /tmp/sshkey -q -N ""

                    gcloud compute ssh ci-controller --zone=us-west1-b \
                        --ssh-key-file=/tmp/sshkey \
                        --command="mkdir ${BUILD_ID}"

                    gcloud compute scp self.sif ci-controller:${BUILD_ID}/ \
                         --zone=us-west1-b \
                        --ssh-key-file=/tmp/sshkey

                    gcloud compute scp test.sh ci-controller:${BUILD_ID}/ \
                         --zone=us-west1-b \
                        --ssh-key-file=/tmp/sshkey

                    gcloud compute ssh ci-controller --zone=us-west1-b \
                        --ssh-key-file=/tmp/sshkey \
                        --command="cd ${BUILD_ID} && srun --account=ci-runners --partition=n1-standard-8-1xp100 --gres=gpu:1 -n1 ./test.sh --artifact singularity --image self.sif --gpu yes"
          

                        #images: ['gcr.io/self-fluids/self:dev']
 
timeout: 7200s

#substitutions:
#        _IMAGE_TAG: 'dev'
#        _ZONE: 'us-west1-b'
