
steps:
        - id: 'Build SELF'
          name: 'gcr.io/cloud-builders/docker'
          args: ['build',
                 '.',
                 '-t',
                 'gcr.io/self-fluids/self:dev'
          ]

        - id: 'Test SELF'
          name: 'gcr.io/cloud-builders/docker'
          args: ['run',
                 'gcr.io/self-fluids/self:dev',
                 '/bin/bash',
                 '/apps/self/bin/ci.sh'
                ]

images: ['gcr.io/self-fluids/self:dev']
timeout: 1800s
