
steps:

        - id: 'Build Docker Container'
          name: 'gcr.io/cloud-builders/docker'
          args: ['build',
                 '.',
                 '-t',
                 'gcr.io/${PROJECT_ID}/self:latest'
                ]

        - id: 'Run ci.sh'
          name: 'gcr.io/cloud-builders/docker'
          args: ['run',
                 'gcr.io/${PROJECT_ID}/self:latest'
                 '/bin/sh',
                 '/apps/self/bin/ci.sh'
                ]

images: ['gcr.io/${PROJECT_ID}/self:latest']
