# 
# To use this build,
# gcloud builds submit . --substitutions=_BUILD_BASE=pgi-hdf5
#

steps:
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'gs://${PROJECT_ID}-singularity/base/${_BUILD_BASE}.sif', '/workspace']
   
- name: 'gcr.io/$PROJECT_ID/singularity'
  args: ['build','self-fluids_${_BUILD_FLAVOR}.sif','./cloudbuild/self-fluids_${_BUILD_FLAVOR}.def']

substitutions:
  _BUILD_BASE: pgi-hdf5
  _BUILD_FLAVOR: pgi-serial

artifacts:
  objects:
    location: 'gs://${PROJECT_ID}-singularity/builds/${BRANCH_NAME}'
    paths: ['self-fluids_${_BUILD_FLAVOR}.sif']
