
steps:

        - id: Build Singularity Image
          name: 'gcr.io/self-fluids/singularity'
          args: ['build',
                 'self.sif',
                 './build/singularity/self.srf']


        - id: Test Application (GPU)
          name: 'gcr.io/cloud-builders/gcloud'
          entrypoint: '/bin/sh'
          args: 
            - '-c'
            - |
                    ssh-keygen -b 2048 -t rsa -f /tmp/sshkey -q -N ""


                    gcloud compute ssh ci-controller \
                       --zone=us-west1-b \
                       --ssh-key-file=/tmp/sshkey \
                       --command="mkdir -p ${BUILD_ID}"

                    gcloud compute scp self.sif ci-controller:${BUILD_ID} \
                       --zone=us-west1-b \
                       --ssh-key-file=/tmp/sshkey

                    gcloud compute scp test.sh ci-controller:${BUILD_ID} \
                       --zone=us-west1-b \
                       --ssh-key-file=/tmp/sshkey

                    gcloud compute ssh ci-controller \
                       --zone=us-west1-b \
                       --ssh-key-file=/tmp/sshkey \
                       --command="cd ${BUILD_ID} && srun -n1 --gres=gpu:1 --account=ci-runners --partition=n1-standard-8-1xp100 test.sh"

 
timeout: 1800s

artifacts:
  objects: 
    location: 'gs://self-fluids-singularity/${_IMAGE_TAG}'
    paths: ['self.sif']

substitutions:
        _IMAGE_TAG: 'dev'
