timeout: 1800s

steps:

- id: SELF Build
  name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '.',
         '-t',
         'gcr.io/${PROJECT_ID}/self:${_IMAGE_TAG}'
         ]

- id: SELF Testing
  name: 'gcr.io/cloud-builders/docker'
  args: ['run',
         'gcr.io/${PROJECT_ID}/self:${_IMAGE_TAG}',
         '/bin/bash','/apps/self/bin/ci.sh'
         ]

substitutions:
  _IMAGE_TAG: 'dev'

images: ['gcr.io/${PROJECT_ID}/self:${_IMAGE_TAG}']
