
steps:
        - id: 'Build Docker Container Image'
          name: 'gcr.io/cloud-builders/docker'
          args: ['build',
                 '.',
                 '-t',
                 'gcr.io/${PROJECT_ID}/self:latest']

        - id: 'Run CI Tests'
          name: 'gcr.io/cloud-builder/docker'
          args: ['run',
                 'gcr.io/${PROJECT_ID}/self:latest',
                 '/bin/bash', 
                 '/apps/self/bin/ci.sh']

images: ['gcr.io/${PROJECT_ID}/self:latest']
