name = "SELF"
version = "0.0.0"
license = "license"
author = "Joe Schoonover (Fluid Numerics LLC)"
maintainer = "joe@fluidnumerics.com"
copyright = "Copyright 2018-2023, Fluid Numerics LLC"

[build]
auto-executables = true
auto-tests = true
auto-examples = false

[install]
library = true

[build]
external-modules = ["hdf5","mpi"]
link = ["hdf5", "hdf5_fortran","mpi"]

[dependencies]
json-fortran.git = "https://github.com/jacobwilliams/json-fortran"
json-fortran.branch = "master"
feq-parse.git = "https://github.com/fluidnumerics/feq-parse"
feq-parse.branch = "master"