site_name: Spectral Element Library in Fortran
site_description: SELF Documentation
site_author: Fluid Numerics
site_dir: public
site_url: ""
repo_name: GitHub/fluidnumerics/SELF
repo_url: https://github.com/fluidnumerics/SELF
edit_uri: edit/main/docs/mkdocs

# Directory where site content is located
docs_dir: docs

# Site navigation 
nav:
  - Home: index.md
  - Getting Started:
    - Installation: GettingStarted/install.md
    - Dependencies: GettingStarted/dependencies.md
    - Building Applications with SELF: GettingStarted/building-with-self.md
    - Using Multiple GPUs: GettingStarted/multi-gpu.md
  - Tutorials:
    - Burgers Equation:
      - Traveling Shock : Tutorials/BurgersEquation1D/TravelingShock.md
    - Linear Euler (2D):
      - Plane wave propagation: Tutorials/LinearEuler2D/PlaneWavePropagation.md
      - Plane wave reflection: Tutorials/LinearEuler2D/PlaneWaveReflection.md
      - Spherical sound wave: Tutorials/LinearEuler2D/SphericalSoundWave.md
  #    - Create your own model: Tutorials/CreateYourOwnModel.md
  - Models:
    - Viscous Burgers Equation: Models/burgers-equation-model.md
    - Linear Euler (2D) : Models/linear-euler-2d-model.md
#    - Generic DG Models: Models/generic-dg-models.md
  - Mesh Generation:
    - Overview: MeshGeneration/Overview.md
    - Structured Mesh Generators: MeshGeneration/StructuredMesh.md
   # - Importing other mesh types with HOPr: MeshGeneration/HOPr.md
  #- Post Processing:
  #  - Visualization with PySELF: PostProcessing/VisualizationWithPyself.md
  - Learning:
    - Theory:
      - Spectral Approximations: Learning/SpectralApproximations.md
      - Differential Geometry: Learning/DifferentialGeometry.md
      - Provable Stability: Learning/ProvableStability.md
    - Code:
      - Software Architecture: Learning/SoftwareArchitecture.md
      - Dependencies: Learning/dependencies.md
  - API Documentation: ford/index.html
  - Contributing:
    - Documentation: Contributing/Documentation.md

theme: 
  name: material
  favicon: assets/images/favicon.png
  logo: assets/images/logo-fluid-numerics.png
  palette:
    - scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
         
    - scheme: default 
      primary: black
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

markdown_extensions:
  - toc:
      permalink: "#"
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


plugins: 
    - glightbox