#!/bin/bash

# Compilers
export FC=pgfortran
export MPIFC=mpif90

# Support
export DEBUG=no
export TIMING=no

# Precision
export DOUBLE_PRECISION=no

# Geometry
export CURL_INVARIANT=no

# Parallelization schemes
export CUDA=yes
export GPU_ARCH=cc60
export CUDA_VERSION=cuda9.2
export GPU_DIRECT=no

export MPI=yes
export MPI_LIB=
export MPI_INC=

export OMP=no

# SELF Features
export PASSIVE_TRACERS=yes
