BlockMesh3D_Test – SELF
BlockMesh3D_Test Subroutine
75 statements
Source File
public subroutine BlockMesh3D_Test(cqType, tqType, cqDegree, tqDegree, nElem, tolerance, error)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: cqType
integer, intent(in) :: tqType
integer, intent(in) :: cqDegree
integer, intent(in) :: tqDegree
integer, intent(in) :: nElem
real(kind=prec), intent(in) :: tolerance
integer, intent(out) :: error
Calls
Called by
Contents
Source Code
BlockMesh3D_Test
Source Code
  SUBROUTINE BlockMesh3D_Test(cqType,tqType,cqDegree,tqDegree,nElem,tolerance,error)
#undef __FUNC__
#define __FUNC__ "BlockMesh3D_Test"
    IMPLICIT NONE
    INTEGER,INTENT(in) :: cqType
    INTEGER,INTENT(in) :: tqType
    INTEGER,INTENT(in) :: cqDegree
    INTEGER,INTENT(in) :: tqDegree
    INTEGER,INTENT(in) :: nElem
    REAL(prec),INTENT(in) :: tolerance
    INTEGER,INTENT(out) :: error
    ! Local
    CHARACTER(240) :: msg
    TYPE(Mesh3D) :: mesh
    TYPE(SEMHex) :: geometry
    REAL(prec) :: expect_dxds(1:3,1:3),dxds_error(1:3,1:3)
    REAL(prec) :: expect_J,J_error
    INTEGER :: iel,jel,kel,i,j,k
    INTEGER :: row,col
    error = 0
    msg = 'Number of elements : '//Int2Str(nElem*nElem*nElem)
    INFO(TRIM(msg))
    INFO('Control point degree : '//Int2Str(cqDegree))
    INFO('Target point degree : '//Int2Str(tqDegree))
    INFO('Error tolerance : '//Float2Str(tolerance))
    CALL mesh % UniformBlockMesh(cqDegree, &
                                 (/nElem,nElem,nElem/), &
                                 (/0.0_prec,1.0_prec, &
                                   0.0_prec,1.0_prec, &
                                   0.0_prec,1.0_prec/))
    ! Create the geometry
    CALL geometry % GenerateFromMesh(mesh,cqType,tqType,cqDegree,tqDegree)
    ! Verify the mesh
    expect_dxds(1,1) = (1.0_prec/REAL(nElem,prec))/2.0_prec
    expect_dxds(1,2) = 0.0_prec
    expect_dxds(1,3) = 0.0_prec
    expect_dxds(2,1) = 0.0_prec
    expect_dxds(2,2) = (1.0_prec/REAL(nElem,prec))/2.0_prec
    expect_dxds(2,3) = 0.0_prec
    expect_dxds(3,1) = 0.0_prec
    expect_dxds(3,2) = 0.0_prec
    expect_dxds(3,3) = (1.0_prec/REAL(nElem,prec))/2.0_prec
    expect_J = expect_dxds(1,1)*expect_dxds(2,2)*expect_dxds(3,3)
    ! Calculate error in metric terms
    dxds_error = 0.0_prec
    J_error = 0.0_prec
    DO iel = 1,nElem
      DO k = 0,cqDegree
        DO j = 0,cqDegree
          DO i = 0,cqDegree
            DO col = 1,3
              DO row = 1,3
                dxds_error(row,col) = MAX(dxds_error(row,col), &
                                          ABS(geometry % dxds % &
                                              interior % hostData(row,col,i,j,k,1,iel) - &
                                              expect_dxds(row,col)))
              END DO
            END DO
            J_error = MAX(J_error,ABS(geometry % J % &
                                      interior % hostData(i,j,k,1,iel) - &
                                      expect_J))
          END DO
        END DO
      END DO
    END DO
    CALL mesh % Free()
    CALL geometry % Free()
    DO col = 1,3
      DO row = 1,3
        msg = "Numerical Error (dx/ds) ("// &
              TRIM(Int2Str(row))//","// &
              TRIM(Int2Str(col))//") : "// &
              Float2Str(dxds_error(row,col))
        IF (dxds_error(row,col) > tolerance) THEN
          error = error + 1
          ERROR(TRIM(msg))
          ERROR("Status : [FAIL]")
        ELSE
          INFO(TRIM(msg))
          INFO("Status : [PASS]")
        END IF
      END DO
    END DO
    msg = "Numerical Error (Jacobian) : "//Float2Str(J_error)
    IF (J_error > tolerance) THEN
      error = error + 1
      ERROR(TRIM(msg))
      ERROR("Status : [FAIL]")
    ELSE
      INFO(TRIM(msg))
      INFO("Status : [PASS]")
    END IF
  END SUBROUTINE BlockMesh3D_Test
Call graph
blockmesh3d_test calls int2str, float2str, info
self calls blockmesh3d_test