Float2Str – SELF
Float2Str Function
6 statements
Source File
public function Float2Str(aNumber) result(aString)
Arguments
Type Intent Optional Attributes Name
real(kind=prec) :: aNumber
Return Value character(len=12)
Called by
Contents
Source Code
Float2Str
Source Code
  FUNCTION Float2Str(aNumber) RESULT(aString)
    IMPLICIT NONE
    REAL(prec) :: aNumber
    CHARACTER(12) :: aString
    WRITE (aString,'(E12.4)') aNumber
  END FUNCTION Float2Str
Call graph
vectorinterp2d_test calls float2str
vectordivergence2d_test calls float2str
vectorinterp3d_test calls float2str
blockmesh3d_test calls float2str
tensorinterp3d_test calls float2str
vectorboundaryinterp2d_test calls float2str
tensorboundaryinterp2d_test calls float2str
scalarboundaryinterp2d_test calls float2str
vectorgradient2d_test calls float2str
tensorboundaryinterp3d_test calls float2str
blockmesh1d_test calls float2str
scalarboundaryinterp3d_test calls float2str
tensorinterp2d_test calls float2str
vectorgradient3d_test calls float2str
scalarinterp3d_test calls float2str
scalargradient2d_test calls float2str
scalarboundaryinterp1d_test calls float2str
scalarinterp1d_test calls float2str
scalarinterp2d_test calls float2str
vectorboundaryinterp3d_test calls float2str
vectordivergence3d_test calls float2str
scalarderivative1d_test calls float2str
scalargradient3d_test calls float2str
blockmesh2d_test calls float2str
self calls vectorinterp3d_test, blockmesh3d_test, tensorinterp3d_test, scalarboundaryinterp2d_test, tensorboundaryinterp3d_test, blockmesh1d_test, scalarboundaryinterp3d_test, vectorgradient3d_test, scalarinterp3d_test, scalarboundaryinterp1d_test, scalarinterp1d_test, scalarinterp2d_test, vectorboundaryinterp3d_test, vectordivergence3d_test, scalarderivative1d_test, scalargradient3d_test, blockmesh2d_test