GPUAvailable – SELF
GPUAvailable Function
Anti-Capitalist Software License
12 statements
Source File
public function GPUAvailable() result(avail)
Arguments
None
Return Value logical
Calls
Called by
Contents
Source Code
GPUAvailable
Source Code
  FUNCTION GPUAvailable() RESULT(avail)
    IMPLICIT NONE
    LOGICAL :: avail
    ! Local
    INTEGER :: gpuCount
    INTEGER(KIND(hipSuccess)) :: err
    err = hipGetDeviceCount(gpuCount)
    IF (gpuCount > 0 .AND. err == hipSuccess) THEN
      avail = .TRUE.
    ELSE
      avail = .FALSE.
    END IF
  END FUNCTION GPUAvailable
Call graph
gpuavailable calls hipgetdevicecount
updatedevice_hfreal_r6 calls gpuavailable
alloc_hfreal_r2 calls gpuavailable
alloc_hfint32_r5 calls gpuavailable
updatedevice_hfreal_r4 calls gpuavailable
alloc_hfreal_r5 calls gpuavailable
updatedevice_hfreal_r3 calls gpuavailable
updatedevice_hfint32_r6 calls gpuavailable
updatedevice_hfint64_r2 calls gpuavailable
free_hfint32_r7 calls gpuavailable
free_hfint32_r5 calls gpuavailable
updatehost_hfint32_r5 calls gpuavailable
updatehost_hfint64_r4 calls gpuavailable
alloc_hfint64_r5 calls gpuavailable
updatehost_hfint64_r5 calls gpuavailable
free_hfreal_r4 calls gpuavailable
updatehost_hfint64_r3 calls gpuavailable
updatedevice_hfint64_r5 calls gpuavailable
free_hfreal_r7 calls gpuavailable
alloc_hfint32_r1 calls gpuavailable
updatehost_hfint32_r3 calls gpuavailable
alloc_hfint64_r6 calls gpuavailable
free_hfint32_r3 calls gpuavailable
updatedevice_hfreal_r1 calls gpuavailable
free_hfreal_r3 calls gpuavailable
free_hfint64_r6 calls gpuavailable
updatehost_hfint32_r1 calls gpuavailable
updatedevice_hfint64_r3 calls gpuavailable
alloc_hfint32_r7 calls gpuavailable
free_hfint32_r2 calls gpuavailable
alloc_hfint64_r1 calls gpuavailable
updatehost_hfint32_r4 calls gpuavailable
free_hfreal_r1 calls gpuavailable
free_hfint32_r1 calls gpuavailable
free_hfreal_r2 calls gpuavailable
updatehost_hfreal_r3 calls gpuavailable
free_hfint32_r6 calls gpuavailable
free_hfreal_r5 calls gpuavailable
updatedevice_hfint32_r1 calls gpuavailable
updatedevice_hfint64_r7 calls gpuavailable
updatedevice_hfint64_r1 calls gpuavailable
updatehost_hfreal_r1 calls gpuavailable
free_hfint64_r7 calls gpuavailable
alloc_hfint32_r3 calls gpuavailable
updatehost_hfreal_r2 calls gpuavailable
alloc_hfreal_r3 calls gpuavailable
free_hfint64_r5 calls gpuavailable
updatehost_hfreal_r4 calls gpuavailable
free_hfint32_r4 calls gpuavailable
alloc_hfint64_r3 calls gpuavailable
alloc_hfint64_r2 calls gpuavailable
alloc_hfint32_r4 calls gpuavailable
alloc_hfreal_r7 calls gpuavailable
updatedevice_hfint32_r3 calls gpuavailable
updatedevice_hfint32_r4 calls gpuavailable
updatehost_hfint32_r2 calls gpuavailable
free_hfreal_r6 calls gpuavailable
updatehost_hfreal_r6 calls gpuavailable
updatedevice_hfint64_r4 calls gpuavailable
updatedevice_hfint64_r6 calls gpuavailable
updatedevice_hfreal_r2 calls gpuavailable
free_hfint64_r1 calls gpuavailable
updatedevice_hfint32_r2 calls gpuavailable
updatehost_hfint32_r7 calls gpuavailable
updatehost_hfint64_r7 calls gpuavailable
updatedevice_hfint32_r7 calls gpuavailable
updatehost_hfint64_r2 calls gpuavailable
free_hfint64_r3 calls gpuavailable
free_hfint64_r2 calls gpuavailable
alloc_hfreal_r1 calls gpuavailable
updatehost_hfint64_r1 calls gpuavailable
alloc_hfreal_r6 calls gpuavailable
updatehost_hfreal_r5 calls gpuavailable
alloc_hfreal_r4 calls gpuavailable
updatehost_hfint64_r6 calls gpuavailable
alloc_hfint32_r2 calls gpuavailable
updatedevice_hfreal_r5 calls gpuavailable
updatedevice_hfint32_r5 calls gpuavailable
free_hfint64_r4 calls gpuavailable
alloc_hfint64_r7 calls gpuavailable
updatehost_hfint32_r6 calls gpuavailable
alloc_hfint32_r6 calls gpuavailable
updatehost_hfreal_r7 calls gpuavailable
updatedevice_hfreal_r7 calls gpuavailable
alloc_hfint64_r4 calls gpuavailable