Init_MPILayer – SELF
Init_MPILayer Subroutine
Anti-Capitalist Software License
28 statements
Source File
public subroutine Init_MPILayer(this, enableMPI)
Arguments
Type Intent Optional Attributes Name
class(MPILayer), intent(out) :: this
logical, intent(in) :: enableMPI
Calls
Contents
Source Code
Init_MPILayer
Source Code
  SUBROUTINE Init_MPILayer(this,enableMPI)
#undef __FUNC__
#define __FUNC__ "Init_MPILayer"
    IMPLICIT NONE
    CLASS(MPILayer),INTENT(out) :: this
    LOGICAL,INTENT(in) :: enableMPI
    ! Local
    INTEGER       :: ierror
    CHARACTER(30) :: msg
    this % mpiComm = 0
    this % mpiPrec = prec
    this % rankId = 0
    this % nRanks = 1
    this % nElem = 0
    this % mpiEnabled = enableMPI
    IF (enableMPI) THEN
      this % mpiComm = MPI_COMM_WORLD
      CALL MPI_INIT(ierror)
      CALL MPI_COMM_RANK(this % mpiComm,this % rankId,ierror)
      CALL MPI_COMM_SIZE(this % mpiComm,this % nRanks,ierror)
    END IF
    IF (prec == real32) THEN
      this % mpiPrec = MPI_FLOAT
    ELSE
      this % mpiPrec = MPI_DOUBLE
    END IF
    CALL this % offSetElem % Alloc(0,this % nRanks)
    WRITE (msg,'(I5)') this % rankId
    msg = "Greetings from rank "//TRIM(msg)//"."
    INFO(TRIM(msg))
  END SUBROUTINE Init_MPILayer
Call graph
init_mpilayer calls mpi_comm_size, info, mpi_comm_rank, mpi_init