Invert_2x2 – SELF
Invert_2x2 Function
11 statements
Source File
public function Invert_2x2(A) result(Ainv)
\addtogroup SELF_SupportRoutines @{ \fn Invert_2x2 Computes the inverse of a 2x2 matrix using Kramer's rule.
This Function depends on
\ref determinant
Usage :
REAL(prec) :: A(1:2,1:2), Ainv(1:2,1:2)
....
Ainv = Invert_2x2(A)
Parameters :
in A(1:2,1:2) REAL(prec) Real 2x2 matrix
in Ainv(1:2,1:2) REAL(prec) Real 2x2 matrix, inverse of A
@}
Arguments
Type Intent Optional Attributes Name
real(kind=prec) :: A(1:2,1:2)
Return Value real(kind=prec) (1:2,1:2)
Calls
Contents
Source Code
Invert_2x2
Source Code
  FUNCTION Invert_2x2(A) RESULT(Ainv)
    IMPLICIT NONE
    REAL(prec) :: A(1:2,1:2)
    REAL(prec) :: Ainv(1:2,1:2)
    ! LOCAL
    REAL(prec) :: detA
    detA = Determinant(A,2)
    Ainv(1,1) = A(2,2)/detA
    Ainv(2,2) = A(1,1)/detA
    Ainv(1,2) = -A(1,2)/detA
    Ainv(2,1) = -A(2,1)/detA
  END FUNCTION Invert_2x2
Call graph
invert_2x2 calls determinant
determinant calls getminor, determinant