LegendreQuadrature – SELF
LegendreQuadrature Subroutine
19 statements
Source File
public subroutine LegendreQuadrature(N, nodes, weights, QuadType)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: N
real(kind=prec), intent(out) :: nodes(0:N)
real(kind=prec), intent(out) :: weights(0:N)
integer, intent(in) :: QuadType
Calls
Called by
Contents
Source Code
LegendreQuadrature
Source Code
  SUBROUTINE LegendreQuadrature(N,nodes,weights,QuadType)
    IMPLICIT NONE
    INTEGER,INTENT(in)     :: N
    REAL(prec),INTENT(out) :: nodes(0:N)
    REAL(prec),INTENT(out) :: weights(0:N)
    INTEGER,INTENT(in)     :: QuadType
    ! Local
    REAL(real64) :: nodesLocal(0:N)
    REAL(real64) :: weightsLocal(0:N)
    INTEGER :: i
    IF (QuadType == GAUSS_LOBATTO) THEN
      CALL LegendreGaussLobatto(N,nodesLocal,weightsLocal)
    ELSEIF (QuadType == GAUSS) THEN
      CALL LegendreGauss(N,nodesLocal,weightsLocal)
    END IF
    DO i = 0, N
      nodes(i) = REAL(nodesLocal(i),prec)
      weights(i) = REAL(weightsLocal(i),prec)
    ENDDO
  END SUBROUTINE LegendreQuadrature
Call graph
legendrequadrature calls legendregausslobatto, legendregauss
legendregausslobatto calls legendreqandl
legendregauss calls legendrepolynomial
init_lagrange calls legendrequadrature