LegendreGaussLobatto – SELF
LegendreGaussLobatto Subroutine
43 statements
Source File
private subroutine LegendreGaussLobatto(N, nodes, weights)
Arguments
Type Intent Optional Attributes Name
integer :: N
real(kind=real64) :: nodes(0:N)
real(kind=real64) :: weights(0:N)
Calls
Called by
Contents
Source Code
LegendreGaussLobatto
Source Code
  SUBROUTINE LegendreGaussLobatto(N,nodes,weights)
    IMPLICIT NONE
    INTEGER    :: N
    REAL(real64) :: nodes(0:N)
    REAL(real64) :: weights(0:N)
    ! Local
    REAL(real64) :: nodes_local(0:N)
    REAL(real64) :: weights_local(0:N)
    REAL(real64) :: delta,q,qprime,lN
    INTEGER  :: j,kIt
    IF (N == 1) then
      nodes_local(0) = -1.0_real64
      weights_local(0) = 1.0_real64
      nodes_local(1) = 1.0_real64
      weights_local(1) = 1.0_real64
    ELSE
      nodes_local(0) = -1.0_real64
      weights_local(0) = 2.0_real64/(REAL(N,real64)*(REAL(N,real64) + 1.0_real64))
      nodes_local(N) = 1.0_real64
      weights_local(N) = weights_local(0)
      DO j = 1, ((N + 1)/2 - 1)
        nodes_local(j) = -COS((REAL(j,real64) + 0.25_real64)*pi/REAL(N,real64) - &
                              3.0_real64/(8.0_real64*REAL(N,real64)*pi*(REAL(j,real64) + 0.25_real64)))
        DO kIt = 1,newtonMax
          CALL LegendreQandL(N,nodes_local(j),q,qprime,lN)
          delta = -q/qprime
          nodes_local(j) = nodes_local(j) + delta
          IF (ABS(delta) <= TOL*nodes_local(j)) EXIT
        END DO
        CALL LegendreQandL(N,nodes_local(j),q,qprime,lN)
        weights_local(j) = 2.0_real64/(REAL(N,real64)*(REAL(N,real64) + 1.0_real64)*lN*lN)
        weights_local(N - j) = weights_local(j)
        nodes_local(N - j) = -nodes_local(j)
      END DO
    END IF
    IF (MOD(REAL(N,real64),2.0_real64) == 0.0_real64) THEN
      CALL LegendreQandL(N,0.0_real64,q,qprime,lN)
      nodes_local(N/2) = 0.0_real64
      weights_local(N/2) = 2.0_real64/(REAL(N,real64)*(REAL(N,real64) + 1.0_real64)*lN*lN)
    END IF
    DO j = 0,N
      nodes(j) = REAL(nodes_local(j),real64)
      weights(j) = REAL(weights_local(j),real64)
    END DO
  END SUBROUTINE LegendreGaussLobatto
Call graph
legendregausslobatto calls legendreqandl
legendrequadrature calls legendregausslobatto
init_lagrange calls legendrequadrature