Open_HDF5_parallel – SELF
Open_HDF5_parallel Subroutine
Anti-Capitalist Software License
23 statements
Source File
private subroutine Open_HDF5_parallel(fileName, accessFlag, fileId, mpiComm)
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: fileName
integer, intent(in) :: accessFlag
integer(kind=HID_T), intent(inout) :: fileId
integer, intent(in) :: mpiComm
Calls
Called by
Contents
Source Code
Open_HDF5_parallel
Source Code
  SUBROUTINE Open_HDF5_parallel(fileName,accessFlag,fileId,mpiComm)
    IMPLICIT NONE
    CHARACTER(*),INTENT(in) :: fileName
    INTEGER,INTENT(in) :: accessFlag
    INTEGER(HID_T),INTENT(inout) :: fileId
    INTEGER,INTENT(in) :: mpiComm
    ! Local
    INTEGER(HID_T) :: plistId
    INTEGER :: error
    CALL h5open_f(error)
    CALL h5pcreate_f(H5P_FILE_ACCESS_F,plistId,error)
    CALL h5pset_fapl_mpio_f(plistId,mpiComm,MPI_INFO_NULL,error)
    CALL h5fopen_f(TRIM(fileName),accessFlag,fileId,error,plistId)
    IF (accessFlag == H5F_ACC_TRUNC_F) THEN
      CALL h5fcreate_f(TRIM(fileName),accessFlag,fileId,error,plistId)
    ELSE
      CALL h5fopen_f(TRIM(fileName),accessFlag,fileId,error,plistId)
    END IF
    CALL h5pclose_f(plistId,error)
    IF (error == -1) THEN
      PRINT *, 'Failed to open '//TRIM(fileName)//'.'
      STOP - 1
    END IF
  END SUBROUTINE Open_HDF5_parallel
Call graph
open_hdf5_parallel calls h5pset_fapl_mpio_f, h5pcreate_f, h5pclose_f, h5fopen_f, h5open_f, h5fcreate_f
open_hdf5 calls open_hdf5_parallel