Read_ISMv2_Mesh2D – SELF
Read_ISMv2_Mesh2D Subroutine
Anti-Capitalist Software License
103 statements
Source File
public subroutine Read_ISMv2_Mesh2D(myMesh, meshFile)
Arguments
Type Intent Optional Attributes Name
class(Mesh2D), intent(out) :: myMesh
character, intent(in) :: meshFile
Calls
Contents
Source Code
Read_ISMv2_Mesh2D
Source Code
  SUBROUTINE Read_ISMv2_Mesh2D(myMesh,meshFile)
#undef __FUNC__
#define __FUNC__ "Read_ISMv2_Mesh2D"
    IMPLICIT NONE
    CLASS(Mesh2D),INTENT(out) :: myMesh
    CHARACTER(*),INTENT(in) :: meshFile
    ! Local
    INTEGER :: nNodes,nSides,nElem,nGeo
    INTEGER :: lnid,nid,usid,lsid,sid,eid
    INTEGER :: fUnit
    INTEGER :: i,j
    CHARACTER(100) :: line
    CHARACTER(500) :: msg
    REAL(prec) :: x(1:3),x0(1:2),x1(1:2)
    REAL(prec) :: wSurf(1:2),eSurf(1:2),nSurf(1:2),sSurf(1:2)
    REAL(prec) :: P1(1:2),P2(1:2)
    REAL(prec) :: l1(1:2),l2(1:2)
    REAL(prec) :: se(1:2),sw(1:2),ne(1:2),nw(1:2)
    INTEGER :: bCurveFlag(1:4)
    TYPE(Lagrange) :: interp
    OPEN (UNIT=NEWUNIT(fUnit), &
          FILE=TRIM(meshFile), &
          FORM='FORMATTED', &
          STATUS='OLD', &
          ACCESS='SEQUENTIAL')
    READ (fUnit,*) line
    IF (TRIM(line) /= 'ISM-V2') THEN
      msg = 'Unrecognized file format : '//TRIM(line)
      ERROR(msg)
      STOP
    END IF
    ! Number of Nodes, Number of Edges (sides; unique!), number of elements, polynomial degree of elements
    READ (fUnit,*) nNodes,nSides,nElem,nGeo
    ! HOHQMesh reports interpolant data on Chebyshev Lobatto points
    ! We want data to be interpolated to Legendre Gauss Lobatto points
    CALL interp % Init(nGeo,CHEBYSHEV_GAUSS_LOBATTO,nGeo,GAUSS_LOBATTO)
    ! When we initialize the mesh, we set nNodes=nElem*4*(nGeo+1)**2 and
    ! nSides = nElem*4 since we still use `nNodes` and `nSides`
    ! in the input correspond to the HOPR definitions of these
    ! variables.
    ! `nSides` in HOHQMesh corresponds to nUniqueSides in HOPR and SELF
    ! `nNodes` in HOHQMesh corresponds to nCornerNodes (unique) in HOPR and SELF
    CALL myMesh % Init(nGeo,nElem,nElem*4,nElem*(nGeo + 1)**2,self_nBCsDefault)
    myMesh % nUniqueSides = nSides
    myMesh % nCornerNodes = nNodes
    CALL myMesh % hohq_cornerNodes % Alloc((/1,1/), &
                                           (/2,nNodes/))
    CALL myMesh % hohq_sideInfo % Alloc((/1,1/), &
                                        (/6,nSides/))
    CALL myMesh % hohq_elemInfo % Alloc((/1,1/), &
                                        (/4,nElem/))
    CALL myMesh % hohq_sideCurves % Alloc((/1,0,1,1/), &
                                          (/2,nGeo,4,nElem/))
    DO nid = 1,myMesh % nCornerNodes
      READ (fUnit,*) x
      myMesh % hohq_cornerNodes % hostData(1:2,nid) = x(1:2)
    END DO
    DO usid = 1,myMesh % nUniqueSides
      READ (fUnit,*) myMesh % hohq_sideInfo % hostData(1:6,usid)
    END DO
    DO eid = 1,myMesh % nElem
      READ (fUnit,*) myMesh % hohq_elemInfo % hostData(1:4,eid)
      READ (fUnit,*) bCurveFlag(1:4)
      DO lsid = 1,4
        IF (bCurveFlag(lsid) == 1) THEN
          DO i = 0,nGeo
            READ (fUnit,*) x
            myMesh % hohq_sideCurves % hostData(1:2,i,lsid,eid) = x(1:2)
          END DO
        ELSE
          ! For non-polynomial sides, create the side curve through interpolation between corner nodes
          lnid = myMesh % hopr_CGNSSideMap % hostData(1,lsid)
          nid = myMesh % hohq_elemInfo % hostData(lnid,eid)
          x0(1:2) = myMesh % hohq_cornerNodes % hostData(1:2,nid)
          lnid = myMesh % hopr_CGNSSideMap % hostData(2,lsid)
          nid = myMesh % hohq_elemInfo % hostData(lnid,eid)
          x1(1:2) = myMesh % hohq_cornerNodes % hostData(1:2,nid)
          DO i = 0,nGeo
            myMesh % hohq_sideCurves % hostData(1:2,i,lsid,eid) = 0.5_prec*( &
                                                           x0(1:2)*(1.0_prec - interp % controlPoints % hostData(i)) + &
                                                              x1(1:2)*(interp % controlPoints % hostData(i) + 1.0_prec))
          END DO
        END IF
      END DO
      READ (fUnit,*) line
      ! TO DO : Parse line for boundary conditions
    END DO
    CLOSE (fUnit)
    ! Fill in hopr_elemInfo
    ! To fill in the element info, we apply the assumption of a mesh with all quadrilateral elements
    ! with uniform polynomial order
    sid = 1
    nid = 1
    DO eid = 1,myMesh % nElem
      myMesh % hopr_elemInfo % hostData(1,eid) = selfQuadLinear ! Element Type
      myMesh % hopr_elemInfo % hostData(2,eid) = 1 ! Element Zone
      myMesh % hopr_elemInfo % hostData(3,eid) = sid ! Side Index Start
      sid = sid + 4
      myMesh % hopr_elemInfo % hostData(4,eid) = sid ! Side Index End
      myMesh % hopr_elemInfo % hostData(5,eid) = nid - 1 ! Node Index Start
      nid = nid + (nGeo + 1)**2
      myMesh % hopr_elemInfo % hostData(6,eid) = nid ! Node Index End
    END DO
    ! Generate the self_nodeCoords through transfinite interpolation with linear blending
    nid = 1
    DO eid = 1,myMesh % nElem
      lnid = 1
      ! Evaluate for corner points of mapping. This requires computational coordinates
      ! that include -1 and 1 in each computational direction (e.g. Gauss Lobatto)
      sw = myMesh % hohq_sideCurves % hostData(1:2,0,1,eid)
      se = myMesh % hohq_sideCurves % hostData(1:2,nGeo,1,eid)
      ne = myMesh % hohq_sideCurves % hostData(1:2,nGeo,3,eid)
      nw = myMesh % hohq_sideCurves % hostData(1:2,0,3,eid)
      DO j = 0,nGeo
        wSurf = myMesh % hohq_sideCurves % hostData(1:2,j,4,eid)
        eSurf = myMesh % hohq_sideCurves % hostData(1:2,j,2,eid)
        l2 = LinearBlend(interp % controlPoints % hostData(j))
        DO i = 0,nGeo
          sSurf = myMesh % hohq_sideCurves % hostData(1:2,i,1,eid)
          nSurf = myMesh % hohq_sideCurves % hostData(1:2,i,3,eid)
          l1 = LinearBlend(interp % controlPoints % hostData(i))
          P1 = l1(1)*wSurf + l1(2)*eSurf
          P2 = l2(1)*sSurf + l2(2)*nSurf
          ! Apply transfinite interpolation with linear blending
          myMesh % self_nodeCoords % hostData(1:2,lnid,eid) = P1 + P2 - &
                                                              l1(1)*(l2(1)*sw + l2(2)*nw) - l1(2)*(l2(1)*se + l2(2)*ne)
          myMesh % hopr_nodeCoords % hostData(1:2,nid) = myMesh % self_nodeCoords % hostData(1:2,lnid,eid)
          ! Increment node ids
          nid = nid + 1
          lnid = lnid + 1
        END DO
      END DO
    END DO
    CALL myMesh % GenerateConnectivity()
    CALL interp % Free()
  END SUBROUTINE Read_ISMv2_Mesh2D
Call graph
read_ismv2_mesh2d calls linearblend, newunit, error