ScalarGradient3D_Test – SELF
ScalarGradient3D_Test Subroutine
97 statements
Source File
public subroutine ScalarGradient3D_Test(cqType, tqType, cqDegree, tqDegree, dForm, nElem, nVar, fChar, gradientChar, tolerance, gpuAccel, error)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: cqType
integer, intent(in) :: tqType
integer, intent(in) :: cqDegree
integer, intent(in) :: tqDegree
integer, intent(in) :: dForm
integer, intent(in) :: nElem
integer, intent(in) :: nVar
character(len=*), intent(in) :: fChar
character(len=240), intent(in) :: gradientChar(1:3)
real(kind=prec), intent(in) :: tolerance
logical, intent(in) :: gpuAccel
integer, intent(out) :: error
Calls
Called by
Contents
Source Code
ScalarGradient3D_Test
Source Code
  SUBROUTINE ScalarGradient3D_Test(cqType,tqType,cqDegree,tqDegree,dForm,nElem,nvar,&
                                   fChar,gradientChar,tolerance,gpuAccel,error)
#undef __FUNC__
#define __FUNC__ "ScalarGradient3D_Test"
    IMPLICIT NONE
    INTEGER,INTENT(in) :: cqType
    INTEGER,INTENT(in) :: tqType
    INTEGER,INTENT(in) :: cqDegree
    INTEGER,INTENT(in) :: tqDegree
    INTEGER,INTENT(in) :: dForm
    INTEGER,INTENT(in) :: nElem
    INTEGER,INTENT(in) :: nVar
    CHARACTER(*),INTENT(in) :: fChar
    CHARACTER(240),INTENT(in) :: gradientChar(1:3)
    REAL(prec),INTENT(in) :: tolerance
    LOGICAL,INTENT(in) :: gpuAccel
    INTEGER,INTENT(out) :: error
    ! Local
    CHARACTER(240) :: msg
    TYPE(Mesh3D) :: controlMesh
    TYPE(SEMHex) :: controlGeometry
    TYPE(EquationParser) :: feq,gxeq,gyeq,gzeq
    TYPE(MappedScalar3D) :: f
    TYPE(MappedTensor3D) :: workTensor
    TYPE(MappedVector3D) :: dfInterp,dfActual,dfError
    REAL(prec) :: maxErrors(1:nvar)
    INTEGER :: iel,i,j,k,ivar,iside
    error = 0
    IF (dForm == selfStrongForm ) THEN
      msg = 'Formulation Type : Strong Form'
    ELSEIF (dForm == selfWeakDGForm ) THEN
      msg = 'Formulation Type : Weak DG Form'
    ELSEIF (dForm == selfWeakCGForm ) THEN
      msg = 'Formulation Type : Weak CG Form'
    ENDIF
    INFO(TRIM(msg))
    msg = 'Number of elements : '//Int2Str(nElem)
    msg = 'Number of elements : '//Int2Str(nElem*nElem*nElem)
    INFO(TRIM(msg))
    msg = 'Number of control points : '//Int2Str(cqDegree)
    INFO(TRIM(msg))
    msg = 'Number of target points : '//Int2Str(tqDegree)
    INFO(TRIM(msg))
    msg = 'Number of variables : '//Int2Str(nvar)
    INFO(TRIM(msg))
    msg = 'Error tolerance : '//Float2Str(tolerance)
    INFO(TRIM(msg))
    ! Create the control mesh and geometry
    CALL controlMesh % UniformBlockMesh(cqDegree, &
                                        (/nElem,nElem,nElem/), &
                                        (/0.0_prec,1.0_prec, &
                                          0.0_prec,1.0_prec, &
                                          0.0_prec,1.0_prec/))
    CALL controlGeometry % GenerateFromMesh(controlMesh,cqType,tqType,cqDegree,tqDegree)
    ! Create the scalar1d objects
    CALL f % Init(cqDegree,cqType,tqDegree,tqType,nvar,controlGeometry % nElem)
    CALL workTensor % Init(cqDegree,cqType,tqDegree,tqType,nvar,controlGeometry % nElem)
    CALL dfInterp % Init(cqDegree,cqType,tqDegree,tqType,nvar,controlGeometry % nElem)
    CALL dfActual % Init(cqDegree,cqType,tqDegree,tqType,nvar,controlGeometry % nElem)
    CALL dfError % Init(cqDegree,cqType,tqDegree,tqType,nvar,controlGeometry % nElem)
    ! Create the equation parser object
    feq = EquationParser(fChar, (/'x','y','z'/))
    gxeq = EquationParser(gradientChar(1), (/'x','y','z'/))
    gyeq = EquationParser(gradientChar(2), (/'x','y','z'/))
    gzeq = EquationParser(gradientChar(3), (/'x','y','z'/))
    ! Load the control function
    DO iel = 1, controlGeometry % nElem
      DO ivar = 1, nvar
        DO k = 0, cqDegree
          DO j = 0, cqDegree
            DO i = 0, cqDegree
              f % interior % hostData(i,j,k,ivar,iel) = &
                feq % Evaluate( controlGeometry % x % interior % hostData(1:3,i,j,k,1,iel) )
              dfActual % interior % hostData(1,i,j,k,ivar,iel) = &
                gxeq % Evaluate( controlGeometry % x % interior % hostData(1:3,i,j,k,1,iel) )
              dfActual % interior % hostData(2,i,j,k,ivar,iel) = &
                gyeq % Evaluate( controlGeometry % x % interior % hostData(1:3,i,j,k,1,iel) )
              dfActual % interior % hostData(3,i,j,k,ivar,iel) = &
                gzeq % Evaluate( controlGeometry % x % interior % hostData(1:3,i,j,k,1,iel) )
            ENDDO
            DO iside = 1,6
             f % boundary % hostData(j,k,ivar,iside,iel) = &
               feq % Evaluate( controlGeometry % x % boundary % hostData(1:3,j,k,1,iside,iel) )
            ENDDO
          ENDDO
        ENDDO
      ENDDO
    ENDDO
#ifdef GPU
    IF (gpuAccel) THEN
      CALL f % UpdateDevice()
    END IF
#endif
    ! Run the grid interpolation
    CALL f % Gradient(workTensor,controlGeometry,dfInterp,dForm,gpuAccel)
#ifdef GPU
    IF (gpuAccel) THEN
      CALL dfInterp % UpdateHost()
    END IF
#endif
    dfError = dfActual - dfInterp
    ! Calculate Absolute Maximum Error
    maxErrors = dfError % AbsMaxInterior( )
    msg = "Numerical Error : "//Float2Str(maxErrors(1))
    IF (maxErrors(1) > tolerance) THEN
      error = error + 1
      ERROR(TRIM(msg))
      ERROR("Status : [FAIL]")
    ELSE
      INFO(TRIM(msg))
      INFO("Status : [PASS]")
    END IF
    ! Clean up
    CALL controlMesh % Free()
    CALL controlGeometry % Free()
    CALL f % Free()
    CALL workTensor % Free()
    CALL dfInterp % Free()
    CALL dfActual % Free()
    CALL dfError % Free()
  END SUBROUTINE ScalarGradient3D_Test
Call graph
scalargradient3d_test calls float2str, int2str, info, equationparser
self calls scalargradient3d_test