ScalarBoundaryInterp3D_Test – Fortran Program
ScalarBoundaryInterp3D_Test Subroutine
80 statements
Source File
public subroutine ScalarBoundaryInterp3D_Test(cqType, tqType, cqDegree, tqDegree, nElem, nVar, functionChar, tolerance, gpuAccel, error)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: cqType
integer, intent(in) :: tqType
integer, intent(in) :: cqDegree
integer, intent(in) :: tqDegree
integer, intent(in) :: nElem
integer, intent(in) :: nVar
character(len=*), intent(in) :: functionChar
real(kind=prec), intent(in) :: tolerance
logical, intent(in) :: gpuAccel
integer, intent(out) :: error
Calls
Called by
Contents
None
Call graph
scalarboundaryinterp3d_test calls equationparser, info, float2str, int2str
self calls scalarboundaryinterp3d_test