ScalarGradient2D_Test – Fortran Program
ScalarGradient2D_Test Subroutine
93 statements
Source File
public subroutine ScalarGradient2D_Test(cqType, tqType, cqDegree, tqDegree, dForm, nElem, nVar, fChar, gradientChar, tolerance, gpuAccel, error)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: cqType
integer, intent(in) :: tqType
integer, intent(in) :: cqDegree
integer, intent(in) :: tqDegree
integer, intent(in) :: dForm
integer, intent(in) :: nElem
integer, intent(in) :: nVar
character(len=*), intent(in) :: fChar
character(len=240), intent(in) :: gradientChar(1:2)
real(kind=prec), intent(in) :: tolerance
logical, intent(in) :: gpuAccel
integer, intent(out) :: error
Calls
Contents
None
Call graph
scalargradient2d_test calls equationparser, info, float2str, int2str