TensorBoundaryInterp3D_Test – SELF
TensorBoundaryInterp3D_Test Subroutine
93 statements
Source File
public subroutine TensorBoundaryInterp3D_Test(cqType, tqType, cqDegree, tqDegree, nElem, nVar, tensorChar, tolerance, gpuAccel, error)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: cqType
integer, intent(in) :: tqType
integer, intent(in) :: cqDegree
integer, intent(in) :: tqDegree
integer, intent(in) :: nElem
integer, intent(in) :: nVar
character(len=240), intent(in) :: tensorChar(1:3,1:3)
real(kind=prec), intent(in) :: tolerance
logical, intent(in) :: gpuAccel
integer, intent(out) :: error
Calls
Called by
Contents
Source Code
TensorBoundaryInterp3D_Test
Source Code
  SUBROUTINE TensorBoundaryInterp3D_Test(cqType,tqType,cqDegree,tqDegree,nElem,nvar,&
                                         tensorChar,tolerance,gpuAccel,error)
#undef __FUNC__
#define __FUNC__ "TensorBoundaryInterp3D_Test"
    IMPLICIT NONE
    INTEGER,INTENT(in) :: cqType
    INTEGER,INTENT(in) :: tqType
    INTEGER,INTENT(in) :: cqDegree
    INTEGER,INTENT(in) :: tqDegree
    INTEGER,INTENT(in) :: nElem
    INTEGER,INTENT(in) :: nVar
    CHARACTER(240),INTENT(in) :: tensorChar(1:3,1:3)
    REAL(prec),INTENT(in) :: tolerance
    LOGICAL,INTENT(in) :: gpuAccel
    INTEGER,INTENT(out) :: error
    ! Local
    CHARACTER(240) :: msg
    TYPE(Mesh3D) :: controlMesh
    TYPE(SEMHex) :: controlGeometry
    TYPE(EquationParser)  :: tensorEq(1:3,1:3)
    TYPE(Tensor3D) :: f,fInterp,fActual,fError
    REAL(prec) :: maxErrors(1:nvar,1:6)
    INTEGER :: nel,iel
    INTEGER :: i,j,k,ivar,iside
    INTEGER :: row,col
    nel = nElem*nElem*nElem
    error = 0
    msg = 'Number of elements : '//Int2Str(nEl)
    INFO(TRIM(msg))
    msg = 'Number of control points : '//Int2Str(cqDegree)
    INFO(TRIM(msg))
    msg = 'Number of target points : '//Int2Str(tqDegree)
    INFO(TRIM(msg))
    msg = 'Number of variables : '//Int2Str(nvar)
    INFO(TRIM(msg))
    msg = 'Error tolerance : '//Float2Str(tolerance)
    INFO(TRIM(msg))
    ! Create the control mesh and geometry
    CALL controlMesh % UniformBlockMesh(cqDegree, &
                                        (/nElem,nElem,nElem/), &
                                        (/0.0_prec,1.0_prec, &
                                          0.0_prec,1.0_prec, &
                                          0.0_prec,1.0_prec/))
    CALL controlGeometry % GenerateFromMesh(controlMesh,cqType,tqType,cqDegree,tqDegree)
    ! Create the scalar1d objects
    CALL f % Init(cqDegree,cqType,tqDegree,tqType,nvar,nEl)
    CALL fActual % Init(cqDegree,cqType,tqDegree,tqType,nvar,nEl)
    CALL fError % Init(cqDegree,cqType,tqDegree,tqType,nvar,nEl)
    ! Create the equation parser object
    DO col = 1,3
      DO row = 1,3
        tensorEq(row,col) = EquationParser(TRIM(tensorChar(row,col)), (/'x','y','z'/))
      ENDDO
    ENDDO
    ! Load the control function
    DO iel = 1, nel
      DO ivar = 1, nvar
        DO k = 0, cqDegree
          DO j = 0, cqDegree
            DO i = 0, cqDegree
              DO col = 1,3
                DO row = 1,3
                  f % interior % hostData(row,col,i,j,k,ivar,iel) = &
                    tensorEq(row,col) % Evaluate( controlGeometry % x % interior % hostData(1:3,i,j,k,1,iel) )
                ENDDO
              ENDDO
            ENDDO
            DO iside = 1,6
              DO col = 1,3
                DO row = 1,3
                  fActual % boundary % hostData(row,col,j,k,ivar,iside,iel) = &
                    tensorEq(row,col) % Evaluate( controlGeometry % x % boundary % hostData(1:3,j,k,1,iside,iel) )
                ENDDO
              ENDDO
            ENDDO
          ENDDO
        ENDDO
      ENDDO
    ENDDO
#ifdef GPU
    IF (gpuAccel) THEN
      CALL f % UpdateDevice()
    END IF
#endif
    ! Run the grid interpolation
     CALL f % BoundaryInterp(gpuAccel)
#ifdef GPU
    IF (gpuAccel) THEN
      CALL f % UpdateHost()
    END IF
#endif
    fError = fActual - f
    ! Calculate Absolute Maximum Error
    maxErrors = fError % AbsMaxBoundary( )
    DO iside = 1,6
      msg = "Numerical Error : "//TRIM(Int2Str(iSide))//Float2Str(maxErrors(1,iSide))
      IF (maxErrors(1,iSide) > tolerance) THEN
        error = error + 1
        ERROR(TRIM(msg))
        msg = "Status : [FAIL]"
        ERROR(TRIM(msg))
      ELSE
        INFO(TRIM(msg))
        msg = "Status : [PASS]"
        INFO(TRIM(msg))
      END IF
    ENDDO
    ! Clean up
    CALL controlMesh % Free()
    CALL controlGeometry % Free()
    CALL f % Free()
    CALL fActual % Free()
    CALL fError % Free()
  END SUBROUTINE TensorBoundaryInterp3D_Test
Call graph
tensorboundaryinterp3d_test calls int2str, equationparser, float2str, info
self calls tensorboundaryinterp3d_test