UpdateHost_hfReal_r6 – SELF
UpdateHost_hfReal_r6 Subroutine
Anti-Capitalist Software License
7 statements
Source File
public subroutine UpdateHost_hfReal_r6(this)
Arguments
Type Intent Optional Attributes Name
class(hfReal_r6), intent(inout) :: this
Calls
Contents
Source Code
UpdateHost_hfReal_r6
Source Code
  SUBROUTINE UpdateHost_hfReal_r6(this)
    IMPLICIT NONE
    CLASS(hfReal_r6),INTENT(inout) :: this
    IF (GPUAvailable()) THEN
      CALL hipCheck(hipMemcpy(c_loc(this % hostData), &
                              this % deviceData, &
                              SIZEOF(this % hostData), &
                              hipMemcpyDeviceToHost))
    END IF
  END SUBROUTINE UpdateHost_hfReal_r6
Call graph
updatehost_hfreal_r6 calls hipmemcpy, hipcheck, gpuavailable
gpuavailable calls hipgetdevicecount