VectorDivergence2D_Test – SELF
VectorDivergence2D_Test Subroutine
97 statements
Source File
public subroutine VectorDivergence2D_Test(cqType, tqType, cqDegree, tqDegree, dForm, nElem, nVar, vectorChar, scalarChar, tolerance, gpuAccel, error)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: cqType
integer, intent(in) :: tqType
integer, intent(in) :: cqDegree
integer, intent(in) :: tqDegree
integer, intent(in) :: dForm
integer, intent(in) :: nElem
integer, intent(in) :: nVar
character(len=240), intent(in) :: vectorChar(1:2)
character(len=240), intent(in) :: scalarChar
real(kind=prec), intent(in) :: tolerance
logical, intent(in) :: gpuAccel
integer, intent(out) :: error
Calls
Contents
Source Code
VectorDivergence2D_Test
Source Code
  SUBROUTINE VectorDivergence2D_Test(cqType,tqType,cqDegree,tqDegree,dForm,nElem,nvar,&
                                     vectorChar,scalarChar,tolerance,gpuAccel,error)
#undef __FUNC__
#define __FUNC__ "VectorDivergence2D_Test"
    IMPLICIT NONE
    INTEGER,INTENT(in) :: cqType
    INTEGER,INTENT(in) :: tqType
    INTEGER,INTENT(in) :: cqDegree
    INTEGER,INTENT(in) :: tqDegree
    INTEGER,INTENT(in) :: dForm
    INTEGER,INTENT(in) :: nElem
    INTEGER,INTENT(in) :: nVar
    CHARACTER(240),INTENT(in) :: vectorChar(1:2)
    CHARACTER(240),INTENT(in) :: scalarChar
    REAL(prec),INTENT(in) :: tolerance
    LOGICAL,INTENT(in) :: gpuAccel
    INTEGER,INTENT(out) :: error
    ! Local
    CHARACTER(240) :: msg
    TYPE(Mesh2D) :: controlMesh
    TYPE(SEMQuad) :: controlGeometry
    TYPE(EquationParser)  :: feq(1:2),dfeqChar
    TYPE(MappedVector2D) :: f
    TYPE(MappedVector2D) :: workVector
    TYPE(MappedScalar2D) :: dfInterp,dfActual,dfError
    REAL(prec) :: maxErrors(1:nvar)
    INTEGER :: iel,i,j,ivar,row,col,iside
    error = 0
    IF (dForm == selfStrongForm ) THEN
      msg = 'Formulation Type : Strong Form'
    ELSEIF (dForm == selfWeakDGForm ) THEN
      msg = 'Formulation Type : Weak DG Form'
    ELSEIF (dForm == selfWeakCGForm ) THEN
      msg = 'Formulation Type : Weak CG Form'
    ENDIF
    INFO(TRIM(msg))
    msg = 'Number of elements : '//Int2Str(nElem)
    msg = 'Number of elements : '//Int2Str(nElem*nElem)
    INFO(TRIM(msg))
    msg = 'Number of control points : '//Int2Str(cqDegree)
    INFO(TRIM(msg))
    msg = 'Number of target points : '//Int2Str(tqDegree)
    INFO(TRIM(msg))
    msg = 'Number of variables : '//Int2Str(nvar)
    INFO(TRIM(msg))
    msg = 'Error tolerance : '//Float2Str(tolerance)
    INFO(TRIM(msg))
    ! Create the control mesh and geometry
    CALL controlMesh % UniformBlockMesh(cqDegree, &
                                        (/nElem,nElem/), &
                                        (/0.0_prec,1.0_prec, &
                                          0.0_prec,1.0_prec/))
    CALL controlGeometry % GenerateFromMesh(controlMesh,cqType,tqType,cqDegree,tqDegree)
    ! Create the scalar1d objects
    CALL f % Init(cqDegree,cqType,tqDegree,tqType,nvar,controlGeometry % nElem)
    CALL dfInterp % Init(cqDegree,cqType,tqDegree,tqType,nvar,controlGeometry % nElem)
    CALL dfActual % Init(cqDegree,cqType,tqDegree,tqType,nvar,controlGeometry % nElem)
    CALL dfError % Init(cqDegree,cqType,tqDegree,tqType,nvar,controlGeometry % nElem)
    ! Create work objects
    CALL workVector % Init(cqDegree,cqType,tqDegree,tqType,nvar,controlGeometry % nElem)
    ! Create the equation parser object
    DO row = 1, 2
      feq(row) = EquationParser(vectorChar(row), (/'x','y'/))
    ENDDO
    dfeqChar = EquationParser(scalarChar, (/'x','y'/))
    ! Load the control function
    DO iel = 1, controlGeometry % nElem
      DO ivar = 1, nvar
        DO j = 0, cqDegree
          DO i = 0, cqDegree
            DO row = 1,2
              f % interior % hostData(row,i,j,ivar,iel) = &
                feq(row) % Evaluate( controlGeometry % x % interior % hostData(1:2,i,j,1,iel) )
            ENDDO
            dfActual % interior % hostData(i,j,ivar,iel) = &
              dfeqChar % Evaluate( controlGeometry % x % interior % hostData(1:2,i,j,1,iel) )
          ENDDO
          DO iside = 1,4
            DO row = 1,2
              f % boundary % hostData(row,j,ivar,iside,iel) = &
                feq(row) % Evaluate( controlGeometry % x % boundary % hostData(1:2,j,1,iside,iel) )
            ENDDO
          ENDDO
        ENDDO
      ENDDO
    ENDDO
#ifdef GPU
    IF (gpuAccel) THEN
      CALL f % UpdateDevice()
    END IF
#endif
    ! Run the grid interpolation
    CALL f % Divergence(workVector,controlGeometry,dfInterp,dForm,gpuAccel)
#ifdef GPU
    IF (gpuAccel) THEN
      CALL dfInterp % UpdateHost( )
    END IF
#endif
    dfError = dfActual - dfInterp
    ! Calculate Absolute Maximum Error
    maxErrors = dfError % AbsMaxInterior( )
    msg = "Numerical Error : "//Float2Str(maxErrors(1))
    IF (maxErrors(1) > tolerance) THEN
      error = error + 1
      ERROR(TRIM(msg))
      ERROR("Status : [FAIL]")
    ELSE
      INFO(TRIM(msg))
      INFO("Status : [PASS]")
    END IF
    ! Clean up
    CALL controlMesh % Free()
    CALL controlGeometry % Free()
    CALL f % Free()
    CALL workVector % Free()
    CALL dfInterp % Free()
    CALL dfActual % Free()
    CALL dfError % Free()
  END SUBROUTINE VectorDivergence2D_Test
Call graph
vectordivergence2d_test calls int2str, info, equationparser, float2str