VectorBoundaryInterp2D_Test – SELF
VectorBoundaryInterp2D_Test Subroutine
84 statements
Source File
public subroutine VectorBoundaryInterp2D_Test(cqType, tqType, cqDegree, tqDegree, nElem, nVar, vectorChar, tolerance, gpuAccel, error)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: cqType
integer, intent(in) :: tqType
integer, intent(in) :: cqDegree
integer, intent(in) :: tqDegree
integer, intent(in) :: nElem
integer, intent(in) :: nVar
character(len=240), intent(in) :: vectorChar(1:2)
real(kind=prec), intent(in) :: tolerance
logical, intent(in) :: gpuAccel
integer, intent(out) :: error
Calls
Contents
Source Code
VectorBoundaryInterp2D_Test
Source Code
  SUBROUTINE VectorBoundaryInterp2D_Test(cqType,tqType,cqDegree,tqDegree,nElem,nvar,&
                                         vectorChar,tolerance,gpuAccel,error)
#undef __FUNC__
#define __FUNC__ "VectorBoundaryInterp2D_Test"
    IMPLICIT NONE
    INTEGER,INTENT(in) :: cqType
    INTEGER,INTENT(in) :: tqType
    INTEGER,INTENT(in) :: cqDegree
    INTEGER,INTENT(in) :: tqDegree
    INTEGER,INTENT(in) :: nElem
    INTEGER,INTENT(in) :: nVar
    CHARACTER(240),INTENT(in) :: vectorChar(1:2)
    REAL(prec),INTENT(in) :: tolerance
    LOGICAL,INTENT(in) :: gpuAccel
    INTEGER,INTENT(out) :: error
    ! Local
    CHARACTER(240) :: msg
    TYPE(Mesh2D) :: controlMesh
    TYPE(SEMQuad) :: controlGeometry
    TYPE(EquationParser)  :: vEq(1:2)
    TYPE(Vector2D) :: f,fActual,fError
    REAL(prec) :: maxErrors(1:nvar,1:4)
    INTEGER :: nel,iel,jel
    INTEGER :: i,j,ivar,iside,idir
    nel = nElem*nElem
    error = 0
    msg = 'Number of elements : '//Int2Str(nEl)
    INFO(TRIM(msg))
    msg = 'Number of control points : '//Int2Str(cqDegree)
    INFO(TRIM(msg))
    msg = 'Number of target points : '//Int2Str(tqDegree)
    INFO(TRIM(msg))
    msg = 'Number of variables : '//Int2Str(nvar)
    INFO(TRIM(msg))
    msg = 'Error tolerance : '//Float2Str(tolerance)
    INFO(TRIM(msg))
    ! Create the control mesh and geometry
    CALL controlMesh % UniformBlockMesh(cqDegree, &
                                        (/nElem,nElem/), &
                                        (/0.0_prec,1.0_prec, &
                                          0.0_prec,1.0_prec/))
    CALL controlGeometry % GenerateFromMesh(controlMesh,cqType,tqType,cqDegree,tqDegree)
    ! Create the scalar1d objects
    CALL f % Init(cqDegree,cqType,tqDegree,tqType,nvar,nEl)
    CALL fActual % Init(cqDegree,cqType,tqDegree,tqType,nvar,nEl)
    CALL fError % Init(cqDegree,cqType,tqDegree,tqType,nvar,nEl)
    ! Create the equation parser object
    DO idir = 1,2
      vEq(idir) = EquationParser(vectorChar(idir), (/'x','y'/))
    ENDDO
    ! Load the control function
    DO iel = 1, nel
      DO ivar = 1, nvar
        DO j = 0, cqDegree
          DO i = 0, cqDegree
            DO idir = 1,2
              f % interior % hostData(idir,i,j,ivar,iel) = &
                vEq(idir) % Evaluate( controlGeometry % x % interior % hostData(1:2,i,j,1,iel) )
            ENDDO
          ENDDO
          DO iside = 1,4
            DO idir = 1,2
              fActual % boundary % hostData(idir,j,ivar,iside,iel) = &
                vEq(idir) % Evaluate( controlGeometry % x % boundary % hostData(1:2,j,1,iside,iel) )
            ENDDO
          ENDDO
        ENDDO
      ENDDO
    ENDDO
    ! Run the grid interpolation
#ifdef GPU
    IF (gpuAccel) THEN
      CALL f % UpdateDevice()
    END IF
#endif
    CALL f % BoundaryInterp(gpuAccel)
#ifdef GPU
    IF (gpuAccel) THEN
      CALL f % UpdateHost()
    END IF
#endif
    fError = fActual - f
    ! Calculate Absolute Maximum Error
    maxErrors = fError % AbsMaxBoundary( )
    DO iside = 1,4
      msg = "Numerical Error : "//TRIM(Int2Str(iSide))//Float2Str(maxErrors(1,iSide))
      IF (maxErrors(1,iSide) > tolerance) THEN
        error = error + 1
        ERROR(TRIM(msg))
        msg = "Status : [FAIL]"
        ERROR(TRIM(msg))
      ELSE
        INFO(TRIM(msg))
        msg = "Status : [PASS]"
        INFO(TRIM(msg))
      END IF
    ENDDO
    ! Clean up
    CALL controlMesh % Free()
    CALL controlGeometry % Free()
    CALL f % Free()
    CALL fActual % Free()
    CALL fError % Free()
  END SUBROUTINE VectorBoundaryInterp2D_Test
Call graph
vectorboundaryinterp2d_test calls float2str, int2str, info, equationparser