WriteArray_HDF5_int32_r4_serial – SELF
WriteArray_HDF5_int32_r4_serial Subroutine
Anti-Capitalist Software License
18 statements
Source File
private subroutine WriteArray_HDF5_int32_r4_serial(fileId, arrayName, hfArray)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfint32_r4), intent(in) :: hfArray
Calls
Called by
Contents
Source Code
WriteArray_HDF5_int32_r4_serial
Source Code
  SUBROUTINE WriteArray_HDF5_int32_r4_serial(fileId,arrayName,hfArray)
    IMPLICIT NONE
    INTEGER(HID_T),INTENT(in) :: fileId
    CHARACTER(*),INTENT(in) :: arrayName
    TYPE(hfint32_r4),INTENT(in) :: hfArray
    ! Local
    INTEGER(HID_T) :: dsetId
    INTEGER(HID_T) :: memspace
    INTEGER(HSIZE_T) :: dims(1:4)
    INTEGER :: error
    INTEGER :: aRank
    aRank = RANK(hfArray % hostData)
    dims = SHAPE(hfArray % hostData)
    CALL h5screate_simple_f(aRank,dims,memspace,error)
    CALL h5dcreate_f(fileId,TRIM(arrayName),H5T_STD_I32LE,memspace, &
                     dsetId,error)
    CALL h5dwrite_f(dsetId,H5T_STD_I32LE, &
                    hfArray % hostData,dims,error)
    CALL h5dclose_f(dSetId,error)
    CALL h5sclose_f(memspace,error)
  END SUBROUTINE WriteArray_HDF5_int32_r4_serial
Call graph
writearray_hdf5_int32_r4_serial calls h5sclose_f, h5screate_simple_f, h5dcreate_f, h5dwrite_f, h5dclose_f
writearray_hdf5 calls writearray_hdf5_int32_r4_serial