Write_HOPr_Mesh2D – SELF
Write_HOPr_Mesh2D Subroutine
Anti-Capitalist Software License
16 statements
Source File
public subroutine Write_HOPr_Mesh2D(myMesh, meshFile)
Arguments
Type Intent Optional Attributes Name
class(Mesh2D), intent(inout) :: myMesh
character, intent(in) :: meshFile
Calls
Contents
Source Code
Write_HOPr_Mesh2D
Source Code
  SUBROUTINE Write_HOPr_Mesh2D(myMesh,meshFile)
    ! Writes mesh output in HOPR format (serial only)
    IMPLICIT NONE
    CLASS(Mesh2D),INTENT(inout) :: myMesh
    CHARACTER(*),INTENT(in) :: meshFile
    ! Local
    INTEGER(HID_T) :: fileId
    CALL Open_HDF5(meshFile,H5F_ACC_RDWR_F,fileId)
    CALL WriteAttribute_HDF5(fileId,'nElems',myMesh % nElem)
    CALL WriteAttribute_HDF5(fileId,'Ngeo',myMesh % nGeo)
    CALL WriteAttribute_HDF5(fileId,'nBCs',myMesh % nBCs)
    CALL WriteArray_HDF5(fileId,'BCType',myMesh % bcType)
    ! Write local subarray of ElemInfo
    CALL WriteArray_HDF5(fileId,'ElemInfo',myMesh % hopr_elemInfo)
    ! Write local subarray of NodeCoords and GlobalNodeIDs
    CALL WriteArray_HDF5(fileId,'NodeCoords',myMesh % hopr_nodeCoords)
    CALL WriteArray_HDF5(fileId,'GlobalNodeIDs',myMesh % hopr_globalNodeIDs)
    ! Write local subarray of SideInfo
    CALL WriteArray_HDF5(fileId,'SideInfo',myMesh % hopr_sideInfo)
    CALL Close_HDF5(fileID)
  END SUBROUTINE Write_HOPr_Mesh2D
Call graph
write_hopr_mesh2d calls writeattribute_hdf5, writearray_hdf5, close_hdf5, open_hdf5