steps:
  - label: ":partyparrot: Build & Test NVIDIA V100 (Coverage)"
    key: "build-test-v100"
    command: |
      source /opt/spack-environment/activate.sh
      export WORKSPACE=/workspace
      mkdir -p /workspace/build
      nvidia-smi
      cd /workspace/build
      FC=gfortran cmake -DCMAKE_INSTALL_PREFIX=/workspace/opt/self \
            -DCMAKE_BUILD_TYPE="coverage" \
            -DSELF_ENABLE_GPU=ON \
            -DSELF_GPU_BACKEND=CUDA \
            -DSELF_ENABLE_TESTING=ON \
            -DCMAKE_CUDA_ARCHITECTURES="70" \
            -DSELF_ENABLE_EXAMPLES=ON \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
            /workspace/
      make -j
      lcov --capture --initial \
           --directory /workspace/build/src/ \
           --output-file /workspace/initial.info
      ctest --test-dir /workspace/build --output-on-failure
      lcov --capture \
           --directory /workspace/build/src/ \
           --output-file /workspace/ctest-capture.info
      lcov --add-tracefile /workspace/initial.info \
           --add-tracefile /workspace/ctest-capture.info \
           --output-file /workspace/coverage.info
    env:
      slurm_partition: "main"
      slurm_gres: "gpu:v100:2"
      slurm_time: "01:00:00"
      slurm_nodes: 1
      slurm_ntasks: 2
      slurm_cpus_per_task: 8
      slurm_container_image: "docker://higherordermethods/selfish:latest-x86-cuda124-sm70"
    agents:
      queue: "galapagos"

  - label: ":codecov: Upload Coverage (V100)"
    key: "upload-coverage-v100"
    depends_on: "build-test-v100"
    command: |
      curl -Os https://uploader.codecov.io/latest/linux/codecov
      chmod +x codecov
      ./codecov -t "$${CODECOV_TOKEN}" \
                -f "$${BUILDKITE_BUILD_CHECKOUT_PATH}/coverage.info" \
                -F buildkite-cuda-v100
    secrets:
      - CODECOV_TOKEN
    agents:
      queue: "galapagos"
