steps:
  - label: ":pipeline: AMD MI210 Debug Tests"
    command: buildkite-agent pipeline upload .buildkite/amd-mi210-debug-tests.yml

  - label: ":pipeline: NVIDIA V100 Debug Tests"
    command: buildkite-agent pipeline upload .buildkite/nvidia-v100-debug-tests.yml
