#!/bin/bash

# Compilers
export FC=pgfortran
export MPIFC=mpif90
#export MPIFC=${HOME}/pgi_mpi_withcuda/bin/mpif90

# Parallelization schemes
export CUDA=yes
export GPU_ARCH=cc60
export DUAL_GPU=yes
export CUDA_DIRECT=no

export MPI=yes
export MPI_LIB=
export MPI_INC=
#export MPI_LIB="-L${HOME}/pgi_mpi_withcuda/lib -lmpi"
#export MPI_INC="-I${HOME}/pgi_mpi_withcuda/include" 

export OMP=no

# SELF Features

export INSITU_VIZ=no
#export LIBSIM_LIB="-L${HOME}/visit/2.9.0/linux-x86_64/libsim/V2/lib/ -lsimV2f -lsimV2 -ldl"
#export LIBSIM_INC="-I${HOME}/visit/2.9.0/linux-x86_64/libsim/V2/include/"
export LIBSIM_LIB="-L${HOME}/Software/visit/visit2.12.0/src/lib/ -lsimV2f -lsimV2 -ldl"
export LIBSIM_INC="-I${HOME}/Software/visit/visit2.12.0/src/sim/V2/lib/"

export DEBUG=no

export TIMING=yes
export DIAGNOSTICS=yes
