blank_issues_enabled: false
contact_links:
  - name: Fluid Numerics Community Support
    url: https://octoskelo.atlassian.net/servicedesk/customer/portal/1
  - name: Fluid Numerics Security Vulnerability Reporting
    url: https://octoskelo.atlassian.net/servicedesk/customer/portal/1/group/47/create/151
  - name: Fluid Numerics Software Services
    url: https://octoskelo.atlassian.net/servicedesk/customer/portal/6
