# In this directory, run the following command to build this builder.
# $ gcloud builds submit .
steps:

- id: GNU Dependency Container Image
  name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t', 'gcr.io/${PROJECT_ID}/gnu:latest', 'gnu/']
  waitFor: ["-"]

- id: GNU+MVAPICH Dependency Container Image
  name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t', 'gcr.io/${PROJECT_ID}/gnu-mvapich:latest', 'gnu-mvapich/']
  waitFor: ["-"]

- id: GNU+OpenMPI Dependency Container Image
  name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t', 'gcr.io/${PROJECT_ID}/gnu-openmpi:latest', 'gnu-openmpi/']
  waitFor: ["-"]

- id: PGI Dependency Container Image
  name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t', 'gcr.io/${PROJECT_ID}/pgi:latest', 'pgi/']
  waitFor: ["-"]

- id: PGI+MVAPICH Dependency Container Image
  name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t', 'gcr.io/${PROJECT_ID}/pgi-mvapich:latest', 'pgi-mvapich/']
  waitFor: ["-"]

- id: PGI+OpenMPI Dependency Container Image
  name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t', 'gcr.io/${PROJECT_ID}/pgi-openmpi:latest', 'pgi-openmpi/']
  waitFor: ["-"]


images: ['gcr.io/${PROJECT_ID}/gnu',
         'gcr.io/${PROJECT_ID}/gnu-mvapich',
         'gcr.io/${PROJECT_ID}/gnu-openmpi',
         'gcr.io/${PROJECT_ID}/pgi',
         'gcr.io/${PROJECT_ID}/pgi-mvapich',
         'gcr.io/${PROJECT_ID}/pgi-openmpi']

timeout : 7200s
options : 
  machineType : N1_HIGHCPU_32
