
steps:
        # Add a step for formatting requirements

        - id: Build Docker Image
          name: gcr.io/cloud-builders/docker
          args: ['build',
                 '--build-arg','BUILD_TYPE=${_BUILD_TYPE}',
                 '-f','docker/Dockerfile.${_PLATFORM}',
                 '.',
                 '-t',
                 'gcr.io/self-fluids/self_${_PLATFORM}:${_IMAGE_TAG}'
          ]

        - id: Run CI Tests
          name: gcr.io/cloud-builders/docker
          args: 
          - run
          - -v
          - "/workspace:/workspace"
          - --env 
          - WORKSPACE=/workspace
          - --entrypoint
          - /usr/bin/python3
          - gcr.io/self-fluids/self_${_PLATFORM}:${_IMAGE_TAG}
          - /opt/self/test/ciRun.py
          
      
# Check for zero exit codes

# Check for correctness
  


images: ['gcr.io/self-fluids/self_${_PLATFORM}:${_IMAGE_TAG}']

timeout: 7200s

substitutions:
        _IMAGE_TAG: 'dev'
        _BUILD_TYPE: 'dev'
        _PLATFORM: 'serial-x86'
