ReadArray_HDF5 – SELF
ReadArray_HDF5 Interface
Anti-Capitalist Software License
44 statements
Source File
public interface ReadArray_HDF5
Calls
Contents
Module Procedures
ReadArray_HDF5_real_r1_serial ReadArray_HDF5_real_r2_serial ReadArray_HDF5_real_r3_serial ReadArray_HDF5_real_r4_serial ReadArray_HDF5_real_r5_serial ReadArray_HDF5_real_r6_serial ReadArray_HDF5_real_r7_serial ReadArray_HDF5_int32_r1_serial ReadArray_HDF5_int32_r2_serial ReadArray_HDF5_int32_r3_serial ReadArray_HDF5_int32_r4_serial ReadArray_HDF5_int32_r5_serial ReadArray_HDF5_int32_r6_serial ReadArray_HDF5_int32_r7_serial ReadArray_HDF5_int64_r1_serial ReadArray_HDF5_int64_r2_serial ReadArray_HDF5_int64_r3_serial ReadArray_HDF5_int64_r4_serial ReadArray_HDF5_int64_r5_serial ReadArray_HDF5_int64_r6_serial ReadArray_HDF5_int64_r7_serial ReadArray_HDF5_real_r1_parallel ReadArray_HDF5_real_r2_parallel ReadArray_HDF5_real_r3_parallel ReadArray_HDF5_real_r4_parallel ReadArray_HDF5_real_r5_parallel ReadArray_HDF5_real_r6_parallel ReadArray_HDF5_real_r7_parallel ReadArray_HDF5_int32_r1_parallel ReadArray_HDF5_int32_r2_parallel ReadArray_HDF5_int32_r3_parallel ReadArray_HDF5_int32_r4_parallel ReadArray_HDF5_int32_r5_parallel ReadArray_HDF5_int32_r6_parallel ReadArray_HDF5_int32_r7_parallel ReadArray_HDF5_int64_r1_parallel ReadArray_HDF5_int64_r2_parallel ReadArray_HDF5_int64_r3_parallel ReadArray_HDF5_int64_r4_parallel ReadArray_HDF5_int64_r5_parallel ReadArray_HDF5_int64_r6_parallel ReadArray_HDF5_int64_r7_parallel
Module Procedures
private subroutine ReadArray_HDF5_real_r1_serial(fileId, arrayName, hfArray)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfReal_r1), intent(inout) :: hfArray
private subroutine ReadArray_HDF5_real_r2_serial(fileId, arrayName, hfArray)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfReal_r2), intent(inout) :: hfArray
private subroutine ReadArray_HDF5_real_r3_serial(fileId, arrayName, hfArray)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfReal_r3), intent(inout) :: hfArray
private subroutine ReadArray_HDF5_real_r4_serial(fileId, arrayName, hfArray)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfReal_r4), intent(inout) :: hfArray
private subroutine ReadArray_HDF5_real_r5_serial(fileId, arrayName, hfArray)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfReal_r5), intent(inout) :: hfArray
private subroutine ReadArray_HDF5_real_r6_serial(fileId, arrayName, hfArray)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfReal_r6), intent(inout) :: hfArray
private subroutine ReadArray_HDF5_real_r7_serial(fileId, arrayName, hfArray)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfReal_r7), intent(inout) :: hfArray
private subroutine ReadArray_HDF5_int32_r1_serial(fileId, arrayName, hfArray)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfInt32_r1), intent(inout) :: hfArray
private subroutine ReadArray_HDF5_int32_r2_serial(fileId, arrayName, hfArray)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfInt32_r2), intent(inout) :: hfArray
private subroutine ReadArray_HDF5_int32_r3_serial(fileId, arrayName, hfArray)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfInt32_r3), intent(inout) :: hfArray
private subroutine ReadArray_HDF5_int32_r4_serial(fileId, arrayName, hfArray)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfInt32_r4), intent(inout) :: hfArray
private subroutine ReadArray_HDF5_int32_r5_serial(fileId, arrayName, hfArray)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfInt32_r5), intent(inout) :: hfArray
private subroutine ReadArray_HDF5_int32_r6_serial(fileId, arrayName, hfArray)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfInt32_r6), intent(inout) :: hfArray
private subroutine ReadArray_HDF5_int32_r7_serial(fileId, arrayName, hfArray)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfInt32_r7), intent(inout) :: hfArray
private subroutine ReadArray_HDF5_int64_r1_serial(fileId, arrayName, hfArray)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfInt64_r1), intent(inout) :: hfArray
private subroutine ReadArray_HDF5_int64_r2_serial(fileId, arrayName, hfArray)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfInt64_r2), intent(inout) :: hfArray
private subroutine ReadArray_HDF5_int64_r3_serial(fileId, arrayName, hfArray)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfInt64_r3), intent(inout) :: hfArray
private subroutine ReadArray_HDF5_int64_r4_serial(fileId, arrayName, hfArray)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfInt64_r4), intent(inout) :: hfArray
private subroutine ReadArray_HDF5_int64_r5_serial(fileId, arrayName, hfArray)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfInt64_r5), intent(inout) :: hfArray
private subroutine ReadArray_HDF5_int64_r6_serial(fileId, arrayName, hfArray)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfInt64_r6), intent(inout) :: hfArray
private subroutine ReadArray_HDF5_int64_r7_serial(fileId, arrayName, hfArray)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfInt64_r7), intent(inout) :: hfArray
private subroutine ReadArray_HDF5_real_r1_parallel(fileId, arrayName, hfArray, offset)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfReal_r1), intent(inout) :: hfArray
integer(kind=HID_T), intent(in) :: offset(1)
private subroutine ReadArray_HDF5_real_r2_parallel(fileId, arrayName, hfArray, offset)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfReal_r2), intent(inout) :: hfArray
integer(kind=HID_T), intent(in) :: offset(1:2)
private subroutine ReadArray_HDF5_real_r3_parallel(fileId, arrayName, hfArray, offset)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfReal_r3), intent(inout) :: hfArray
integer(kind=HID_T), intent(in) :: offset(1:3)
private subroutine ReadArray_HDF5_real_r4_parallel(fileId, arrayName, hfArray, offset)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfReal_r4), intent(inout) :: hfArray
integer(kind=HID_T), intent(in) :: offset(1:4)
private subroutine ReadArray_HDF5_real_r5_parallel(fileId, arrayName, hfArray, offset)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfReal_r5), intent(inout) :: hfArray
integer(kind=HID_T), intent(in) :: offset(1:5)
private subroutine ReadArray_HDF5_real_r6_parallel(fileId, arrayName, hfArray, offset)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfReal_r6), intent(inout) :: hfArray
integer(kind=HID_T), intent(in) :: offset(1:6)
private subroutine ReadArray_HDF5_real_r7_parallel(fileId, arrayName, hfArray, offset)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfReal_r7), intent(inout) :: hfArray
integer(kind=HID_T), intent(in) :: offset(1:7)
private subroutine ReadArray_HDF5_int32_r1_parallel(fileId, arrayName, hfArray, offset)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfInt32_r1), intent(inout) :: hfArray
integer(kind=HID_T), intent(in) :: offset(1)
private subroutine ReadArray_HDF5_int32_r2_parallel(fileId, arrayName, hfArray, offset)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfInt32_r2), intent(inout) :: hfArray
integer(kind=HID_T), intent(in) :: offset(1:2)
private subroutine ReadArray_HDF5_int32_r3_parallel(fileId, arrayName, hfArray, offset)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfInt32_r3), intent(inout) :: hfArray
integer(kind=HID_T), intent(in) :: offset(1:3)
private subroutine ReadArray_HDF5_int32_r4_parallel(fileId, arrayName, hfArray, offset)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfInt32_r4), intent(inout) :: hfArray
integer(kind=HID_T), intent(in) :: offset(1:4)
private subroutine ReadArray_HDF5_int32_r5_parallel(fileId, arrayName, hfArray, offset)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfInt32_r5), intent(inout) :: hfArray
integer(kind=HID_T), intent(in) :: offset(1:5)
private subroutine ReadArray_HDF5_int32_r6_parallel(fileId, arrayName, hfArray, offset)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfInt32_r6), intent(inout) :: hfArray
integer(kind=HID_T), intent(in) :: offset(1:6)
private subroutine ReadArray_HDF5_int32_r7_parallel(fileId, arrayName, hfArray, offset)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfInt32_r7), intent(inout) :: hfArray
integer(kind=HID_T), intent(in) :: offset(1:7)
private subroutine ReadArray_HDF5_int64_r1_parallel(fileId, arrayName, hfArray, offset)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfInt64_r1), intent(inout) :: hfArray
integer(kind=HID_T), intent(in) :: offset(1)
private subroutine ReadArray_HDF5_int64_r2_parallel(fileId, arrayName, hfArray, offset)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfInt64_r2), intent(inout) :: hfArray
integer(kind=HID_T), intent(in) :: offset(1:2)
private subroutine ReadArray_HDF5_int64_r3_parallel(fileId, arrayName, hfArray, offset)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfInt64_r3), intent(inout) :: hfArray
integer(kind=HID_T), intent(in) :: offset(1:3)
private subroutine ReadArray_HDF5_int64_r4_parallel(fileId, arrayName, hfArray, offset)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfInt64_r4), intent(inout) :: hfArray
integer(kind=HID_T), intent(in) :: offset(1:4)
private subroutine ReadArray_HDF5_int64_r5_parallel(fileId, arrayName, hfArray, offset)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfInt64_r5), intent(inout) :: hfArray
integer(kind=HID_T), intent(in) :: offset(1:5)
private subroutine ReadArray_HDF5_int64_r6_parallel(fileId, arrayName, hfArray, offset)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfInt64_r6), intent(inout) :: hfArray
integer(kind=HID_T), intent(in) :: offset(1:6)
private subroutine ReadArray_HDF5_int64_r7_parallel(fileId, arrayName, hfArray, offset)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfInt64_r7), intent(inout) :: hfArray
integer(kind=HID_T), intent(in) :: offset(1:7)
Call graph
readarray_hdf5 calls readarray_hdf5_int32_r7_serial, readarray_hdf5_int64_r1_parallel, readarray_hdf5_real_r1_serial, readarray_hdf5_real_r2_serial, readarray_hdf5_int32_r3_parallel, readarray_hdf5_int32_r2_serial, readarray_hdf5_int32_r2_parallel, readarray_hdf5_int64_r5_serial, readarray_hdf5_int32_r7_parallel, readarray_hdf5_int32_r4_parallel, readarray_hdf5_int64_r2_serial, readarray_hdf5_real_r4_parallel, readarray_hdf5_int64_r3_parallel, readarray_hdf5_int32_r4_serial, readarray_hdf5_int64_r7_parallel, readarray_hdf5_real_r5_serial, readarray_hdf5_int64_r1_serial, readarray_hdf5_real_r4_serial, readarray_hdf5_int64_r6_parallel, readarray_hdf5_int32_r1_serial, readarray_hdf5_int64_r5_parallel, readarray_hdf5_int64_r6_serial, readarray_hdf5_real_r1_parallel, readarray_hdf5_int64_r3_serial, readarray_hdf5_int64_r4_parallel, readarray_hdf5_int32_r1_parallel, readarray_hdf5_real_r5_parallel, readarray_hdf5_int32_r6_parallel, readarray_hdf5_int32_r6_serial, readarray_hdf5_int64_r7_serial, readarray_hdf5_int32_r3_serial, readarray_hdf5_real_r6_parallel, readarray_hdf5_int64_r4_serial, readarray_hdf5_real_r3_parallel, readarray_hdf5_real_r3_serial, readarray_hdf5_int32_r5_parallel, readarray_hdf5_real_r6_serial, readarray_hdf5_int32_r5_serial, readarray_hdf5_int64_r2_parallel, readarray_hdf5_real_r7_parallel, readarray_hdf5_real_r7_serial, readarray_hdf5_real_r2_parallel
readarray_hdf5_int32_r7_serial calls h5tclose_f, h5dget_type_f, h5dread_f, h5dclose_f, h5dopen_f
readarray_hdf5_int64_r1_parallel calls h5pcreate_f, h5screate_simple_f, h5pset_dxpl_mpio_f, h5tclose_f, h5sclose_f, h5dget_type_f, h5dget_space_f, h5sselect_hyperslab_f, h5dread_f, h5dclose_f, h5pclose_f, h5dopen_f
readarray_hdf5_real_r1_serial calls h5tclose_f, h5dget_type_f, h5dread_f, h5dclose_f, h5dopen_f
readarray_hdf5_real_r2_serial calls h5tclose_f, h5dget_type_f, h5dread_f, h5dclose_f, h5dopen_f
readarray_hdf5_int32_r3_parallel calls h5pcreate_f, h5screate_simple_f, h5pset_dxpl_mpio_f, h5tclose_f, h5sclose_f, h5dget_type_f, h5dget_space_f, h5sselect_hyperslab_f, h5dread_f, h5dclose_f, h5pclose_f, h5dopen_f
readarray_hdf5_int32_r2_serial calls h5tclose_f, h5dget_type_f, h5dread_f, h5dclose_f, h5dopen_f
readarray_hdf5_int32_r2_parallel calls h5pcreate_f, h5screate_simple_f, h5pset_dxpl_mpio_f, h5tclose_f, h5sclose_f, h5dget_type_f, h5dget_space_f, h5sselect_hyperslab_f, h5dread_f, h5dclose_f, h5pclose_f, h5dopen_f
readarray_hdf5_int64_r5_serial calls h5tclose_f, h5dget_type_f, h5dread_f, h5dclose_f, h5dopen_f
readarray_hdf5_int32_r7_parallel calls h5pcreate_f, h5screate_simple_f, h5pset_dxpl_mpio_f, h5tclose_f, h5sclose_f, h5dget_type_f, h5dget_space_f, h5sselect_hyperslab_f, h5dread_f, h5dclose_f, h5pclose_f, h5dopen_f
readarray_hdf5_int32_r4_parallel calls h5pcreate_f, h5screate_simple_f, h5pset_dxpl_mpio_f, h5tclose_f, h5sclose_f, h5dget_type_f, h5dget_space_f, h5sselect_hyperslab_f, h5dread_f, h5dclose_f, h5pclose_f, h5dopen_f
readarray_hdf5_int64_r2_serial calls h5tclose_f, h5dget_type_f, h5dread_f, h5dclose_f, h5dopen_f
readarray_hdf5_real_r4_parallel calls h5pcreate_f, h5screate_simple_f, h5pset_dxpl_mpio_f, h5tclose_f, h5sclose_f, h5dget_type_f, h5dget_space_f, h5sselect_hyperslab_f, h5dread_f, h5dclose_f, h5pclose_f, h5dopen_f
readarray_hdf5_int64_r3_parallel calls h5pcreate_f, h5screate_simple_f, h5pset_dxpl_mpio_f, h5tclose_f, h5sclose_f, h5dget_type_f, h5dget_space_f, h5sselect_hyperslab_f, h5dread_f, h5dclose_f, h5pclose_f, h5dopen_f
readarray_hdf5_int32_r4_serial calls h5tclose_f, h5dget_type_f, h5dread_f, h5dclose_f, h5dopen_f
readarray_hdf5_int64_r7_parallel calls h5pcreate_f, h5screate_simple_f, h5pset_dxpl_mpio_f, h5tclose_f, h5sclose_f, h5dget_type_f, h5dget_space_f, h5sselect_hyperslab_f, h5dread_f, h5dclose_f, h5pclose_f, h5dopen_f
readarray_hdf5_real_r5_serial calls h5tclose_f, h5dget_type_f, h5dread_f, h5dclose_f, h5dopen_f
readarray_hdf5_int64_r1_serial calls h5tclose_f, h5dget_type_f, h5dread_f, h5dclose_f, h5dopen_f
readarray_hdf5_real_r4_serial calls h5tclose_f, h5dget_type_f, h5dread_f, h5dclose_f, h5dopen_f
readarray_hdf5_int64_r6_parallel calls h5pcreate_f, h5screate_simple_f, h5pset_dxpl_mpio_f, h5tclose_f, h5sclose_f, h5dget_type_f, h5dget_space_f, h5sselect_hyperslab_f, h5dread_f, h5dclose_f, h5pclose_f, h5dopen_f
readarray_hdf5_int32_r1_serial calls h5tclose_f, h5dget_type_f, h5dread_f, h5dclose_f, h5dopen_f
readarray_hdf5_int64_r5_parallel calls h5pcreate_f, h5screate_simple_f, h5pset_dxpl_mpio_f, h5tclose_f, h5sclose_f, h5dget_type_f, h5dget_space_f, h5sselect_hyperslab_f, h5dread_f, h5dclose_f, h5pclose_f, h5dopen_f
readarray_hdf5_int64_r6_serial calls h5tclose_f, h5dget_type_f, h5dread_f, h5dclose_f, h5dopen_f
readarray_hdf5_real_r1_parallel calls h5pcreate_f, h5screate_simple_f, h5pset_dxpl_mpio_f, h5tclose_f, h5sclose_f, h5dget_type_f, h5dget_space_f, h5sselect_hyperslab_f, h5dread_f, h5dclose_f, h5pclose_f, h5dopen_f
readarray_hdf5_int64_r3_serial calls h5tclose_f, h5dget_type_f, h5dread_f, h5dclose_f, h5dopen_f
readarray_hdf5_int64_r4_parallel calls h5pcreate_f, h5screate_simple_f, h5pset_dxpl_mpio_f, h5tclose_f, h5sclose_f, h5dget_type_f, h5dget_space_f, h5sselect_hyperslab_f, h5dread_f, h5dclose_f, h5pclose_f, h5dopen_f
readarray_hdf5_int32_r1_parallel calls h5pcreate_f, h5screate_simple_f, h5pset_dxpl_mpio_f, h5tclose_f, h5sclose_f, h5dget_type_f, h5dget_space_f, h5sselect_hyperslab_f, h5dread_f, h5dclose_f, h5pclose_f, h5dopen_f
readarray_hdf5_real_r5_parallel calls h5pcreate_f, h5screate_simple_f, h5pset_dxpl_mpio_f, h5tclose_f, h5sclose_f, h5dget_type_f, h5dget_space_f, h5sselect_hyperslab_f, h5dread_f, h5dclose_f, h5pclose_f, h5dopen_f
readarray_hdf5_int32_r6_parallel calls h5pcreate_f, h5screate_simple_f, h5pset_dxpl_mpio_f, h5tclose_f, h5sclose_f, h5dget_type_f, h5dget_space_f, h5sselect_hyperslab_f, h5dread_f, h5dclose_f, h5pclose_f, h5dopen_f
readarray_hdf5_int32_r6_serial calls h5tclose_f, h5dget_type_f, h5dread_f, h5dclose_f, h5dopen_f
readarray_hdf5_int64_r7_serial calls h5tclose_f, h5dget_type_f, h5dread_f, h5dclose_f, h5dopen_f
readarray_hdf5_int32_r3_serial calls h5tclose_f, h5dget_type_f, h5dread_f, h5dclose_f, h5dopen_f
readarray_hdf5_real_r6_parallel calls h5pcreate_f, h5screate_simple_f, h5pset_dxpl_mpio_f, h5tclose_f, h5sclose_f, h5dget_type_f, h5dget_space_f, h5sselect_hyperslab_f, h5dread_f, h5dclose_f, h5pclose_f, h5dopen_f
readarray_hdf5_int64_r4_serial calls h5tclose_f, h5dget_type_f, h5dread_f, h5dclose_f, h5dopen_f
readarray_hdf5_real_r3_parallel calls h5pcreate_f, h5screate_simple_f, h5pset_dxpl_mpio_f, h5tclose_f, h5sclose_f, h5dget_type_f, h5dget_space_f, h5sselect_hyperslab_f, h5dread_f, h5dclose_f, h5pclose_f, h5dopen_f
readarray_hdf5_real_r3_serial calls h5tclose_f, h5dget_type_f, h5dread_f, h5dclose_f, h5dopen_f
readarray_hdf5_int32_r5_parallel calls h5pcreate_f, h5screate_simple_f, h5pset_dxpl_mpio_f, h5tclose_f, h5sclose_f, h5dget_type_f, h5dget_space_f, h5sselect_hyperslab_f, h5dread_f, h5dclose_f, h5pclose_f, h5dopen_f
readarray_hdf5_real_r6_serial calls h5tclose_f, h5dget_type_f, h5dread_f, h5dclose_f, h5dopen_f
readarray_hdf5_int32_r5_serial calls h5tclose_f, h5dget_type_f, h5dread_f, h5dclose_f, h5dopen_f
readarray_hdf5_int64_r2_parallel calls h5pcreate_f, h5screate_simple_f, h5pset_dxpl_mpio_f, h5tclose_f, h5sclose_f, h5dget_type_f, h5dget_space_f, h5sselect_hyperslab_f, h5dread_f, h5dclose_f, h5pclose_f, h5dopen_f
readarray_hdf5_real_r7_parallel calls h5pcreate_f, h5screate_simple_f, h5pset_dxpl_mpio_f, h5tclose_f, h5sclose_f, h5dget_type_f, h5dget_space_f, h5sselect_hyperslab_f, h5dread_f, h5dclose_f, h5pclose_f, h5dopen_f
readarray_hdf5_real_r7_serial calls h5tclose_f, h5dget_type_f, h5dread_f, h5dclose_f, h5dopen_f
readarray_hdf5_real_r2_parallel calls h5pcreate_f, h5screate_simple_f, h5pset_dxpl_mpio_f, h5tclose_f, h5sclose_f, h5dget_type_f, h5dget_space_f, h5sselect_hyperslab_f, h5dread_f, h5dclose_f, h5pclose_f, h5dopen_f