CalculateDSDt_gpu – SELF
CalculateDSDt_gpu Interface
3-Clause BSD with attribution
8 statements
Source File
interface
Called by
public subroutine CalculateDSDt_gpu(fluxDivergence, source, dsdt, ndof) bind(c,name="0")
Arguments
Type Intent Optional Attributes Name
type(c_ptr), value :: fluxDivergence
type(c_ptr), value :: source
type(c_ptr), value :: dsdt
integer(kind=c_int), value :: ndof
Call graph
calculatetendency_dgmodel2d calls calculatedsdt_gpu
calculatetendency_dgmodel1d calls calculatedsdt_gpu
calculatetendency_dgmodel3d calls calculatedsdt_gpu
calculatetendency_ecdgmodel3d calls calculatedsdt_gpu
calculatetendency_ecdgmodel2d calls calculatedsdt_gpu