Divergence_2D_gpu – SELF
Divergence_2D_gpu Interface
3-Clause BSD with attribution
8 statements
Source File
interface
Called by
public subroutine Divergence_2D_gpu(f, df, dmat, N, nVar, nEl) bind(c,name="0")
Arguments
Type Intent Optional Attributes Name
type(c_ptr), value :: f
type(c_ptr), value :: df
type(c_ptr), value :: dmat
integer(kind=c_int), value :: N
integer(kind=c_int), value :: nVar
integer(kind=c_int), value :: nEl
Call graph
mappeddgdivergence_mappedvector2d calls divergence_2d_gpu
mappeddivergence_mappedvector2d calls divergence_2d_gpu
divergence_vector2d calls divergence_2d_gpu