hipblasCreate – SELF
hipblasCreate Interface
3-Clause BSD with attribution
10 statements
Source File
public interface hipblasCreate
Called by
Contents
Functions
hipblasCreate_
Functions
public function hipblasCreate_(handle) bind(c,name="cublasCreate_v2")
Arguments
Type Intent Optional Attributes Name
type(c_ptr) :: handle
Return Value integer(kind=kind(HIPBLAS_STATUS_SUCCESS))
Call graph
init_scalar1d calls hipblascreate
init_tensor3d calls hipblascreate
init_mappedscalar3d calls hipblascreate
init_vector3d calls hipblascreate
init_vector2d calls hipblascreate
init_mappedscalar2d calls hipblascreate
init_scalar3d calls hipblascreate
init_scalar2d calls hipblascreate
init_tensor2d calls hipblascreate