hipblasDestroy – SELF
hipblasDestroy Interface
3-Clause BSD with attribution
10 statements
Source File
public interface hipblasDestroy
Called by
Contents
Functions
hipblasDestroy_
Functions
public function hipblasDestroy_(handle) bind(c,name="cublasDestroy_v2")
Arguments
Type Intent Optional Attributes Name
type(c_ptr), value :: handle
Return Value integer(kind=kind(HIPBLAS_STATUS_SUCCESS))
Call graph
free_scalar2d calls hipblasdestroy
free_scalar1d calls hipblasdestroy
free_vector2d calls hipblasdestroy
free_scalar3d calls hipblasdestroy
free_tensor3d calls hipblasdestroy
free_mappedscalar2d calls hipblasdestroy
free_tensor2d calls hipblasdestroy
free_vector3d calls hipblasdestroy
free_mappedscalar3d calls hipblasdestroy