hipFree – SELF
hipFree Interface
3-Clause BSD with attribution
10 statements
Source File
public interface hipFree
Called by
Contents
Functions
hipFree_
Functions
public function hipFree_(ptr) bind(c,name="hipFree")
Arguments
Type Intent Optional Attributes Name
type(c_ptr), value :: ptr
Return Value integer(kind=c_int)
Call graph
free_mesh2d calls hipfree
free_tensor2d calls hipfree
free_dgmodel2d calls hipfree
free_twopointvector2d calls hipfree
free_vector3d calls hipfree
free_scalar3d calls hipfree
free_vector2d calls hipfree
free_dgmodel1d calls hipfree
free_scalar1d calls hipfree
free_mappedvector3d calls hipfree, free_vector3d
free_twopointvector3d calls hipfree
free_esatmo2d calls hipfree
free_mappedscalar3d calls hipfree
free_lagrange calls hipfree
free_esatmo3d calls hipfree
free_dgmodel3d calls hipfree
free_tensor3d calls hipfree
updatedevice_points calls hipfree
free_ecadvection2d calls hipfree
free_mesh3d calls hipfree
free_points calls hipfree
free_mappedvector2d calls hipfree, free_vector2d
free_scalar2d calls hipfree
free_ecadvection3d calls hipfree
free_mappedscalar2d calls hipfree
free_domaindecomposition calls hipfree