hipGetDeviceCount – SELF
hipGetDeviceCount Interface
3-Clause BSD with attribution
10 statements
Source File
public interface hipGetDeviceCount
Called by
Contents
Functions
hipGetDeviceCount_
Functions
public function hipGetDeviceCount_(count) bind(c,name="hipGetDeviceCount")
Arguments
Type Intent Optional Attributes Name
integer(kind=c_int) :: count
Return Value integer(kind=kind(hipSuccess))
Call graph
gpuavailable calls hipgetdevicecount
init_domaindecomposition calls hipgetdevicecount
init_scalar1d calls gpuavailable
init_lagrange calls gpuavailable