hipMemcpy – SELF
hipMemcpy Interface
3-Clause BSD with attribution
13 statements
Source File
public interface hipMemcpy
Called by
Contents
Functions
hipMemcpy_
Functions
public function hipMemcpy_(dest, src, sizeBytes, myKind) bind(c,name="hipMemcpy")
Arguments
Type Intent Optional Attributes Name
type(c_ptr), value :: dest
type(c_ptr), value :: src
integer(kind=c_size_t), value :: sizeBytes
integer(kind=c_int), value :: myKind
Return Value integer(kind=c_int)
Call graph
calculateentropy_dgmodel2d calls hipmemcpy
boundaryflux_dgmodel3d calls hipmemcpy
sourcemethod_ecadvection3d calls hipmemcpy
setinteriorfromequation_mappedscalar1d calls hipmemcpy
sourcemethod_dgmodel3d calls hipmemcpy
init_esatmo2d calls hipmemcpy
updatehost_tensor2d calls hipmemcpy
buildhaloexchange_domaindecomposition calls hipmemcpy
setinteriorfromequation_mappedvector2d calls hipmemcpy
init_esatmo3d calls hipmemcpy
updatehost_vector2d calls hipmemcpy
updatehost_scalar1d calls hipmemcpy
calculateentropy_dgmodel1d calls hipmemcpy
setgradientboundarycondition_dgmodel1d calls hipmemcpy
updatedevice_vector3d calls hipmemcpy
updatehost_twopointvector2d calls hipmemcpy
updatedevice_tensor3d calls hipmemcpy
setinteriorfromequation_mappedscalar2d calls hipmemcpy
calculateentropy_dgmodel3d calls hipmemcpy
init_ecadvection2d calls hipmemcpy
updatedevice_mesh3d calls hipmemcpy
setelemtorank_domaindecomposition calls hipmemcpy
updatedevice_scalar1d calls hipmemcpy
updatedevice_twopointvector3d calls hipmemcpy
updatedevice_scalar2d calls hipmemcpy
init_dgmodel2d calls hipmemcpy
sourcemethod_dgmodel2d calls hipmemcpy
sideexchange_mappedscalar1d calls hipmemcpy
fluxmethod_dgmodel1d calls hipmemcpy
updatehost_scalar3d calls hipmemcpy
setinteriorfromequation_mappedscalar3d calls hipmemcpy
updatedevice_points calls hipmemcpy
setinteriorfromequation_mappedvector3d calls hipmemcpy
boundaryflux_dgmodel2d calls hipmemcpy
init_dgmodel1d calls hipmemcpy
sourcemethod_dgmodel1d calls hipmemcpy
init_ecadvection3d calls hipmemcpy
updatehost_vector3d calls hipmemcpy
updatedevice_scalar3d calls hipmemcpy
updatehost_tensor3d calls hipmemcpy
fluxmethod_dgmodel2d calls hipmemcpy
fluxmethod_dgmodel3d calls hipmemcpy
sourcemethod_ecadvection2d calls hipmemcpy
updatedevice_mesh2d calls hipmemcpy
updatedevice_tensor2d calls hipmemcpy
init_lagrange calls hipmemcpy
updatehost_scalar2d calls hipmemcpy
updatehost_twopointvector3d calls hipmemcpy
updatedevice_vector2d calls hipmemcpy
init_dgmodel3d calls hipmemcpy
boundaryflux_dgmodel1d calls hipmemcpy
setboundarycondition_dgmodel1d calls hipmemcpy
updatedevice_twopointvector2d calls hipmemcpy