hipMalloc – SELF
hipMalloc Interface
3-Clause BSD with attribution
11 statements
Source File
public interface hipMalloc
Called by
Contents
Functions
hipMalloc_
Functions
public function hipMalloc_(ptr, mySize) bind(c,name="hipMalloc")
Arguments
Type Intent Optional Attributes Name
type(c_ptr) :: ptr
integer(kind=c_size_t), value :: mySize
Return Value integer(kind=c_int)
Call graph
sideexchangestart_mappedscalar2d calls hipmalloc
init_scalar1d calls hipmalloc
init_mesh3d calls hipmalloc
init_twopointvector3d calls hipmalloc
init_esatmo2d calls hipmalloc
buildhaloexchange_domaindecomposition calls hipmalloc
init_mappedscalar3d calls hipmalloc
init_esatmo3d calls hipmalloc
init_scalar3d calls hipmalloc
init_mappedscalar2d calls hipmalloc
sideexchangestart_mappedscalar3d calls hipmalloc
init_ecadvection2d calls hipmalloc
init_mesh2d calls hipmalloc
init_tensor2d calls hipmalloc
setelemtorank_domaindecomposition calls hipmalloc
init_points calls hipmalloc
init_vector2d calls hipmalloc
init_dgmodel2d calls hipmalloc
init_vector3d calls hipmalloc
init_twopointvector2d calls hipmalloc
updatedevice_points calls hipmalloc
init_dgmodel1d calls hipmalloc
init_ecadvection3d calls hipmalloc
mpiexchangeasync_mappedvector3d calls hipmalloc
init_scalar2d calls hipmalloc
init_lagrange calls hipmalloc
mpiexchangeasync_mappedvector2d calls hipmalloc
init_dgmodel3d calls hipmalloc
init_tensor3d calls hipmalloc