JacobianWeight_2D_gpu – SELF
JacobianWeight_2D_gpu Interface
3-Clause BSD with attribution
8 statements
Source File
interface
Called by
public subroutine JacobianWeight_2D_gpu(scalar, J, N, nVar, nEl) bind(c,name="0")
Arguments
Type Intent Optional Attributes Name
type(c_ptr), value :: scalar
type(c_ptr), value :: J
integer(kind=c_int), value :: N
integer(kind=c_int), value :: nVar
integer(kind=c_int), value :: nEl
Call graph
mappeddgdivergence_mappedvector2d calls jacobianweight_2d_gpu
mappeddggradient_mappedscalar2d calls jacobianweight_2d_gpu
mappeddivergence_mappedvector2d calls jacobianweight_2d_gpu
mappedgradient_mappedscalar2d calls jacobianweight_2d_gpu