Open_HDF5 – SELF
Open_HDF5 Interface
3-Clause BSD with attribution
4 statements
Source File
public interface Open_HDF5
Calls
Called by
Contents
Module Procedures
Open_HDF5_serial Open_HDF5_parallel
Module Procedures
private subroutine Open_HDF5_serial(fileName, accessFlag, fileId)
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: fileName
integer, intent(in) :: accessFlag
integer(kind=HID_T), intent(inout) :: fileId
private subroutine Open_HDF5_parallel(fileName, accessFlag, fileId, mpiComm)
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: fileName
integer, intent(in) :: accessFlag
integer(kind=HID_T), intent(inout) :: fileId
integer, intent(in) :: mpiComm
Call graph
open_hdf5 calls open_hdf5_serial, open_hdf5_parallel
open_hdf5_serial calls h5open_f, h5fopen_f, h5fcreate_f
open_hdf5_parallel calls h5open_f, h5pcreate_f, h5pclose_f, h5fopen_f, h5fcreate_f, h5pset_fapl_mpio_f
read_dgmodel2d_t calls open_hdf5
write_dgmodel3d_t calls open_hdf5
read_dgmodel3d_t calls open_hdf5
read_hopr_mesh2d_t calls open_hdf5
write_geometry1d calls open_hdf5
write_mesh3d_t calls open_hdf5
write_dgmodel1d_t calls open_hdf5
write_dgmodel2d_t calls open_hdf5
write_mesh2d_t calls open_hdf5
write_mesh1d calls open_hdf5
read_hopr_mesh3d_t calls open_hdf5
read_dgmodel1d_t calls open_hdf5