ReadAttribute_HDF5 – SELF
ReadAttribute_HDF5 Interface
3-Clause BSD with attribution
5 statements
Source File
public interface ReadAttribute_HDF5
Calls
Called by
Contents
Module Procedures
ReadAttribute_HDF5_int32 ReadAttribute_HDF5_real ReadAttribute_HDF5_character
Module Procedures
private subroutine ReadAttribute_HDF5_int32(fileId, attributeName, attribute)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: attributeName
integer, intent(out) :: attribute
private subroutine ReadAttribute_HDF5_real(fileId, attributeName, attribute)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: attributeName
real(kind=prec), intent(out) :: attribute
private subroutine ReadAttribute_HDF5_character(fileId, attributeName, attribute)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: attributeName
character, intent(out) :: attribute
Call graph
readattribute_hdf5 calls readattribute_hdf5_int32, readattribute_hdf5_real, readattribute_hdf5_character
readattribute_hdf5_int32 calls h5aopen_f, h5aread_f, h5tclose_f, h5aclose_f, h5aget_type_f
readattribute_hdf5_real calls h5aopen_f, h5aread_f, h5tclose_f, h5aclose_f, h5aget_type_f
readattribute_hdf5_character calls h5aopen_f, h5aread_f, h5tclose_f, h5aclose_f, h5aget_type_f
read_hopr_mesh2d_t calls readattribute_hdf5
read_hopr_mesh3d_t calls readattribute_hdf5