WriteCharacter_HDF5 – SELF
WriteCharacter_HDF5 Interface
3-Clause BSD with attribution
3 statements
Source File
public interface WriteCharacter_HDF5
Calls
Called by
Contents
Module Procedures
WriteCharacter_HDF5_serial
Module Procedures
private subroutine WriteCharacter_HDF5_serial(fileId, name, hfField)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character(len=*), intent(in) :: name
character(len=*), intent(in) :: hfField
Call graph
writecharacter_hdf5 calls writecharacter_hdf5_serial
writecharacter_hdf5_serial calls h5tcopy_f, h5sclose_f, h5screate_simple_f, h5dwrite_vl_f, h5tset_strpad_f, h5dcreate_f, h5dclose_f
writehdf5_metadata calls writecharacter_hdf5