WriteArray_HDF5 – SELF
WriteArray_HDF5 Interface
Anti-Capitalist Software License
44 statements
Source File
public interface WriteArray_HDF5
Calls
Contents
Module Procedures
WriteArray_HDF5_real_r1_serial WriteArray_HDF5_real_r2_serial WriteArray_HDF5_real_r3_serial WriteArray_HDF5_real_r4_serial WriteArray_HDF5_real_r5_serial WriteArray_HDF5_real_r6_serial WriteArray_HDF5_real_r7_serial WriteArray_HDF5_int32_r1_serial WriteArray_HDF5_int32_r2_serial WriteArray_HDF5_int32_r3_serial WriteArray_HDF5_int32_r4_serial WriteArray_HDF5_int32_r5_serial WriteArray_HDF5_int32_r6_serial WriteArray_HDF5_int32_r7_serial WriteArray_HDF5_int64_r1_serial WriteArray_HDF5_int64_r2_serial WriteArray_HDF5_int64_r3_serial WriteArray_HDF5_int64_r4_serial WriteArray_HDF5_int64_r5_serial WriteArray_HDF5_int64_r6_serial WriteArray_HDF5_int64_r7_serial WriteArray_HDF5_real_r1_parallel WriteArray_HDF5_real_r2_parallel WriteArray_HDF5_real_r3_parallel WriteArray_HDF5_real_r4_parallel WriteArray_HDF5_real_r5_parallel WriteArray_HDF5_real_r6_parallel WriteArray_HDF5_real_r7_parallel WriteArray_HDF5_int32_r1_parallel WriteArray_HDF5_int32_r2_parallel WriteArray_HDF5_int32_r3_parallel WriteArray_HDF5_int32_r4_parallel WriteArray_HDF5_int32_r5_parallel WriteArray_HDF5_int32_r6_parallel WriteArray_HDF5_int32_r7_parallel WriteArray_HDF5_int64_r1_parallel WriteArray_HDF5_int64_r2_parallel WriteArray_HDF5_int64_r3_parallel WriteArray_HDF5_int64_r4_parallel WriteArray_HDF5_int64_r5_parallel WriteArray_HDF5_int64_r6_parallel WriteArray_HDF5_int64_r7_parallel
Module Procedures
private subroutine WriteArray_HDF5_real_r1_serial(fileId, arrayName, hfArray)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfReal_r1), intent(in) :: hfArray
private subroutine WriteArray_HDF5_real_r2_serial(fileId, arrayName, hfArray)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfReal_r2), intent(in) :: hfArray
private subroutine WriteArray_HDF5_real_r3_serial(fileId, arrayName, hfArray)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfReal_r3), intent(in) :: hfArray
private subroutine WriteArray_HDF5_real_r4_serial(fileId, arrayName, hfArray)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfReal_r4), intent(in) :: hfArray
private subroutine WriteArray_HDF5_real_r5_serial(fileId, arrayName, hfArray)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfReal_r5), intent(in) :: hfArray
private subroutine WriteArray_HDF5_real_r6_serial(fileId, arrayName, hfArray)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfReal_r6), intent(in) :: hfArray
private subroutine WriteArray_HDF5_real_r7_serial(fileId, arrayName, hfArray)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfReal_r7), intent(in) :: hfArray
private subroutine WriteArray_HDF5_int32_r1_serial(fileId, arrayName, hfArray)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfint32_r1), intent(in) :: hfArray
private subroutine WriteArray_HDF5_int32_r2_serial(fileId, arrayName, hfArray)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfint32_r2), intent(in) :: hfArray
private subroutine WriteArray_HDF5_int32_r3_serial(fileId, arrayName, hfArray)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfint32_r3), intent(in) :: hfArray
private subroutine WriteArray_HDF5_int32_r4_serial(fileId, arrayName, hfArray)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfint32_r4), intent(in) :: hfArray
private subroutine WriteArray_HDF5_int32_r5_serial(fileId, arrayName, hfArray)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfint32_r5), intent(in) :: hfArray
private subroutine WriteArray_HDF5_int32_r6_serial(fileId, arrayName, hfArray)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfint32_r6), intent(in) :: hfArray
private subroutine WriteArray_HDF5_int32_r7_serial(fileId, arrayName, hfArray)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfint32_r7), intent(in) :: hfArray
private subroutine WriteArray_HDF5_int64_r1_serial(fileId, arrayName, hfArray)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfint64_r1), intent(in) :: hfArray
private subroutine WriteArray_HDF5_int64_r2_serial(fileId, arrayName, hfArray)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfint64_r2), intent(in) :: hfArray
private subroutine WriteArray_HDF5_int64_r3_serial(fileId, arrayName, hfArray)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfint64_r3), intent(in) :: hfArray
private subroutine WriteArray_HDF5_int64_r4_serial(fileId, arrayName, hfArray)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfint64_r4), intent(in) :: hfArray
private subroutine WriteArray_HDF5_int64_r5_serial(fileId, arrayName, hfArray)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfint64_r5), intent(in) :: hfArray
private subroutine WriteArray_HDF5_int64_r6_serial(fileId, arrayName, hfArray)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfint64_r6), intent(in) :: hfArray
private subroutine WriteArray_HDF5_int64_r7_serial(fileId, arrayName, hfArray)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfint64_r7), intent(in) :: hfArray
private subroutine WriteArray_HDF5_real_r1_parallel(fileId, arrayName, hfArray, offset, globalDims)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfReal_r1), intent(in) :: hfArray
integer(kind=HID_T), intent(in) :: offset(1)
integer(kind=HID_T), intent(in) :: globalDims(1)
private subroutine WriteArray_HDF5_real_r2_parallel(fileId, arrayName, hfArray, offset, globalDims)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfReal_r2), intent(in) :: hfArray
integer(kind=HID_T), intent(in) :: offset(1:2)
integer(kind=HID_T), intent(in) :: globalDims(1:2)
private subroutine WriteArray_HDF5_real_r3_parallel(fileId, arrayName, hfArray, offset, globalDims)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfReal_r3), intent(in) :: hfArray
integer(kind=HID_T), intent(in) :: offset(1:3)
integer(kind=HID_T), intent(in) :: globalDims(1:3)
private subroutine WriteArray_HDF5_real_r4_parallel(fileId, arrayName, hfArray, offset, globalDims)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfReal_r4), intent(in) :: hfArray
integer(kind=HID_T), intent(in) :: offset(1:4)
integer(kind=HID_T), intent(in) :: globalDims(1:4)
private subroutine WriteArray_HDF5_real_r5_parallel(fileId, arrayName, hfArray, offset, globalDims)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfReal_r5), intent(in) :: hfArray
integer(kind=HID_T), intent(in) :: offset(1:5)
integer(kind=HID_T), intent(in) :: globalDims(1:5)
private subroutine WriteArray_HDF5_real_r6_parallel(fileId, arrayName, hfArray, offset, globalDims)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfReal_r6), intent(in) :: hfArray
integer(kind=HID_T), intent(in) :: offset(1:6)
integer(kind=HID_T), intent(in) :: globalDims(1:6)
private subroutine WriteArray_HDF5_real_r7_parallel(fileId, arrayName, hfArray, offset, globalDims)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfReal_r7), intent(in) :: hfArray
integer(kind=HID_T), intent(in) :: offset(1:7)
integer(kind=HID_T), intent(in) :: globalDims(1:7)
private subroutine WriteArray_HDF5_int32_r1_parallel(fileId, arrayName, hfArray, offset, globalDims)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfint32_r1), intent(in) :: hfArray
integer(kind=HID_T), intent(in) :: offset(1)
integer(kind=HID_T), intent(in) :: globalDims(1)
private subroutine WriteArray_HDF5_int32_r2_parallel(fileId, arrayName, hfArray, offset, globalDims)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfint32_r2), intent(in) :: hfArray
integer(kind=HID_T), intent(in) :: offset(1:2)
integer(kind=HID_T), intent(in) :: globalDims(1:2)
private subroutine WriteArray_HDF5_int32_r3_parallel(fileId, arrayName, hfArray, offset, globalDims)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfint32_r3), intent(in) :: hfArray
integer(kind=HID_T), intent(in) :: offset(1:3)
integer(kind=HID_T), intent(in) :: globalDims(1:3)
private subroutine WriteArray_HDF5_int32_r4_parallel(fileId, arrayName, hfArray, offset, globalDims)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfint32_r4), intent(in) :: hfArray
integer(kind=HID_T), intent(in) :: offset(1:4)
integer(kind=HID_T), intent(in) :: globalDims(1:4)
private subroutine WriteArray_HDF5_int32_r5_parallel(fileId, arrayName, hfArray, offset, globalDims)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfint32_r5), intent(in) :: hfArray
integer(kind=HID_T), intent(in) :: offset(1:5)
integer(kind=HID_T), intent(in) :: globalDims(1:5)
private subroutine WriteArray_HDF5_int32_r6_parallel(fileId, arrayName, hfArray, offset, globalDims)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfint32_r6), intent(in) :: hfArray
integer(kind=HID_T), intent(in) :: offset(1:6)
integer(kind=HID_T), intent(in) :: globalDims(1:6)
private subroutine WriteArray_HDF5_int32_r7_parallel(fileId, arrayName, hfArray, offset, globalDims)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfint32_r7), intent(in) :: hfArray
integer(kind=HID_T), intent(in) :: offset(1:7)
integer(kind=HID_T), intent(in) :: globalDims(1:7)
private subroutine WriteArray_HDF5_int64_r1_parallel(fileId, arrayName, hfArray, offset, globalDims)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfint64_r1), intent(in) :: hfArray
integer(kind=HID_T), intent(in) :: offset(1)
integer(kind=HID_T), intent(in) :: globalDims(1)
private subroutine WriteArray_HDF5_int64_r2_parallel(fileId, arrayName, hfArray, offset, globalDims)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfint64_r2), intent(in) :: hfArray
integer(kind=HID_T), intent(in) :: offset(1:2)
integer(kind=HID_T), intent(in) :: globalDims(1:2)
private subroutine WriteArray_HDF5_int64_r3_parallel(fileId, arrayName, hfArray, offset, globalDims)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfint64_r3), intent(in) :: hfArray
integer(kind=HID_T), intent(in) :: offset(1:3)
integer(kind=HID_T), intent(in) :: globalDims(1:3)
private subroutine WriteArray_HDF5_int64_r4_parallel(fileId, arrayName, hfArray, offset, globalDims)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfint64_r4), intent(in) :: hfArray
integer(kind=HID_T), intent(in) :: offset(1:4)
integer(kind=HID_T), intent(in) :: globalDims(1:4)
private subroutine WriteArray_HDF5_int64_r5_parallel(fileId, arrayName, hfArray, offset, globalDims)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfint64_r5), intent(in) :: hfArray
integer(kind=HID_T), intent(in) :: offset(1:5)
integer(kind=HID_T), intent(in) :: globalDims(1:5)
private subroutine WriteArray_HDF5_int64_r6_parallel(fileId, arrayName, hfArray, offset, globalDims)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfint64_r6), intent(in) :: hfArray
integer(kind=HID_T), intent(in) :: offset(1:6)
integer(kind=HID_T), intent(in) :: globalDims(1:6)
private subroutine WriteArray_HDF5_int64_r7_parallel(fileId, arrayName, hfArray, offset, globalDims)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfint64_r7), intent(in) :: hfArray
integer(kind=HID_T), intent(in) :: offset(1:7)
integer(kind=HID_T), intent(in) :: globalDims(1:7)
Call graph
writearray_hdf5 calls writearray_hdf5_int64_r2_serial, writearray_hdf5_int32_r5_parallel, writearray_hdf5_real_r7_parallel, writearray_hdf5_int32_r3_parallel, writearray_hdf5_real_r6_parallel, writearray_hdf5_int32_r1_parallel, writearray_hdf5_real_r4_serial, writearray_hdf5_int32_r5_serial, writearray_hdf5_int32_r7_parallel, writearray_hdf5_int32_r3_serial, writearray_hdf5_int32_r7_serial, writearray_hdf5_real_r7_serial, writearray_hdf5_real_r1_parallel, writearray_hdf5_int64_r6_serial, writearray_hdf5_real_r5_parallel, writearray_hdf5_int64_r5_serial, writearray_hdf5_int64_r6_parallel, writearray_hdf5_real_r1_serial, writearray_hdf5_int64_r2_parallel, writearray_hdf5_int32_r4_serial, writearray_hdf5_int32_r6_serial, writearray_hdf5_real_r5_serial, writearray_hdf5_int32_r1_serial, writearray_hdf5_real_r6_serial, writearray_hdf5_int64_r4_serial, writearray_hdf5_int32_r2_serial, writearray_hdf5_int64_r3_serial, writearray_hdf5_real_r4_parallel, writearray_hdf5_int32_r4_parallel, writearray_hdf5_int64_r1_serial, writearray_hdf5_real_r3_serial, writearray_hdf5_real_r2_parallel, writearray_hdf5_real_r3_parallel, writearray_hdf5_int64_r7_serial, writearray_hdf5_real_r2_serial, writearray_hdf5_int32_r2_parallel, writearray_hdf5_int64_r7_parallel, writearray_hdf5_int32_r6_parallel, writearray_hdf5_int64_r4_parallel, writearray_hdf5_int64_r5_parallel, writearray_hdf5_int64_r3_parallel, writearray_hdf5_int64_r1_parallel
writearray_hdf5_int64_r2_serial calls h5screate_simple_f, h5dcreate_f, h5sclose_f, h5dwrite_f, h5dclose_f
writearray_hdf5_int32_r5_parallel calls h5pcreate_f, h5screate_simple_f, h5dcreate_f, h5sclose_f, h5sselect_hyperslab_f, h5dwrite_f, h5dclose_f, h5pset_chunk_f, h5pclose_f
writearray_hdf5_real_r7_parallel calls h5pcreate_f, h5screate_simple_f, h5dcreate_f, h5sclose_f, h5sselect_hyperslab_f, h5dwrite_f, h5dclose_f, h5pset_chunk_f, h5pclose_f
writearray_hdf5_int32_r3_parallel calls h5pcreate_f, h5screate_simple_f, h5dcreate_f, h5sclose_f, h5sselect_hyperslab_f, h5dwrite_f, h5dclose_f, h5pset_chunk_f, h5pclose_f
writearray_hdf5_real_r6_parallel calls h5pcreate_f, h5screate_simple_f, h5dcreate_f, h5sclose_f, h5sselect_hyperslab_f, h5dwrite_f, h5dclose_f, h5pset_chunk_f, h5pclose_f
writearray_hdf5_int32_r1_parallel calls h5pcreate_f, h5screate_simple_f, h5dcreate_f, h5sclose_f, h5sselect_hyperslab_f, h5dwrite_f, h5dclose_f, h5pset_chunk_f, h5pclose_f
writearray_hdf5_real_r4_serial calls h5screate_simple_f, h5dcreate_f, h5sclose_f, h5dwrite_f, h5dclose_f
writearray_hdf5_int32_r5_serial calls h5screate_simple_f, h5dcreate_f, h5sclose_f, h5dwrite_f, h5dclose_f
writearray_hdf5_int32_r7_parallel calls h5pcreate_f, h5screate_simple_f, h5dcreate_f, h5sclose_f, h5sselect_hyperslab_f, h5dwrite_f, h5dclose_f, h5pset_chunk_f, h5pclose_f
writearray_hdf5_int32_r3_serial calls h5screate_simple_f, h5dcreate_f, h5sclose_f, h5dwrite_f, h5dclose_f
writearray_hdf5_int32_r7_serial calls h5screate_simple_f, h5dcreate_f, h5sclose_f, h5dwrite_f, h5dclose_f
writearray_hdf5_real_r7_serial calls h5screate_simple_f, h5dcreate_f, h5sclose_f, h5dwrite_f, h5dclose_f
writearray_hdf5_real_r1_parallel calls h5pcreate_f, h5screate_simple_f, h5dcreate_f, h5sclose_f, h5sselect_hyperslab_f, h5dwrite_f, h5dclose_f, h5pset_chunk_f, h5pclose_f
writearray_hdf5_int64_r6_serial calls h5screate_simple_f, h5dcreate_f, h5sclose_f, h5dwrite_f, h5dclose_f
writearray_hdf5_real_r5_parallel calls h5pcreate_f, h5screate_simple_f, h5dcreate_f, h5sclose_f, h5sselect_hyperslab_f, h5dwrite_f, h5dclose_f, h5pset_chunk_f, h5pclose_f
writearray_hdf5_int64_r5_serial calls h5screate_simple_f, h5dcreate_f, h5sclose_f, h5dwrite_f, h5dclose_f
writearray_hdf5_int64_r6_parallel calls h5pcreate_f, h5screate_simple_f, h5dcreate_f, h5sclose_f, h5sselect_hyperslab_f, h5dwrite_f, h5dclose_f, h5pset_chunk_f, h5pclose_f
writearray_hdf5_real_r1_serial calls h5screate_simple_f, h5dcreate_f, h5sclose_f, h5dwrite_f, h5dclose_f
writearray_hdf5_int64_r2_parallel calls h5pcreate_f, h5screate_simple_f, h5dcreate_f, h5sclose_f, h5sselect_hyperslab_f, h5dwrite_f, h5dclose_f, h5pset_chunk_f, h5pclose_f
writearray_hdf5_int32_r4_serial calls h5screate_simple_f, h5dcreate_f, h5sclose_f, h5dwrite_f, h5dclose_f
writearray_hdf5_int32_r6_serial calls h5screate_simple_f, h5dcreate_f, h5sclose_f, h5dwrite_f, h5dclose_f
writearray_hdf5_real_r5_serial calls h5screate_simple_f, h5dcreate_f, h5sclose_f, h5dwrite_f, h5dclose_f
writearray_hdf5_int32_r1_serial calls h5screate_simple_f, h5dcreate_f, h5sclose_f, h5dwrite_f, h5dclose_f
writearray_hdf5_real_r6_serial calls h5screate_simple_f, h5dcreate_f, h5sclose_f, h5dwrite_f, h5dclose_f
writearray_hdf5_int64_r4_serial calls h5screate_simple_f, h5dcreate_f, h5sclose_f, h5dwrite_f, h5dclose_f
writearray_hdf5_int32_r2_serial calls h5screate_simple_f, h5dcreate_f, h5sclose_f, h5dwrite_f, h5dclose_f
writearray_hdf5_int64_r3_serial calls h5screate_simple_f, h5dcreate_f, h5sclose_f, h5dwrite_f, h5dclose_f
writearray_hdf5_real_r4_parallel calls h5pcreate_f, h5screate_simple_f, h5dcreate_f, h5sclose_f, h5sselect_hyperslab_f, h5dwrite_f, h5dclose_f, h5pset_chunk_f, h5pclose_f
writearray_hdf5_int32_r4_parallel calls h5pcreate_f, h5screate_simple_f, h5dcreate_f, h5sclose_f, h5sselect_hyperslab_f, h5dwrite_f, h5dclose_f, h5pset_chunk_f, h5pclose_f
writearray_hdf5_int64_r1_serial calls h5screate_simple_f, h5dcreate_f, h5sclose_f, h5dwrite_f, h5dclose_f
writearray_hdf5_real_r3_serial calls h5screate_simple_f, h5dcreate_f, h5sclose_f, h5dwrite_f, h5dclose_f
writearray_hdf5_real_r2_parallel calls h5pcreate_f, h5screate_simple_f, h5dcreate_f, h5sclose_f, h5sselect_hyperslab_f, h5dwrite_f, h5dclose_f, h5pset_chunk_f, h5pclose_f
writearray_hdf5_real_r3_parallel calls h5pcreate_f, h5screate_simple_f, h5dcreate_f, h5sclose_f, h5sselect_hyperslab_f, h5dwrite_f, h5dclose_f, h5pset_chunk_f, h5pclose_f
writearray_hdf5_int64_r7_serial calls h5screate_simple_f, h5dcreate_f, h5sclose_f, h5dwrite_f, h5dclose_f
writearray_hdf5_real_r2_serial calls h5screate_simple_f, h5dcreate_f, h5sclose_f, h5dwrite_f, h5dclose_f
writearray_hdf5_int32_r2_parallel calls h5pcreate_f, h5screate_simple_f, h5dcreate_f, h5sclose_f, h5sselect_hyperslab_f, h5dwrite_f, h5dclose_f, h5pset_chunk_f, h5pclose_f
writearray_hdf5_int64_r7_parallel calls h5pcreate_f, h5screate_simple_f, h5dcreate_f, h5sclose_f, h5sselect_hyperslab_f, h5dwrite_f, h5dclose_f, h5pset_chunk_f, h5pclose_f
writearray_hdf5_int32_r6_parallel calls h5pcreate_f, h5screate_simple_f, h5dcreate_f, h5sclose_f, h5sselect_hyperslab_f, h5dwrite_f, h5dclose_f, h5pset_chunk_f, h5pclose_f
writearray_hdf5_int64_r4_parallel calls h5pcreate_f, h5screate_simple_f, h5dcreate_f, h5sclose_f, h5sselect_hyperslab_f, h5dwrite_f, h5dclose_f, h5pset_chunk_f, h5pclose_f
writearray_hdf5_int64_r5_parallel calls h5pcreate_f, h5screate_simple_f, h5dcreate_f, h5sclose_f, h5sselect_hyperslab_f, h5dwrite_f, h5dclose_f, h5pset_chunk_f, h5pclose_f
writearray_hdf5_int64_r3_parallel calls h5pcreate_f, h5screate_simple_f, h5dcreate_f, h5sclose_f, h5sselect_hyperslab_f, h5dwrite_f, h5dclose_f, h5pset_chunk_f, h5pclose_f
writearray_hdf5_int64_r1_parallel calls h5pcreate_f, h5screate_simple_f, h5dcreate_f, h5sclose_f, h5sselect_hyperslab_f, h5dwrite_f, h5dclose_f, h5pset_chunk_f, h5pclose_f