#!/bin/bash

# Compilers
export FC=pgfortran
export MPIFC=mpif90

# Support
export DEBUG=no
export TIMING=yes

# Precision
export DOUBLE_PRECISION=no

# Geometry
export SKEW_METRICS=no

# Parallelization schemes
export CUDA=yes
export GPU_ARCH=cc35
export CUDA_VERSION=cuda8.0
export GPU_DIRECT=no

export MPI=yes
export MPI_LIB=
export MPI_INC=

export OMP=no

# SELF Features

