#!/bin/bash

# Compilers
export FC=gfortran
export MPIFC=mpif90

# Support
export DEBUG=no
export TIMING=no

# Precision
export DOUBLE_PRECISION=no

# Geometry
export CURL_INVARIANT=no

# Parallelization schemes
export CUDA=no
export GPU_ARCH=cc60
export CUDA_VERSION=cuda8.0
export GPU_DIRECT=no

export MPI=no
export MPI_LIB=
export MPI_INC=

export OMP=no

# SELF Features

