WriteAttribute_HDF5 – SELF
WriteAttribute_HDF5 Interface
Anti-Capitalist Software License
5 statements
Source File
public interface WriteAttribute_HDF5
Calls
Contents
Module Procedures
WriteAttribute_HDF5_int32 WriteAttribute_HDF5_real WriteAttribute_HDF5_character
Module Procedures
private subroutine WriteAttribute_HDF5_int32(fileId, attributeName, attribute)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: attributeName
integer, intent(in) :: attribute
private subroutine WriteAttribute_HDF5_real(fileId, attributeName, attribute)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: attributeName
real(kind=prec), intent(in) :: attribute
private subroutine WriteAttribute_HDF5_character(fileId, attributeName, attribute)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: attributeName
character, intent(in) :: attribute
Call graph
writeattribute_hdf5 calls writeattribute_hdf5_character, writeattribute_hdf5_real, writeattribute_hdf5_int32
writeattribute_hdf5_character calls h5sclose_f, h5awrite_f, h5acreate_f, h5screate_f, h5aclose_f
writeattribute_hdf5_real calls h5sclose_f, h5awrite_f, h5acreate_f, h5screate_f, h5aclose_f
writeattribute_hdf5_int32 calls h5sclose_f, h5awrite_f, h5acreate_f, h5screate_f, h5aclose_f