
steps:
- id: Build Docker Image
  name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '--build-arg','BUILD_TYPE=${_BUILD_TYPE}',
         '--build-arg','GPU_TARGET=${_SELF_GPU_TARGET}',
         '-f','docker/Dockerfile.${_PLATFORM}',
         '.',
         '-t',
         'gcr.io/self-fluids/self_${_PLATFORM}:${SHORT_SHA}'
  ]

- id: Build Singularity Image
  name: 'quay.io/singularity/singularity:v3.7.1'
  args: ['build',
         'self_${_PLATFORM}.sif',
         'docker-daemon://gcr.io/self-fluids/self_${_PLATFORM}:${SHORT_SHA}']
  waitFor: ["Build Docker Image"]

- id: Fluid CI/CB
  name: 'gcr.io/hpc-apps/fluid-cicb:latest'
  args: 
  - '--build-id=${BUILD_ID}'
  - '--git-sha=${COMMIT_SHA}'
  - '--surface-nonzero-exit-code=True'
  - '--artifact-type=singularity'
  - '--singularity-image=self_${_PLATFORM}.sif'
  - '--project=${PROJECT_ID}'
  - '--zone=${_ZONE}'
  - '--ci-file=.fluidci.json'
  - '--slurm-controller=${_SLURM_CONTROLLER}'
  - '--bq-table=${PROJECT_ID}:fluid_cicb.cloud_build_data'

images: ['gcr.io/self-fluids/self_${_PLATFORM}:${SHORT_SHA}']

artifacts:
  objects:
    location: 'gs://self-fluids-singularity/${SHORT_SHA}'
    paths: ['self_${_PLATFORM}.sif']

timeout: 9600s

substitutions:
  _ZONE: 'us-west1-b'
  _REGION: 'us-west1'
  _SLURM_CONTROLLER: 'fluid-cicb-controller'
  _BUILD_TYPE: 'dev'
  _PLATFORM: 'serial-x86'

