
steps:
- id: Build Docker Image
  name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '--build-arg','GPU_TARGET=${_GPU_TARGET}',
         '--build-arg','HIP_PLATFORM=${_HIP_PLATFORM}',
         '--build-arg','PREC=${_PREC}',
         '--build-arg','FFLAGS=${_FFLAGS}',
         '-f',
         'Dockerfile',
         '.',
         '-t',
         'self:test']

- id: Run Tests (Serial)
  name: 'self:test'
  args: 
  - '-c'
  - | 
      ./ci/test.sh

options:
  diskSizeGb: 100

timeout: 7200s

substitutions:
  _PREC: 'double'
  _GPU_TARGET: 'sm_72'
  _HIP_PLATFORM: 'nvidia'
  _FFLAGS: '-cpp -pg -g -O0 -C -Wall -fbounds-check -fbacktrace --coverage -ffpe-trap=invalid,zero,overflow'


