
steps:
- id: Build Docker Image
  name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '-f','img/base/Dockerfile',
         '.',
         '-t',
         'gcr.io/${PROJECT_ID}/self-base:${SHORT_SHA}',
         '-t',
         'gcr.io/${PROJECT_ID}/self-base:latest'
  ]

images: ['gcr.io/${PROJECT_ID}/self-base:${SHORT_SHA}',
         'gcr.io/${PROJECT_ID}/self-base:latest']

timeout: 14400s
