
steps:
- id: Build Docker Image
  name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '--build-arg','BUILD_TYPE=${_BUILD_TYPE}',
         '--build-arg','GPU_TARGET=${_SELF_GPU_TARGET}',
         '-f','img/docker/Dockerfile.${_PLATFORM}',
         '.',
         '-t',
         'gcr.io/self-fluids/self_${_PLATFORM}:${SHORT_SHA}'
  ]
  waitFor: ["-"]

- id: Build Singularity Image
  name: 'quay.io/singularity/singularity:v3.7.1'
  args: ['build',
         'self_${_PLATFORM}.sif',
         'img/singularity/self_${_PLATFORM}.def']
  waitFor: ["-"]

- id: Generate test batch scripts
  name: 'python:3.7-buster'
  entrypoint: '/usr/local/bin/python'
  env:
  - 'GPU_ACCEL=${_GPU_ACCEL}'
  - 'PARTITIONS=${_PARTITIONS}'
  args: ['ci/test/ciGenerator.py']
  waitFor: ["-"]


images: ['gcr.io/self-fluids/self_${_PLATFORM}:${SHORT_SHA}']

artifacts:
  objects:
    location: 'gs://self-fluids-singularity/${SHORT_SHA}'
    paths: ['self_${_PLATFORM}.sif']

timeout: 9600s

substitutions:
        #_ZONE: 'us-west1-b'
        #_REGION: 'us-west1'
  _BUILD_TYPE: 'dev'
  _PLATFORM: 'serial-x86'
  _SELF_GPU_TARGET: 'none'
  _GPU_ACCEL: 'false'
  _PARTITIONS: 'c2-standard-60'

