
steps:
- id: Build Docker Image
  name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '--build-arg','GPU_TARGET=${_GPU_TARGET}',
         '--build-arg','HIP_PLATFORM=${_HIP_PLATFORM}',
         '--build-arg','PREC=${_PREC}',
         '--build-arg','FFLAGS=${_FFLAGS}',
         '-f',
         'docker/${_HIP_PLATFORM}/Dockerfile',
         '.',
         '-t',
         'self:dev-${_PREC}-${_GPU_TARGET}']


- id: Run Tests & Create Coverage Report (Serial)
  name: 'self:dev-${_PREC}-${_GPU_TARGET}'
  args: 
  - ./test.sh

timeout: 3600s

substitutions:
  _PREC: 'double'
  _GPU_TARGET: 'sm_72'
  _HIP_PLATFORM: 'nvidia'
  _FFLAGS: '-cpp -pg -g -O0 -fbackslash -C -Wall -fbounds-check -fbacktrace --coverage -ffpe-trap=invalid,zero,overflow'
