
steps:
- id: Build Nvidia Image
  name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '.',
         '-f',
         'docker/base/nvidia/Dockerfile',
         '-t',
         'gcr.io/self-fluids/self-base:nvidia-cuda11.2.1-rocm-4.3']

- id: Build AMD Base Image
  name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '.',
         '-f',
         'docker/base/amd/Dockerfile',
         '-t',
         'gcr.io/self-fluids/self-base:amd-rocm-4.3']

images: ['gcr.io/self-fluids/self-base:nvidia-cuda11.2.1-rocm-4.3',
         'gcr.io/self-fluids/self-base:amd-rocm-4.3']


options:
  machineType: 'E2_HIGHCPU_32'
  diskSizeGb: 500

timeout: 14400s
