
steps:
- id: Build Docker Image
  name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '--build-arg','GPU_TARGET=${_GPU_TARGET}',
         '--build-arg','HIP_PLATFORM=${_HIP_PLATFORM}',
         '--build-arg','PREC=${_PREC}',
         '-f','img/Dockerfile',
         '.',
         '-t',
         'gcr.io/${PROJECT_ID}/self:${SHORT_SHA}-${_PREC}-${_GPU_TARGET}']
  waitFor: ["-"]


- id: Convert to Singularity
  name: 'quay.io/singularity/singularity:v3.7.1'
  args: ['build',
         'self.sif',
         'docker-daemon://gcr.io/${PROJECT_ID}/self:${SHORT_SHA}-${_PREC}-${_GPU_TARGET}']
  waitFor: ["Build Docker Image"]

    #- id: Fluid Run
    #  name: 'gcr.io/research-computing-cloud/fluid-run'
    #  args: 
    #  - '--build-id=${BUILD_ID}'
    #  - '--git-sha=${COMMIT_SHA}'
    #  - '--project=${PROJECT_ID}'
    #  - '--zone=${_ZONE}'
    #  - '--gce-image=projects/fluid-cluster-ops/global/images/family/rcc-centos-7-v300'
    #  - '--artifact-type=singularity'
    #  - '--compiler="gcc@9.3.0"'
    #  - '--target-arch=""'
    #  - '--singularity-image=self.sif'
    #  - '--rcc-tfvars=ci/fluid.auto.tfvars'
    #  - '--ci-file=fluid-run.yaml'
    #  - '--save-results'
    #  - '--ignore-job-dependencies'
    #

images: ['gcr.io/${PROJECT_ID}/self:${SHORT_SHA}-${_PREC}-${_GPU_TARGET}']

options:
 machineType: 'E2_HIGHCPU_32'
 diskSizeGb: 500

timeout: 14400s


substitutions:
  #  _ZONE: 'us-west1-b'
  _PREC: 'single'
  _GPU_TARGET: 'sm_72'
  _HIP_PLATFORM: 'nvidia'


