
steps:
- id: Build Docker Image
  name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '--build-arg','GPU_TARGET=${_GPU_TARGET}',
         '--build-arg','HIP_PLATFORM=${_HIP_PLATFORM}',
         '--build-arg','PREC=${_PREC}',
         '--build-arg','FFLAGS=${_FFLAGS}',
         '-f',
         'Dockerfile',
         '.',
         '-t',
         'self:${SHORT_SHA}-${_GPU_TARGET}']

- id: Run Tests (Serial)
  name: 'self:${SHORT_SHA}-${_GPU_TARGET}'
  args: 
  - '-c'
  - | 
      ./ci/test.sh

- id: Upload coverage to codecov
  name: 'gcr.io/${PROJECT_ID}/codecov'
  secretEnv: ['CODECOV_TOKEN']
  entrypoint: "/bin/bash"
  args: 
  - "-c"
  - |
     /usr/local/bin/codecov -t "$$CODECOV_TOKEN" \
                            -R "/build/" \
                            --sha "${COMMIT_SHA}" \
                            --branch "${BRANCH_NAME}" \
                            --pr "${_PR_NUMBER}"

options:
  diskSizeGb: 100
  machineType: 'E2_HIGHCPU_8'

timeout: 14400s

availableSecrets:
  secretManager:
    - versionName: projects/self-fluids/secrets/codecov-token/versions/1
      env: 'CODECOV_TOKEN'

substitutions:
  _PREC: 'double'
  _GPU_TARGET: 'sm_72'
  _HIP_PLATFORM: 'nvidia'
  _FFLAGS: '-cpp -pg -g -O0 -C -Wall -fbounds-check -fbacktrace --coverage -ffpe-trap=invalid,zero,overflow'


