
steps:
- id: Build Docker Image
  name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '--build-arg','GPU_TARGET=${_GPU_TARGET}',
         '-f','img/Dockerfile',
         '.',
         '-t',
         'gcr.io/self-fluids/self_${_GPU_TARGET}:${SHORT_SHA}'
  ]
  waitFor: ["-"]

- id: Generate test batch scripts
  name: 'python:3.7-buster'
  entrypoint: '/usr/local/bin/python'
  env:
  - 'PARTITIONS=${_PARTITIONS}'
  args: ['ci/test/ciGenerator.py']
  waitFor: ["-"]


images: ['gcr.io/self-fluids/self_${_GPU_TARGET}:${SHORT_SHA}']

#artifacts:
#  objects:
#    location: 'gs://self-fluids-singularity/${SHORT_SHA}'
#    paths: ['self_${_PLATFORM}.sif']

timeout: 9600s


substitutions:
  _GPU_TARGET: 'sm_72'
  _PARTITIONS: 'c2-standard-8'
