
steps:
- id: Build Docker Image
  name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '--build-arg','GPU_TARGET=${_GPU_TARGET}',
         '--build-arg','HIP_PLATFORM=${_HIP_PLATFORM}',
         '--build-arg','PREC=${_PREC}',
         '--build-arg','FFLAGS=${_FFLAGS}',
         '--build-arg','ROCM_VERSION=${_ROCM_VERSION}',
         '-f',
         'Dockerfile',
         '.',
         '-t',
         'us-docker.pkg.dev/${PROJECT_ID}/self/base_rocm-${_ROCM_VERSION}_cuda-11.8.0_${_GPU_TARGET}_${_PREC}:dev']

images:
- 'us-docker.pkg.dev/${PROJECT_ID}/self/base_rocm-${_ROCM_VERSION}_cuda-11.8.0_${_GPU_TARGET}_${_PREC}:dev'

options:
  diskSizeGb: 100
  machineType: 'E2_HIGHCPU_8'

timeout: 14400s

substitutions:
  _PREC: 'double'
  _GPU_TARGET: 'gfx900'
  _HIP_PLATFORM: 'amd'
  _FFLAGS: '-cpp -pg -g -O0 -C -Wall -fbounds-check -fbacktrace --coverage -ffpe-trap=invalid,zero,overflow'
  _ROCM_VERSION: '5.2.3'
