
steps:
- id: Build Docker Image
  name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '--build-arg','GPU_TARGET=${_GPU_TARGET}',
         '-f','img/Dockerfile',
         '.',
         '-t',
         'gcr.io/${PROJECT_ID}/self_${_GPU_TARGET}:${SHORT_SHA}']

- id: Build Singularity Image
  name: 'quay.io/singularity/singularity:v3.7.1'
  args: ['build',
         'self_${_GPU_TARGET}.sif',
         'img/self.def']
  waitFor: ["-"]

- id: Generate test batch scripts
  name: 'python:3.7-buster'
  entrypoint: '/usr/local/bin/python'
  env:
  - 'PARTITIONS=${_PARTITIONS}'
  args: ['ci/test/ciGenerator.py']
  waitFor: ["-"]

- id: CI/CB
  name: 'gcr.io/research-computing-cloud/fluid-run'
  args: 
  - '--build-id=${BUILD_ID}'
  - '--git-sha=${COMMIT_SHA}'
  - '--project=${PROJECT_ID}'
  - '--zone=${_ZONE}'
  - '--artifact-type=singularity'
  - '--compiler="gcc@9.3.0"'
  - '--target-arch=""'
  - '--singularity-image=self_${_GPU_TARGET}.sif'
  - '--rcc-tfvars=ci/fluid.auto.tfvars'
  - '--ci-file=fluid-run.json'
  - '--save-results'
  - '--ignore-job-dependencies'


images: ['gcr.io/self-fluids/self_${_GPU_TARGET}:${SHORT_SHA}']

artifacts:
  objects:
    location: 'gs://self-fluids-singularity/${SHORT_SHA}'
    paths: ['self_${_GPU_TARGET}.sif']


options:
 machineType: 'E2_HIGHCPU_32'
 diskSizeGb: 50

timeout: 9600s


substitutions:
  _GPU_TARGET: 'sm_72'
  _ZONE: 'us-west1-b'
  _PARTITIONS: 'c2-standard-4'


