
steps:
- id: Build Docker Image
  name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '--build-arg','GPU_TARGET=${_GPU_TARGET}',
         '--build-arg','HIP_PLATFORM=${_HIP_PLATFORM}',
         '--build-arg','PREC=${_PREC}',
         '-f',
         'docker/nvidia/Dockerfile',
         '.',
         '-t',
         'gcr.io/${PROJECT_ID}/self:dev-${_PREC}-${_GPU_TARGET}']

- id: Run Tests (Serial)
  name: 'self:dev-${_PREC}-${_GPU_TARGET}'
  args: 
  - '-c'
  - | 
      ./ci/serial_cb_test.sh

- id: Upload coverage to codecov
  name: 'gcr.io/${PROJECT_ID}/codecov'
  secretEnv: ['CODECOV_TOKEN']
  args: ['-t', '$$CODECOV_TOKEN',
         '-R', '/build/',
         '--sha', '${COMMIT_SHA}',
         '--branch', '${BRANCH_NAME}',
         '--pr', '${_PR_NUMBER}']

images: ['gcr.io/${PROJECT_ID}/self:dev-${_PREC}-${_GPU_TARGET}']

options:
  diskSizeGb: 100

availableSecrets:
  secretManager:
    - versionName: projects/self-fluids/secrets/codecov-token/versions/1
      env: 'CODECOV_TOKEN'

timeout: 7200s

substitutions:
  _PREC: 'single'
  _GPU_TARGET: 'sm_72'
  _HIP_PLATFORM: 'nvidia'
  _TARGET_ARCH: 'x86_64'
  _COMPILER: 'gcc@9.4.0'
  _ZONE: 'us-west1-b'


