#!/bin/bash


# Build Singularity Image
singularity build --fakeroot self-nvidia.sif img/Singularity.nvidia

# Clear out code coverage output directory
rm -rf $(pwd)/ci/test/codecov
mkdir -p $(pwd)/ci/test/codecov

# Run the tests within the singularity container
singularity run --bind $(pwd)/ci/test/codecov:/build self-nvidia.sif $(pwd)/ci/test/localRun.py
