Determinant – SELF
Determinant Function
Anti-Capitalist Software License
18 statements
Source File
public recursive function Determinant(A, N) result(D)
\addtogroup SELF_SupportRoutines @{ \fn Determinant A recursive function that calculates the determinant of an \f$ N\times N \f$ matrix.
This function is used in the functions \ref invert_2x2 and \ref invert_3x3
This function depends on
Function \ref getminor
Usage :
INTEGER :: N REAL(prec) :: A(1:N,1:N), D
....
D = Determinant(A, N)
Parameters :
in A(1:N,1:N) REAL(prec) Square matrix
in N INTEGER Dimension of the matrix
out detA REAL(prec) The determinant of the matrix
@}
Arguments
Type Intent Optional Attributes Name
real(kind=prec) :: A(1:N,1:N)
integer :: N
Return Value real(kind=prec)
Calls
Called by
Contents
Source Code
Determinant
Source Code
  RECURSIVE FUNCTION Determinant(A,N) RESULT(D)
    IMPLICIT NONE
    INTEGER    :: N
    REAL(prec) :: A(1:N,1:N)
    REAL(prec) :: D
    ! LOCAL
    REAL(prec) :: M(1:N - 1,1:N - 1)
    INTEGER    :: j
    IF (N == 2) THEN
      D = A(1,1)*A(2,2) - A(1,2)*A(2,1)
      RETURN
    ELSE
      D = 0.0_prec
      DO j = 1,N
        M = GetMinor(A,1,j,N)
        D = D + (-1.0_prec)**(j + 1)*A(1,j)*Determinant(M,N - 1)
      END DO
    END IF
  END FUNCTION Determinant
Call graph
determinant calls determinant, getminor
invert_2x2 calls determinant
invert_3x3 calls determinant