InitFromCLI_Advection2D – SELF
InitFromCLI_Advection2D Subroutine
Anti-Capitalist Software License
152 statements
Source File
public subroutine InitFromCLI_Advection2D(this)
Arguments
Type Intent Optional Attributes Name
class(Advection2D), intent(inout) :: this
Calls
Contents
Source Code
InitFromCLI_Advection2D
Source Code
  SUBROUTINE InitFromCLI_Advection2D(this)
    IMPLICIT NONE
    CLASS(Advection2D),INTENT(inout) :: this
    ! Local
    TYPE(COMMAND_LINE_INTERFACE) :: cli
    TYPE(MeshSpec) :: spec
    CHARACTER(self_QuadratureTypeCharLength) :: cqTypeChar
    CHARACTER(self_QuadratureTypeCharLength) :: tqTypeChar
    CHARACTER(self_IntegratorTypeCharLength) :: integratorChar
    REAL(prec) :: Lx, Ly ! Domain lengths
    REAL(prec) :: dt ! Default time step size
    REAL(prec) :: diffusivity
    INTEGER :: controlDegree
    INTEGER :: targetDegree
    INTEGER :: controlQuadrature ! ENUMS in SELF_Constants.f90
    INTEGER :: targetQuadrature ! ENUMS in SELF_Constants.f90
    CHARACTER(LEN=self_FileNameLength) :: meshFile
    INTEGER :: nxElements
    INTEGER :: nyElements
    INTEGER :: integrator ! ENUMS needed in SELF_Constants.f90 !! TO DO !!
    CHARACTER(LEN=self_EquationLength) :: velEqnX ! Velocity Equation (x-direction)
    CHARACTER(LEN=self_EquationLength) :: velEqnY ! Velocity Equation (y-direction)
    CHARACTER(LEN=self_EquationLength) :: icEqn ! Initial condition Equation
    CHARACTER(LEN=self_EquationLength) :: bcEqn ! Boundary condition Equation
    CHARACTER(LEN=self_EquationLength) :: sourceEqn ! Boundary condition Equation
    LOGICAL :: enableMPI
    LOGICAL :: enableGPU
    LOGICAL :: diffusiveFlux
    REAL(prec) :: outputInterval
    REAL(prec) :: initialTime
    REAL(prec) :: endTime
    TYPE(EquationParser) :: eqn(1)
    TYPE(EquationParser) :: velEqn(1:2)
    ! Get the CLI parameters !
    CALL GetCLIParameters(cli)
    ! Set the CLI parameters !
    CALL cli % get(val=enableMPI,switch='--mpi')
    CALL cli % get(val=enableGPU,switch='--gpu')
    CALL cli % get(val=meshfile,switch='--mesh')
    CALL cli % get(val=dt,switch="--time-step")
    CALL cli % get(val=outputInterval,switch="--output-interval")
    CALL cli % get(val=initialTime,switch="--initial-time")
    CALL cli % get(val=endTime,switch="--end-time")
    CALL cli % get(val=controlDegree,switch="--control-degree")
    CALL cli % get(val=targetDegree,switch="--target-degree")
    CALL cli % get(val=cqTypeChar,switch="--control-quadrature")
    CALL cli % get(val=tqTypeChar,switch="--target-quadrature")
    CALL cli % get(val=meshFile,switch="--mesh")
    CALL cli % get(val=nxElements,switch="--nxelements")
    CALL cli % get(val=nyElements,switch="--nyelements")
    CALL cli % get(val=Lx, switch="--xlength")
    CALL cli % get(val=Ly, switch="--ylength")
    CALL cli % get(val=velEqnX,switch="--velocity-x")
    CALL cli % get(val=velEqnY,switch="--velocity-y")
    CALL cli % get(val=icEqn,switch="--initial-condition")
    CALL cli % get(val=bcEqn,switch="--boundary-condition")
    CALL cli % get(val=sourceEqn,switch="--source")
    CALL cli % get(val=integratorChar,switch="--integrator")
    CALL cli % get(val=diffusivity,switch="--diffusivity")
    diffusiveFlux = .TRUE.
    IF( diffusivity == 0.0_prec ) THEN
      diffusiveFlux = .FALSE.
    ELSEIF( diffusivity < 0.0_prec ) THEN
      IF( dt > 0.0_prec )THEN
        PRINT*, 'Negative diffusivity provably unstable for forward stepping'
        PRINT*, 'Invalid diffusivity value. Stopping'
        STOP
      ENDIF
    ENDIF
    IF (TRIM(UpperCase(cqTypeChar)) == 'GAUSS') THEN
      controlQuadrature = GAUSS
    ELSEIF (TRIM(UpperCase(cqTypeChar)) == 'GAUSS-LOBATTO') THEN
      controlQuadrature = GAUSS_LOBATTO
    ELSEIF (TRIM(UpperCase(cqTypeChar)) == 'CHEBYSHEV-GAUSS') THEN
      controlQuadrature = CHEBYSHEV_GAUSS
    ELSEIF (TRIM(UpperCase(cqTypeChar)) == 'CHEBYSHEV-GAUSS-LOBATTO') THEN
      controlQuadrature = CHEBYSHEV_GAUSS_LOBATTO
    ELSE
      PRINT *, 'Invalid Control Quadrature'
      STOP - 1
    END IF
    IF (TRIM(UpperCase(tqTypeChar)) == 'UNIFORM') THEN
      targetQuadrature = UNIFORM
    ELSEIF (TRIM(UpperCase(tqTypeChar)) == 'GAUSS') THEN
      targetQuadrature = GAUSS
    ELSEIF (TRIM(UpperCase(tqTypeChar)) == 'GAUSS-LOBATTO') THEN
      targetQuadrature = GAUSS_LOBATTO
    ELSEIF (TRIM(UpperCase(tqTypeChar)) == 'CHEBYSHEV-GAUSS') THEN
      targetQuadrature = CHEBYSHEV_GAUSS
    ELSEIF (TRIM(UpperCase(tqTypeChar)) == 'CHEBYSHEV-GAUSS-LOBATTO') THEN
      targetQuadrature = CHEBYSHEV_GAUSS_LOBATTO
    ELSE
      PRINT *, 'Invalid Target Quadrature'
      STOP - 1
    END IF
    IF (TRIM(UpperCase(integratorChar)) == 'EULER') THEN
      integrator = EULER
    ELSEIF (TRIM(UpperCase(integratorChar)) == 'WILLIAMSON_RK3') THEN
      integrator = RK3
    ELSE
      PRINT *, 'Invalid time integrator'
      STOP - 1
    END IF
    IF( TRIM(meshfile) == "" )THEN
      spec % blockMesh = .TRUE.
    ELSE
      spec % blockMesh = .FALSE.
    ENDIF
    spec % filename = meshfile
    spec % filetype = SELF_MESH_ISM_V2_2D
    spec % blockMesh_nGeo = 1
    spec % blockMesh_x0 = 0.0_prec
    spec % blockMesh_x1 = Lx
    spec % blockMesh_y0 = 0.0_prec
    spec % blockMesh_y1 = Ly
    spec % blockMesh_z0 = 0.0_prec
    spec % blockMesh_z1 = 0.0_prec
    spec % blockMesh_nElemX = nxElements
    spec % blockMesh_nElemY = nyElements
    spec % blockMesh_nElemZ = 0 ! 2-D mesh !
    CALL this % Init(controlQuadrature, &
                     targetQuadrature, &
                     controlDegree, &
                     targetDegree, &
                     1,enableMPI, &
                     spec)
    this % simulationTime = 0.0_prec
    this % Lx = Lx
    this % Ly = Ly ! Domain lengths
    this % dt = dt ! Default time step size
    this % initialTime = initialTime
    this % simulationTime = initialTime
    this % endTime = endTime
    this % outputInterval = outputInterval
    this % controlDegree = controlDegree
    this % targetDegree = targetDegree
    this % controlQuadrature = controlQuadrature ! ENUMS in SELF_Constants.f90
    this % targetQuadrature = targetQuadrature ! ENUMS in SELF_Constants.f90
    this % meshFile = meshFile
    this % nxElements = nxElements
    this % nyElements = nyElements
    this % integrator = integrator ! ENUMS needed in SELF_Constants.f90 !! TO DO !!
    this % velEqnX = velEqnX ! Velocity Equation (x-direction)
    this % velEqnY = velEqnY ! Velocity Equation (y-direction)
    this % icEqn = icEqn ! Initial condition Equation
    this % bcEqn = bcEqn ! Boundary condition Equation
    this % enableMPI = enableMPI
    this % gpuAccel = enableGPU
    this % diffusivity = diffusivity
    this % diffusiveFlux = diffusiveFlux
    eqn(1) = EquationParser( icEqn, (/'x','y', 't'/))
    CALL this % SetSolution( eqn )
    this % solutionEqn(1) = EquationParser( icEqn, (/'x','y','t'/))
    velEqn(1) = EquationParser(velEqnX, (/'x','y'/))
    velEqn(2) = EquationParser(velEqnY, (/'x','y'/))
    CALL this % SetVelocity( velEqn )
    this % boundaryConditionEqn(1) = EquationParser( bcEqn, (/'x','y','t'/))
    CALL this % SetBoundaryCondition( this % boundaryConditionEqn )
    this % sourceEqn(1) = EquationParser( sourceEqn, (/'x','y','t'/))
  END SUBROUTINE InitFromCLI_Advection2D
Call graph
initfromcli_advection2d calls uppercase, getcliparameters, equationparser