Init_Lagrange – SELF
Init_Lagrange Subroutine
Anti-Capitalist Software License
38 statements
Source File
public subroutine Init_Lagrange(myPoly, N, controlNodeType, M, targetNodeType)
Initialize an instance of the Lagrange class On output, all of the attributes for the Lagrange class are allocated and values are initialized according to the number of control points, number of target points, and the types for the control and target nodes. If a GPU is available, device pointers for the Lagrange attributes are allocated and initialized.
Arguments
Type Intent Optional Attributes Name
class(Lagrange), intent(out) :: myPoly
Lagrange class instance
integer, intent(in) :: N
The number of control points for interpolant
integer, intent(in) :: controlNodeType
The integer code specifying the type of control points. Parameters are defined in SELF_Constants.f90. One of GAUSS(=1), GAUSS_LOBATTO(=2), or UNIFORM(=3)
integer, intent(in) :: M
The number of target points for the interpolant
integer, intent(in) :: targetNodeType
The integer code specifying the type of target points. Parameters are defined in SELF_Constants.f90. One of GAUSS(=1), GAUSS_LOBATTO(=2), or UNIFORM(=3)
Calls
Contents
Source Code
Init_Lagrange
Source Code
  SUBROUTINE Init_Lagrange(myPoly,N,controlNodeType,M,targetNodeType)
    !! Initialize an instance of the Lagrange class
    !! On output, all of the attributes for the Lagrange class are allocated and values are initialized according to the number of
    !! control points, number of target points, and the types for the control and target nodes.
    !! If a GPU is available, device pointers for the Lagrange attributes are allocated and initialized.
    IMPLICIT NONE
    CLASS(Lagrange),INTENT(out) :: myPoly
    !! Lagrange class instance
    INTEGER,INTENT(in)          :: N
    !! The number of control points for interpolant
    INTEGER,INTENT(in)          :: M
    !! The number of target points for the interpolant
    INTEGER,INTENT(in)          :: controlNodeType
    !! The integer code specifying the type of control points. Parameters are defined in SELF_Constants.f90. One of GAUSS(=1),
    !! GAUSS_LOBATTO(=2), or UNIFORM(=3)
    INTEGER,INTENT(in)          :: targetNodeType
    !! The integer code specifying the type of target points. Parameters are defined in SELF_Constants.f90. One of GAUSS(=1),
    !! GAUSS_LOBATTO(=2), or UNIFORM(=3)
    ! -------!
    ! Local
    REAL(prec) :: q(0:M)
    myPoly % N = N
    myPoly % M = M
    CALL myPoly % controlPoints % Alloc(loBound=0, &
                                        upBound=N)
    CALL myPoly % targetPoints % Alloc(loBound=0, &
                                       upBound=M)
    CALL myPoly % bWeights % Alloc(loBound=0, &
                                   upBound=N)
    CALL myPoly % qWeights % Alloc(loBound=0, &
                                   upBound=N)
    CALL myPoly % iMatrix % Alloc(loBound=(/0,0/), &
                                  upBound=(/N,M/))
    CALL myPoly % dMatrix % Alloc(loBound=(/0,0/), &
                                  upBound=(/N,N/))
    CALL myPoly % dgMatrix % Alloc(loBound=(/0,0/), &
                                   upBound=(/N,N/))
    CALL myPoly % bMatrix % Alloc(loBound=(/0,0/), &
                                  upBound=(/N,1/))
    IF (controlNodeType == GAUSS .OR. controlNodeType == GAUSS_LOBATTO) THEN
      CALL LegendreQuadrature(N, &
                              myPoly % controlPoints % hostData, &
                              myPoly % qWeights % hostData, &
                              controlNodeType)
    ELSEIF (controlNodeType == CHEBYSHEV_GAUSS .OR. controlNodeType == CHEBYSHEV_GAUSS_LOBATTO) THEN
      CALL ChebyshevQuadrature(N, &
                               myPoly % controlPoints % hostData, &
                               myPoly % qWeights % hostData, &
                               controlNodeType)
    ELSEIF (controlNodeType == UNIFORM) THEN
      myPoly % controlPoints % hostData = UniformPoints(-1.0_prec,1.0_prec,0,N)
      myPoly % qWeights % hostData = 2.0_prec/REAL(N,prec)
    END IF
    ! Target Points
    IF (targetNodeType == GAUSS .OR. targetNodeType == GAUSS_LOBATTO) THEN
      CALL LegendreQuadrature(M, &
                              myPoly % targetPoints % hostData, &
                              q, &
                              targetNodeType)
    ELSEIF (targetNodeType == UNIFORM) THEN
      myPoly % targetPoints % hostData = UniformPoints(-1.0_prec,1.0_prec,0,M)
    END IF
    CALL myPoly % CalculateBarycentricWeights()
    CALL myPoly % CalculateInterpolationMatrix()
    CALL myPoly % CalculateDerivativeMatrix()
    myPoly % bMatrix % hostData(0:N,0) = myPoly % CalculateLagrangePolynomials(-1.0_prec)
    myPoly % bMatrix % hostData(0:N,1) = myPoly % CalculateLagrangePolynomials(1.0_prec)
    CALL myPoly % UpdateDevice()
  END SUBROUTINE Init_Lagrange
Call graph
init_lagrange calls legendrequadrature, uniformpoints, chebyshevquadrature