ReadArray_HDF5_int32_r2_parallel – SELF
ReadArray_HDF5_int32_r2_parallel Subroutine
Anti-Capitalist Software License
30 statements
Source File
private subroutine ReadArray_HDF5_int32_r2_parallel(fileId, arrayName, hfArray, offset)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfInt32_r2), intent(inout) :: hfArray
integer(kind=HID_T), intent(in) :: offset(1:2)
Calls
Called by
Contents
Source Code
ReadArray_HDF5_int32_r2_parallel
Source Code
  SUBROUTINE ReadArray_HDF5_int32_r2_parallel(fileId,arrayName,hfArray,offset)
    IMPLICIT NONE
    INTEGER(HID_T),INTENT(in) :: fileId
    CHARACTER(*),INTENT(in) :: arrayName
    INTEGER(HID_T),INTENT(in) :: offset(1:2)
    TYPE(hfInt32_r2),INTENT(inout) :: hfArray
    ! Local
    INTEGER(HID_T) :: plistId
    INTEGER(HID_T) :: dsetId
    INTEGER(HID_T) :: dtypeId
    INTEGER(HID_T) :: filespace
    INTEGER(HID_T) :: memspace
    INTEGER(HID_T) :: dims(1:2)
    INTEGER :: error
    INTEGER :: aRank
    aRank = RANK(hfArray % hostData)
    dims = SHAPE(hfArray % hostData)
    CALL h5screate_simple_f(aRank,dims,memspace,error)
    CALL h5dopen_f(fileId,arrayName,dsetId,error)
    CALL h5dget_space_f(dsetId,filespace,error)
    CALL h5sselect_hyperslab_f(filespace,H5S_SELECT_SET_F,offset,dims,error)
    CALL h5pcreate_f(H5P_DATASET_XFER_F,plistId,error)
    CALL h5pset_dxpl_mpio_f(plistId,H5FD_MPIO_COLLECTIVE_F,error)
    CALL h5dget_type_f(dsetId,dtypeId,error)
    CALL h5dread_f(dsetId,dtypeId,hfArray % hostData,dims, &
                   error,memspace,filespace,plistId)
    CALL h5tclose_f(dtypeId,error)
    CALL h5pclose_f(plistId,error)
    CALL h5sclose_f(filespace,error)
    CALL h5dclose_f(dsetId,error)
    CALL h5sclose_f(memspace,error)
  END SUBROUTINE ReadArray_HDF5_int32_r2_parallel
Call graph
readarray_hdf5_int32_r2_parallel calls h5tclose_f, h5pset_dxpl_mpio_f, h5pclose_f, h5dopen_f, h5screate_simple_f, h5dclose_f, h5sclose_f, h5sselect_hyperslab_f, h5dget_type_f, h5dread_f, h5pcreate_f, h5dget_space_f
readarray_hdf5 calls readarray_hdf5_int32_r2_parallel