ReadArray_HDF5_int32_r7_serial – SELF
ReadArray_HDF5_int32_r7_serial Subroutine
Anti-Capitalist Software License
17 statements
Source File
private subroutine ReadArray_HDF5_int32_r7_serial(fileId, arrayName, hfArray)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
type(hfInt32_r7), intent(inout) :: hfArray
Calls
Called by
Contents
Source Code
ReadArray_HDF5_int32_r7_serial
Source Code
  SUBROUTINE ReadArray_HDF5_int32_r7_serial(fileId,arrayName,hfArray)
    IMPLICIT NONE
    INTEGER(HID_T),INTENT(in) :: fileId
    CHARACTER(*),INTENT(in) :: arrayName
    TYPE(hfInt32_r7),INTENT(inout) :: hfArray
    ! Local
    INTEGER(HID_T) :: dsetId
    INTEGER(HID_T) :: dtypeId
    INTEGER(HID_T) :: dims(1:7)
    INTEGER :: error
    INTEGER :: aRank
    aRank = RANK(hfArray % hostData)
    CALL h5dopen_f(fileId,arrayName,dsetId,error)
    CALL h5dget_type_f(dsetId,dtypeId,error)
    CALL h5dread_f(dsetId,dtypeId,hfArray % hostData,dims,error)
    CALL h5tclose_f(dtypeId,error)
    CALL h5dclose_f(dsetId,error)
  END SUBROUTINE ReadArray_HDF5_int32_r7_serial
Call graph
readarray_hdf5_int32_r7_serial calls h5tclose_f, h5dopen_f, h5dclose_f, h5dget_type_f, h5dread_f
readarray_hdf5 calls readarray_hdf5_int32_r7_serial