Read_DG2D – SELF
Read_DG2D Subroutine
Anti-Capitalist Software License
26 statements
Source File
public subroutine Read_DG2D(this, fileName)
Arguments
Type Intent Optional Attributes Name
class(DG2D), intent(inout) :: this
character, intent(in) :: fileName
Calls
Contents
Source Code
Read_DG2D
Source Code
  SUBROUTINE Read_DG2D(this,fileName)
    IMPLICIT NONE
    CLASS(DG2D),INTENT(inout) :: this
    CHARACTER(*),INTENT(in) :: fileName
    ! Local
    INTEGER(HID_T) :: fileId
    INTEGER(HID_T) :: solOffset(1:4)
    INTEGER :: firstElem
    INTEGER :: N
    IF (this % decomp % mpiEnabled) THEN
      CALL Open_HDF5(fileName,H5F_ACC_RDWR_F,fileId, &
                     this % decomp % mpiComm)
    ELSE
      CALL Open_HDF5(fileName,H5F_ACC_RDWR_F,fileId)
    END IF
    CALL ReadAttribute_HDF5(fileId,'N',N)
    IF (this % solution % interp % N /= N) THEN
      STOP 'Error : Solution polynomial degree does not match input file'
    END IF
    IF (this % decomp % mpiEnabled) THEN
      firstElem = this % decomp % offsetElem % hostData(this % decomp % rankId) + 1
      solOffset(1:4) = (/0,0,1,firstElem/)
      CALL ReadArray_HDF5(fileId,'/state/interior/solution', &
                          this % solution % interior,solOffset)
    ELSE
      CALL ReadArray_HDF5(fileId,'/state/interior/solution',this % solution % interior)
    END IF
    CALL Close_HDF5(fileId)
  END SUBROUTINE Read_DG2D
Call graph
read_dg2d calls readattribute_hdf5, readarray_hdf5, open_hdf5, close_hdf5