TensorInterp2D_Test – SELF
TensorInterp2D_Test Subroutine
98 statements
Source File
public subroutine TensorInterp2D_Test(cqType, tqType, cqDegree, tqDegree, nElem, nVar, tensorChar, tolerance, gpuAccel, error)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: cqType
integer, intent(in) :: tqType
integer, intent(in) :: cqDegree
integer, intent(in) :: tqDegree
integer, intent(in) :: nElem
integer, intent(in) :: nVar
character(len=240), intent(in) :: tensorChar(1:2,1:2)
real(kind=prec), intent(in) :: tolerance
logical, intent(in) :: gpuAccel
integer, intent(out) :: error
Calls
Contents
Source Code
TensorInterp2D_Test
Source Code
  SUBROUTINE TensorInterp2D_Test(cqType,tqType,cqDegree,tqDegree,nElem,nvar,&
                                 tensorChar,tolerance,gpuAccel,error)
#undef __FUNC__
#define __FUNC__ "TensorInterp2D_Test"
    IMPLICIT NONE
    INTEGER,INTENT(in) :: cqType
    INTEGER,INTENT(in) :: tqType
    INTEGER,INTENT(in) :: cqDegree
    INTEGER,INTENT(in) :: tqDegree
    INTEGER,INTENT(in) :: nElem
    INTEGER,INTENT(in) :: nVar
    CHARACTER(240),INTENT(in) :: tensorChar(1:2,1:2)
    REAL(prec),INTENT(in) :: tolerance
    LOGICAL,INTENT(in) :: gpuAccel
    INTEGER,INTENT(out) :: error
    ! Local
    CHARACTER(240) :: msg
    TYPE(Mesh2D) :: controlMesh,targetMesh
    TYPE(SEMQuad) :: controlGeometry,targetGeometry
    TYPE(EquationParser)  :: tensorEq(1:2,1:2)
    TYPE(Tensor2D) :: f,fInterp,fActual,fError
    REAL(prec) :: maxErrors(1:nvar)
    INTEGER :: nel,iel,jel
    INTEGER :: i,j,ivar
    INTEGER :: row,col
    nel = nElem*nElem
    error = 0
    msg = 'Number of elements : '//Int2Str(nEl)
    INFO(TRIM(msg))
    msg = 'Number of control points : '//Int2Str(cqDegree)
    INFO(TRIM(msg))
    msg = 'Number of target points : '//Int2Str(tqDegree)
    INFO(TRIM(msg))
    msg = 'Number of variables : '//Int2Str(nvar)
    INFO(TRIM(msg))
    INFO('Error tolerance : '//Float2Str(tolerance))
    ! Create the control mesh and geometry
    CALL controlMesh % UniformBlockMesh(cqDegree, &
                                        (/nElem,nElem/), &
                                        (/0.0_prec,1.0_prec, &
                                          0.0_prec,1.0_prec/))
    CALL controlGeometry % GenerateFromMesh(controlMesh,cqType,tqType,cqDegree,tqDegree)
    ! Create the target mesh and geometry
    CALL targetMesh % UniformBlockMesh(tqDegree, &
                                       (/nElem,nElem/), &
                                       (/0.0_prec,1.0_prec, &
                                         0.0_prec,1.0_prec/))
    CALL targetGeometry % GenerateFromMesh(targetMesh,tqType,tqType,tqDegree,tqDegree)
    ! Create the scalar1d objects
    CALL f % Init(cqDegree,cqType,tqDegree,tqType,nvar,nEl)
    CALL fInterp % Init(tqDegree,tqType,tqDegree,tqType,nvar,nEl)
    CALL fActual % Init(tqDegree,tqType,tqDegree,tqType,nvar,nEl)
    CALL fError % Init(tqDegree,tqType,tqDegree,tqType,nvar,nEl)
    ! Create the equation parser object
    DO col = 1,2
      DO row = 1,2
        tensorEq(row,col) = EquationParser(TRIM(tensorChar(row,col)), (/'x','y'/))
      ENDDO
    ENDDO
    ! Load the control function
    DO iel = 1, nel
      DO ivar = 1, nvar
        DO j = 0, cqDegree
          DO i = 0, cqDegree
            DO col = 1,2
              DO row = 1,2
                f % interior % hostData(row,col,i,j,ivar,iel) = &
                  tensorEq(row,col) % Evaluate( controlGeometry % x % interior % hostData(1:2,i,j,1,iel) )
              ENDDO
            ENDDO
          ENDDO
        ENDDO
      ENDDO
    ENDDO
    ! Load the target function
    DO iel = 1, nel
      DO ivar = 1, nvar
        DO j = 0, tqDegree
          DO i = 0, tqDegree
            DO col = 1,2
              DO row = 1,2
               fActual % interior % hostData(row,col,i,j,ivar,iel) = &
                 tensorEq(row,col) % Evaluate( targetGeometry % x % interior % hostData(1:2,i,j,1,iel) )
              ENDDO
            ENDDO
          ENDDO
        ENDDO
      ENDDO
    ENDDO
#ifdef GPU
    IF (gpuAccel) THEN
      CALL f % UpdateDevice()
    END IF
#endif
    ! Run the grid interpolation
    CALL f % GridInterp(fInterp,gpuAccel)
#ifdef GPU
    IF (gpuAccel) THEN
      CALL fInterp % UpdateHost()
    END IF
#endif
    fError = fActual - fInterp
    ! Calculate Absolute Maximum Error
    maxErrors = fError % AbsMaxInterior( )
    msg = "Numerical Error : "//Float2Str(maxErrors(1))
    IF (maxErrors(1) > tolerance) THEN
      error = error + 1
      ERROR(TRIM(msg))
      ERROR("Status : [FAIL]")
    ELSE
      INFO(TRIM(msg))
      INFO("Status : [PASS]")
    END IF
    ! Clean up
    CALL controlMesh % Free()
    CALL controlGeometry % Free()
    CALL targetMesh % Free()
    CALL targetGeometry % Free()
    CALL f % Free()
    CALL fInterp % Free()
    CALL fActual % Free()
    CALL fError % Free()
  END SUBROUTINE TensorInterp2D_Test
Call graph
tensorinterp2d_test calls int2str, equationparser, float2str, info