VectorGradient3D_Test – SELF
VectorGradient3D_Test Subroutine
113 statements
Source File
public subroutine VectorGradient3D_Test(cqType, tqType, cqDegree, tqDegree, dForm, nElem, nVar, vectorChar, tensorChar, tolerance, gpuAccel, error)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: cqType
integer, intent(in) :: tqType
integer, intent(in) :: cqDegree
integer, intent(in) :: tqDegree
integer, intent(in) :: dForm
integer, intent(in) :: nElem
integer, intent(in) :: nVar
character(len=240), intent(in) :: vectorChar(1:3)
character(len=240), intent(in) :: tensorChar(1:3,1:3)
real(kind=prec), intent(in) :: tolerance
logical, intent(in) :: gpuAccel
integer, intent(out) :: error
Calls
Called by
Contents
Source Code
VectorGradient3D_Test
Source Code
  SUBROUTINE VectorGradient3D_Test(cqType,tqType,cqDegree,tqDegree,dForm,nElem,nvar,&
                                   vectorChar,tensorChar,tolerance,gpuAccel,error)
#undef __FUNC__
#define __FUNC__ "VectorGradient3D_Test"
    IMPLICIT NONE
    INTEGER,INTENT(in) :: cqType
    INTEGER,INTENT(in) :: tqType
    INTEGER,INTENT(in) :: cqDegree
    INTEGER,INTENT(in) :: tqDegree
    INTEGER,INTENT(in) :: dForm
    INTEGER,INTENT(in) :: nElem
    INTEGER,INTENT(in) :: nVar
    CHARACTER(240),INTENT(in) :: vectorChar(1:3)
    CHARACTER(240),INTENT(in) :: tensorChar(1:3,1:3)
    REAL(prec),INTENT(in) :: tolerance
    LOGICAL,INTENT(in) :: gpuAccel
    INTEGER,INTENT(out) :: error
    ! Local
    CHARACTER(240) :: msg
    TYPE(Mesh3D) :: controlMesh
    TYPE(SEMHex) :: controlGeometry
    TYPE(EquationParser)  :: feq(1:3),dfeqChar(1:3,1:3)
    TYPE(MappedVector3D) :: f
    TYPE(MappedScalar3D) :: workScalar
    TYPE(MappedVector3D) :: workVector
    TYPE(MappedTensor3D) :: workTensor
    TYPE(MappedTensor3D) :: dfInterp,dfActual,dfError
    REAL(prec) :: maxErrors(1:nvar)
    INTEGER :: iel,i,j,k,ivar,row,col,iside
    error = 0
    IF (dForm == selfStrongForm ) THEN
      msg = 'Formulation Type : Strong Form'
    ELSEIF (dForm == selfWeakDGForm ) THEN
      msg = 'Formulation Type : Weak DG Form'
    ELSEIF (dForm == selfWeakCGForm ) THEN
      msg = 'Formulation Type : Weak CG Form'
    ENDIF
    INFO(TRIM(msg))
    msg = 'Number of elements : '//Int2Str(nElem)
    msg = 'Number of elements : '//Int2Str(nElem*nElem*nElem)
    INFO(TRIM(msg))
    msg = 'Number of control points : '//Int2Str(cqDegree)
    INFO(TRIM(msg))
    msg = 'Number of target points : '//Int2Str(tqDegree)
    INFO(TRIM(msg))
    msg = 'Number of variables : '//Int2Str(nvar)
    INFO(TRIM(msg))
    msg = 'Error tolerance : '//Float2Str(tolerance)
    INFO(TRIM(msg))
    ! Create the control mesh and geometry
    CALL controlMesh % UniformBlockMesh(cqDegree, &
                                        (/nElem,nElem,nElem/), &
                                        (/0.0_prec,1.0_prec, &
                                          0.0_prec,1.0_prec, &
                                          0.0_prec,1.0_prec/))
    CALL controlGeometry % GenerateFromMesh(controlMesh,cqType,tqType,cqDegree,tqDegree)
    ! Create the scalar1d objects
    CALL f % Init(cqDegree,cqType,tqDegree,tqType,nvar,controlGeometry % nElem)
    CALL dfInterp % Init(cqDegree,cqType,tqDegree,tqType,nvar,controlGeometry % nElem)
    CALL dfActual % Init(cqDegree,cqType,tqDegree,tqType,nvar,controlGeometry % nElem)
    CALL dfError % Init(cqDegree,cqType,tqDegree,tqType,nvar,controlGeometry % nElem)
    ! Create work objects
    CALL workScalar % Init(cqDegree,cqType,tqDegree,tqType,3*nvar,controlGeometry % nElem)
    CALL workVector % Init(cqDegree,cqType,tqDegree,tqType,3*nvar,controlGeometry % nElem)
    CALL workTensor % Init(cqDegree,cqType,tqDegree,tqType,3*nvar,controlGeometry % nElem)
    ! Create the equation parser object
    DO row = 1,3
      feq(row) = EquationParser(vectorChar(row), (/'x','y','z'/))
    ENDDO
    DO col = 1,3
      DO row = 1,3
        dfeqChar(row,col) = EquationParser(tensorChar(row,col), (/'x','y','z'/))
      ENDDO
    ENDDO
    ! Load the control function
    DO iel = 1, controlGeometry % nElem
      DO ivar = 1, nvar
        DO k = 0, cqDegree
          DO j = 0, cqDegree
            DO i = 0, cqDegree
              DO row = 1,3
                f % interior % hostData(row,i,j,k,ivar,iel) = &
                  feq(row) % Evaluate( controlGeometry % x % interior % hostData(1:3,i,j,k,1,iel) )
              ENDDO
              DO col = 1,3
                DO row = 1,3
                  dfActual % interior % hostData(row,col,i,j,k,ivar,iel) = &
                    dfeqChar(row,col) % Evaluate( controlGeometry % x % interior % hostData(1:3,i,j,k,1,iel) )
                ENDDO
              ENDDO
            ENDDO
            DO iside = 1,6
              DO row = 1,3
                f % boundary % hostData(row,j,k,ivar,iside,iel) = &
                  feq(row) % Evaluate( controlGeometry % x % boundary % hostData(1:3,j,k,1,iside,iel) )
              ENDDO
            ENDDO
          ENDDO
        ENDDO
      ENDDO
    ENDDO
#ifdef GPU
    IF (gpuAccel) THEN
      CALL f % UpdateDevice()
    END IF
#endif
    ! Run the grid interpolation
    CALL f % Gradient(workScalar,workVector,workTensor,controlGeometry,dfInterp,dForm,gpuAccel)
#ifdef GPU
    IF (gpuAccel) THEN
      CALL dfInterp % UpdateHost()
    END IF
#endif
    dfError = dfActual - dfInterp
    !PRINT*, dfError % interior % hostData
    ! Calculate Absolute Maximum Error
    maxErrors = dfError % AbsMaxInterior( )
    msg = "Numerical Error : "//Float2Str(maxErrors(1))
    IF (maxErrors(1) > tolerance) THEN
      error = error + 1
      ERROR(TRIM(msg))
      ERROR("Status : [FAIL]")
    ELSE
      INFO(TRIM(msg))
      INFO("Status : [PASS]")
    END IF
    ! Clean up
    CALL controlMesh % Free()
    CALL controlGeometry % Free()
    CALL f % Free()
    CALL workScalar % Free()
    CALL workVector % Free()
    CALL workTensor % Free()
    CALL dfInterp % Free()
    CALL dfActual % Free()
    CALL dfError % Free()
  END SUBROUTINE VectorGradient3D_Test
Call graph
vectorgradient3d_test calls int2str, info, equationparser, float2str
self calls vectorgradient3d_test