Write_SEMHex – SELF
Write_SEMHex Subroutine
Anti-Capitalist Software License
32 statements
Source File
public subroutine Write_SEMHex(myGeom, fileName)
Arguments
Type Intent Optional Attributes Name
class(SEMHex), intent(in) :: myGeom
character, intent(in), optional :: fileName
Calls
Contents
Source Code
Write_SEMHex
Source Code
  SUBROUTINE Write_SEMHex(myGeom,fileName)
    IMPLICIT NONE
    CLASS(SEMHex),INTENT(in) :: myGeom
    CHARACTER(*),OPTIONAL,INTENT(in) :: fileName
    ! Local
    INTEGER(HID_T) :: fileId
    ! Local
    CHARACTER(LEN=self_FileNameLength) :: pickupFile
    IF( PRESENT(filename) )THEN
      pickupFile = filename
    ELSE
      pickupFile = 'mesh.h5'
    ENDIF
    CALL Open_HDF5(pickupFile,H5F_ACC_TRUNC_F,fileId)
    CALL CreateGroup_HDF5(fileId,'/quadrature')
    CALL WriteArray_HDF5(fileId,'/quadrature/xi', &
                         myGeom % x % interp % controlPoints)
    CALL WriteArray_HDF5(fileId,'/quadrature/weights', &
                         myGeom % x % interp % qWeights)
    CALL WriteArray_HDF5(fileId,'/quadrature/dgmatrix', &
                         myGeom % x % interp % dgMatrix)
    CALL WriteArray_HDF5(fileId,'/quadrature/dmatrix', &
                         myGeom % x % interp % dMatrix)
    CALL CreateGroup_HDF5(fileId,'/mesh')
    CALL CreateGroup_HDF5(fileId,'/mesh/interior')
    CALL CreateGroup_HDF5(fileId,'/mesh/boundary')
    CALL WriteArray_HDF5(fileId,'/mesh/interior/x',myGeom % x % interior)
    CALL WriteArray_HDF5(fileId,'/mesh/interior/dxds',myGeom % dxds % interior)
    CALL WriteArray_HDF5(fileId,'/mesh/interior/dsdx',myGeom % dsdx % interior)
    CALL WriteArray_HDF5(fileId,'/mesh/interior/J',myGeom % J % interior)
    CALL WriteArray_HDF5(fileId,'/mesh/boundary/x',myGeom % x % boundary)
    CALL WriteArray_HDF5(fileId,'/mesh/boundary/dxds',myGeom % dxds % boundary)
    CALL WriteArray_HDF5(fileId,'/mesh/boundary/dsdx',myGeom % dsdx % boundary)
    CALL WriteArray_HDF5(fileId,'/mesh/boundary/nHat',myGeom % nHat % boundary)
    CALL WriteArray_HDF5(fileId,'/mesh/boundary/nScale',myGeom % nScale % boundary)
    CALL WriteArray_HDF5(fileId,'/mesh/boundary/J',myGeom % J % boundary)
    CALL Close_HDF5(fileId)
  END SUBROUTINE Write_SEMHex
Call graph
write_semhex calls writearray_hdf5, close_hdf5, open_hdf5, creategroup_hdf5