Write_DG3D – SELF
Write_DG3D Subroutine
Anti-Capitalist Software License
73 statements
Source File
public subroutine Write_DG3D(this, fileName)
Arguments
Type Intent Optional Attributes Name
class(DG3D), intent(in) :: this
character, intent(in) :: fileName
Calls
Contents
Source Code
Write_DG3D
Source Code
  SUBROUTINE Write_DG3D(this,fileName)
    IMPLICIT NONE
    CLASS(DG3D),INTENT(in) :: this
    CHARACTER(*),INTENT(in) :: fileName
    ! Local
    INTEGER(HID_T) :: fileId
    INTEGER(HID_T) :: solOffset(1:5)
    INTEGER(HID_T) :: xOffset(1:6)
    INTEGER(HID_T) :: bOffset(1:5)
    INTEGER(HID_T) :: bxOffset(1:6)
    INTEGER(HID_T) :: solGlobalDims(1:5)
    INTEGER(HID_T) :: xGlobalDims(1:6)
    INTEGER(HID_T) :: bGlobalDims(1:5)
    INTEGER(HID_T) :: bxGlobalDims(1:6)
    INTEGER :: firstElem
    IF (this % decomp % mpiEnabled) THEN
      CALL Open_HDF5(fileName,H5F_ACC_TRUNC_F,fileId, &
                     this % decomp % mpiComm)
      firstElem = this % decomp % offsetElem % hostData(this % decomp % rankId)
      solOffset(1:5) = (/0,0,0,1,firstElem/)
      solGlobalDims(1:5) = (/this % solution % N, &
                             this % solution % N, &
                             this % solution % N, &
                             this % solution % nVar, &
                             this % decomp % nElem/)
      xOffset(1:6) = (/1,0,0,0,1,firstElem/)
      xGlobalDims(1:6) = (/3, &
                           this % solution % N, &
                           this % solution % N, &
                           this % solution % N, &
                           this % solution % nVar, &
                           this % decomp % nElem/)
      ! Offsets and dimensions for element boundary data
      bOffset(1:5) = (/0,0,1,1,firstElem/)
      bGlobalDims(1:5) = (/this % solution % N, &
                           this % solution % N, &
                           this % solution % nVar, &
                           6,&
                           this % decomp % nElem/)
      bxOffset(1:6) = (/1,0,0,1,1,firstElem/)
      bxGlobalDims(1:6) = (/3,&
                           this % solution % N, &
                           this % solution % N, &
                           this % solution % nVar, &
                           6,&
                           this % decomp % nElem/)
      CALL CreateGroup_HDF5(fileId,'/quadrature')
      IF( this % decomp % rankId == 0 )THEN
        CALL WriteArray_HDF5(fileId,'/quadrature/xi', &
                             this % solution % interp % controlPoints)
        CALL WriteArray_HDF5(fileId,'/quadrature/weights', &
                             this % solution % interp % qWeights)
        CALL WriteArray_HDF5(fileId,'/quadrature/dgmatrix', &
                             this % solution % interp % dgMatrix)
        CALL WriteArray_HDF5(fileId,'/quadrature/dmatrix', &
                             this % solution % interp % dMatrix)
      ENDIF
      CALL CreateGroup_HDF5(fileId,'/state')
      CALL CreateGroup_HDF5(fileId,'/state/interior')
      CALL CreateGroup_HDF5(fileId,'/state/boundary')
      CALL CreateGroup_HDF5(fileId,'/mesh')
      CALL CreateGroup_HDF5(fileId,'/mesh/interior')
      CALL CreateGroup_HDF5(fileId,'/mesh/boundary')
      CALL WriteArray_HDF5(fileId,'/state/interior/solution', &
                           this % solution % interior,solOffset,solGlobalDims)
      CALL WriteArray_HDF5(fileId,'/state/boundary/solution', &
                           this % solution % boundary,bOffset,bGlobalDims)
      CALL WriteArray_HDF5(fileId,'/state/interior/fluxDivergence', &
                           this % fluxDivergence % interior,solOffset,solGlobalDims)
      CALL WriteArray_HDF5(fileId,'/state/interior/flux', &
                           this % flux % interior,xOffset,xGlobalDims)
      CALL WriteArray_HDF5(fileId,'/state/boundary/flux', &
                           this % flux % boundary,bxOffset,bxGlobalDims)
      CALL WriteArray_HDF5(fileId,'/state/interior/solutionGradient', &
                           this % solutionGradient % interior,xOffset,xGlobalDims)
      CALL WriteArray_HDF5(fileId,'/state/boundary/solutionGradient', &
                           this % solutionGradient % boundary,bxOffset,bxGlobalDims)
      CALL WriteArray_HDF5(fileId,'/mesh/interior/x', &
                           this % geometry % x % interior,xOffset,xGlobalDims)
      CALL WriteArray_HDF5(fileId,'/mesh/boundary/x', &
                           this % geometry % x % boundary,bxOffset,bxGlobalDims)
      CALL Close_HDF5(fileId)
    ELSE
      CALL Open_HDF5(fileName,H5F_ACC_TRUNC_F,fileId)
      CALL CreateGroup_HDF5(fileId,'/quadrature')
      CALL WriteArray_HDF5(fileId,'/quadrature/xi', &
                           this % solution % interp % controlPoints)
      CALL WriteArray_HDF5(fileId,'/quadrature/weights', &
                           this % solution % interp % qWeights)
      CALL WriteArray_HDF5(fileId,'/quadrature/dgmatrix', &
                           this % solution % interp % dgMatrix)
      CALL WriteArray_HDF5(fileId,'/quadrature/dmatrix', &
                           this % solution % interp % dMatrix)
      CALL CreateGroup_HDF5(fileId,'/state')
      CALL CreateGroup_HDF5(fileId,'/state/interior')
      CALL CreateGroup_HDF5(fileId,'/state/boundary')
      CALL CreateGroup_HDF5(fileId,'/mesh')
      CALL CreateGroup_HDF5(fileId,'/mesh/interior')
      CALL CreateGroup_HDF5(fileId,'/mesh/boundary')
      CALL WriteArray_HDF5(fileId,'/state/interior/solution',this % solution % interior)
      CALL WriteArray_HDF5(fileId,'/state/boundary/solution',this % solution % boundary)
      CALL WriteArray_HDF5(fileId,'/state/interior/fluxDivergence',this % fluxDivergence % interior)
      CALL WriteArray_HDF5(fileId,'/state/interior/flux',this % flux % interior)
      CALL WriteArray_HDF5(fileId,'/state/boundary/flux',this % flux % boundary)
      CALL WriteArray_HDF5(fileId,'/state/interior/solutionGradient',this % solutionGradient % interior)
      CALL WriteArray_HDF5(fileId,'/state/boundary/solutionGradient',this % solutionGradient % boundary)
      CALL WriteArray_HDF5(fileId,'/mesh/interior/x',this % geometry % x % interior)
      CALL WriteArray_HDF5(fileId,'/mesh/boundary/x',this % geometry % x % boundary)
      CALL Close_HDF5(fileId)
    END IF
  END SUBROUTINE Write_DG3D
Call graph
write_dg3d calls close_hdf5, writearray_hdf5, creategroup_hdf5, open_hdf5