timeout: 3600s

steps:

- id: SELF Dependencies Build
  name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '.',
         '-t',
         'gcr.io/${PROJECT_ID}/self-dep:${_TAG}']

substitutions:
  _TAG: 'latest'

images: ['gcr.io/${PROJECT_ID}/self-dep:${_TAG}']
