
steps:
- id: Ubuntu 22.04 ROCm 5.7
  name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '--build-arg','ROCM_VERSION=5.7',
         '-f',
         'docker/deps/ubuntu2204/rocm/Dockerfile',
         '.',
         '-t',
         'us-docker.pkg.dev/${PROJECT_ID}/self-base/ubuntu2204-rocm-5.7:latest']
  waitFor: ['-']

- id: Ubuntu 22.04 ROCm 5.6
  name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '--build-arg','ROCM_VERSION=5.6',
         '-f',
         'docker/deps/ubuntu2204/rocm/Dockerfile',
         '.',
         '-t',
         'us-docker.pkg.dev/${PROJECT_ID}/self-base/ubuntu2204-rocm-5.6:latest']
  waitFor: ['-']

- id: Ubuntu 22.04 ROCm 5.5
  name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '--build-arg','ROCM_VERSION=5.5',
         '-f',
         'docker/deps/ubuntu2204/rocm/Dockerfile',
         '.',
         '-t',
         'us-docker.pkg.dev/${PROJECT_ID}/self-base/ubuntu2204-rocm-5.5:latest']
  waitFor: ['-']

options:
  machineType: 'N1_HIGHCPU_32'

images:
- 'us-docker.pkg.dev/${PROJECT_ID}/self-base/ubuntu2204-rocm-5.7:latest'
- 'us-docker.pkg.dev/${PROJECT_ID}/self-base/ubuntu2204-rocm-5.6:latest'
- 'us-docker.pkg.dev/${PROJECT_ID}/self-base/ubuntu2204-rocm-5.5:latest'


timeout: 14400s
