
steps:
- id: Ubuntu 22.04
  name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '--build-arg','GPU_TARGET=gfx90a',
         '--build-arg','BUILD_TYPE=Debug',
         '-f',
         'docker/ubuntu2204/rocm-${_ROCM_VERSION}/${_HIP_PLATFORM}/Dockerfile.rocm',
         '.',
         '-t',
         'us-docker.pkg.dev/${PROJECT_ID}/self/rocm-${_ROCM_VERSION}_${_HIP_PLATFORM}:dev']


images:
- 'us-docker.pkg.dev/${PROJECT_ID}/self/rocm-${_ROCM_VERSION}_${_HIP_PLATFORM}:dev'

options:
  diskSizeGb: 100
  machineType: 'E2_HIGHCPU_32'

timeout: 14400s

substitutions:
  _GPU_TARGET: 'gfx90a'
  _HIP_PLATFORM: 'amd'
  _ROCM_VERSION: '5.7'
