
steps:
- id: Build Image
  name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '--build-arg','GPU_TARGET=gfx90a',
         '--build-arg','BUILD_TYPE=Debug',
         '-f',
         'docker/${_OS}/rocm-${_ROCM_VERSION}/${_HIP_PLATFORM}/Dockerfile',
         '.',
         '-t',
         'us-docker.pkg.dev/${PROJECT_ID}/self/${_OS}-rocm-${_ROCM_VERSION}_${_HIP_PLATFORM}:${SHORT_SHA}']

- id: Run CTests
  name: 'us-docker.pkg.dev/${PROJECT_ID}/self/${_OS}-rocm-${_ROCM_VERSION}_${_HIP_PLATFORM}:${SHORT_SHA}'
  entrypoint: '/bin/bash'
  args: 
  - '-c'
  - |
     . /etc/profile.d/z10_spack_environment.sh
     ctest --test-dir /build/build/test


images:
- 'us-docker.pkg.dev/${PROJECT_ID}/self/rocm-${_ROCM_VERSION}_${_HIP_PLATFORM}:${SHORT_SHA}'

options:
  diskSizeGb: 100
  machineType: 'E2_HIGHCPU_32'

timeout: 14400s

substitutions:
  _GPU_TARGET: 'gfx90a'
  _HIP_PLATFORM: 'amd'
  _ROCM_VERSION: '5.7'
  _OS: 'ubuntu2204'
