name: Publish documentation
on:
  pull_request:
    branches:
        - main

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install docs dependencies
        run: |
          pip install -r docs/requirements.txt

      - name: Generate API docs
        run: |
          python -m pip install --upgrade pip
          ford self.md

