name: pr-template-check

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, labeled, unlabeled]

jobs:
    description:
        name: pull-request-description
        runs-on: ubuntu-22.04
        defaults:
            run:
              shell: bash
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Check the pull request description
              run: |
                python3 .github/scripts/pr_body_check.py
