name: CI

on:
  push:
    branches: 
      - main
    paths-ignore:
      - 'AUTHORS.md'
      - 'LICENSE.md'
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'AUTHORS.md'
      - 'LICENSE.md'
      - 'README.md'
      
jobs:
  test:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: ${{ matrix.os_name }} - ${{ matrix.compiler }} - ${{ matrix.test_type }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux
          - os: ubuntu-22.04
            os_name: linux
            compiler: gfortran-9
            shell: bash
            test_type: regular
            coverage: false
    # Set default shell as suggested here: https://github.community/t/setting-default-shell-or-other-step-metadata-conditionally-in-workflows/154055
    defaults:
      run:
        shell: ${{ matrix.shell }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          ./Utilities/bootstrap
      - name: Show version information
        run: |
          ${{ matrix.compiler }} --version
      - name: Build
        run: |
          make -j 2 FC=${{ matrix.compiler }}
      - name: Run regular function tests
        if: ${{ matrix.test_type == 'regular' }}
        run: |
          ./HOHQMesh -test
      - name: Run memory checks with Valgrind (only Linux)
        if: ${{ matrix.os_name == 'linux' && matrix.test_type == 'valgrind' }}
        run: |
          sudo apt-get install -y valgrind
          valgrind --error-exitcode=1 -s ./HOHQMesh -test
      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      - name: Setup tmate session for debugging
        if: ${{ matrix.os == 'windows-latest' && github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled && always() }}
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 15
      - name: Run tests for coverage
        if: ${{ matrix.coverage }}
        run: |
          sudo apt-get install -y lcov
          FC=${{ matrix.compiler }} ./Utilities/createcoverage
      - uses: codecov/codecov-action@v3
        if: ${{ matrix.coverage }}
        with:
          files: ./lcov.info
          flags: unittests
          name: codecov-umbrella
      - name: Coveralls
        if: ${{ matrix.coverage }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./lcov.info